### ISSUE TITLE
[Bug]:  'ADetailer ControlNet weight'

### ISSUE THREAD

**Issue by LiqYaxi** [Bing-su/adetailer#110]
### Describe the bug

I don't know if it ran successfully

On the left is mine, there are errors; On the right is a friend's without any mistakes
  
![a55bbca8b4b0a67eba8008b4d00a1efc](https://github.com/Bing-su/adetailer/assets/116090990/c6902628-04e1-4e5b-9dcd-ce2872988f11)

and I can guarantee that all the plugins I download are the latest

### Full console logs

```Shell
Error running process: E:\sd\04cf8f3bfkac086e659e8c5cdb75b3d4\extensions\adetailer\scripts\!adetailer.py
Traceback (most recent call last):
  File "E:\sd\04cf8f3bfkac086e659e8c5cdb75b3d4\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "E:\sd\04cf8f3bfkac086e659e8c5cdb75b3d4\extensions\adetailer\scripts\!adetailer.py", line 452, in process
    extra_params = self.extra_params(arg_list)
  File "E:\sd\04cf8f3bfkac086e659e8c5cdb75b3d4\extensions\adetailer\scripts\!adetailer.py", line 193, in extra_params
    params.update(args.extra_params(suffix=suffix(n)))
  File "E:\sd\04cf8f3bfkac086e659e8c5cdb75b3d4\extensions\adetailer\adetailer\args.py", line 122, in extra_params
    ppop("ADetailer ControlNet weight", cond=1.0)
  File "E:\sd\04cf8f3bfkac086e659e8c5cdb75b3d4\extensions\adetailer\adetailer\args.py", line 73, in ppop
    value = p[key]
KeyError: 'ADetailer ControlNet weight'
```

### List of installed extensions

![屏幕截图_20230601_231152](https://github.com/Bing-su/adetailer/assets/116090990/4d6d770a-066a-4d6a-a6c5-e01c36b3c7b2)

**Comment by slikkvikk** [comment]
> Getting same error. It may be the new ControlNet implementation causing these issues. I have ControlNet disabled for ADetailer.

Disregard this observation. My issue was being caused by the extension not detecting a face on the output.
ControlNet support is working.

**Comment by Bing-su** [comment]
This error occurred when the ControlNet model was `None`, sorry.

**Comment by clzzy** [comment]
Same error, How to fix it?
