### ISSUE TITLE
[Bug]: error when running batch scripts

### ISSUE THREAD

**Issue by alenknight** [Bing-su/adetailer#126]
### Describe the bug

when i run adetailer in bulk... sometimes (oddly not always)... i'm getting an error (see below).
i'm on the latest build as of 6/8/2023 
i'm not using controlnet  (though it happens when using it as well).  
only occurs when running hires fix.

### Full console logs

```Shell
Error running postprocess_batch: C:\AI\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "C:\AI\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 552, in postprocess_image
    is_processed |= self._postprocess_image(p, pp, args, n=n)
  File "C:\AI\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 522, in _postprocess_image
    processed = process_images(p2)
  File "C:\AI\stable-diffusion-webui\modules\processing.py", line 610, in process_images
    res = process_images_inner(p)
  File "C:\AI\stable-diffusion-webui\modules\processing.py", line 775, in process_images_inner
    image = apply_overlay(image, p.paste_to, i, p.overlay_images)
  File "C:\AI\stable-diffusion-webui\modules\processing.py", line 70, in apply_overlay
    image = images.resize_image(1, image, w, h)
  File "C:\AI\stable-diffusion-webui\modules\images.py", line 288, in resize_image
    resized = resize(im, src_w, src_h)
  File "C:\AI\stable-diffusion-webui\modules\images.py", line 271, in resize
    im = upscaler.scaler.upscale(im, scale, upscaler.data_path)
  File "C:\AI\stable-diffusion-webui\modules\upscaler.py", line 62, in upscale
    img = self.do_upscale(img, selected_model)
  File "C:\AI\stable-diffusion-webui\modules\esrgan_model.py", line 150, in do_upscale
    img = esrgan_upscale(model, img)
  File "C:\AI\stable-diffusion-webui\modules\esrgan_model.py", line 224, in esrgan_upscale
    output = upscale_without_tiling(model, tile)
  File "C:\AI\stable-diffusion-webui\modules\esrgan_model.py", line 203, in upscale_without_tiling
    output = model(img)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\AI\stable-diffusion-webui\modules\esrgan_model_arch.py", line 61, in forward
    return self.model(feat)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\AI\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 415, in lora_Conv2d_forward
    return torch.nn.Conv2d_forward_before_lora(self, input)
  File "C:\AI\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris\lycoris.py", line 753, in lyco_Conv2d_forward
    return torch.nn.Conv2d_forward_before_lyco(self, input)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 192, 192] to have 3 channels, but got 4 channels instead
```

### List of installed extensions

![Screenshot 2023-06-07 at 8 22 08 PM](https://github.com/Bing-su/adetailer/assets/22153900/5ed75d4b-cb51-4054-a800-fac841e368e5)

**Comment by alenknight** [comment]
> This error occurs when ESRGAN is used as the upscaler and the resolution is not a multiple of 32.

isn't almost every upscaler ESRGAN?  I'm using Ultrasharp-4x.... which is in the ESRGAN folder
I know error shows ESRGAN... but that was Adetailer choosing that, no?

**Comment by Bing-su** [comment]
I've previously considered changing the upscaler only in the ADetailer to prevent this error, but that's not possible.

I'm not sure about the resolution, sorry.

**Comment by alenknight** [comment]
> ously considered changing the upscaler only in the ADetailer to prevent thi

switching to dev branch of A1111 resolved it for some reason... any idea why?

**Comment by Bing-su** [comment]
It looks like the only functional change from 1.3.2 to the dev branch is upcast attention. Did you update from an earlier version?
