### ISSUE TITLE
[Bug]: object has no attribute

### ISSUE THREAD

**Issue by ClipSkipper** [Bing-su/adetailer#152]
### Describe the bug

AttributeError: 'ADetailerArgs' object has no attribute 'ad_use_noise_multiplier'

### Full console logs

```Shell
Error running postprocess_batch: C:\Stable\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
Traceback (most recent call last):
  File "C:\Stable\stable-diffusion-webui\modules\scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "C:\Stable\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 560, in postprocess_image
    is_processed |= self._postprocess_image(p, pp, args, n=n)
  File "C:\Stable\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 482, in _postprocess_image
    i2i = self.get_i2i_p(p, args, pp.image)
  File "C:\Stable\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 348, in get_i2i_p
    initial_noise_multiplier = self.get_initial_noise_multiplier(p, args)
  File "C:\Stable\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 286, in get_initial_noise_multiplier
    if args.ad_use_noise_multiplier:
AttributeError: 'ADetailerArgs' object has no attribute 'ad_use_noise_multiplier'
```

### List of installed extensions

a1111-sd-webui-lycoris
adetailer
multidiffusion-upscaler-for-automatic1111
sd-dynamic-thresholding
sd-webui-additional-networks
sd-webui-controlnet
stable-diffusion-webui-wildcards

**Comment by bell20xx** [comment]
I had the same issue but it got sorted out when I restarted automatic1111. Have you tried that?

**Comment by ClipSkipper** [comment]
> I had the same issue but it got sorted out when I restarted automatic1111. Have you tried that?

Ah yes sorry, it was after updating SD and a couple of extensions.  System reboot made it all go away and it worked as normal.  Anomalous.

**Comment by ClipSkipper** [comment]
Resolved after restart.
