### ISSUE TITLE
[Bug]: With !After Detailer installed, it takes 6 minutes to start Automatic1111 WebUI

### ISSUE THREAD

**Issue by blobbfobb** [Bing-su/adetailer#153]
### Describe the bug

When I start Automatic1111 with !After Detailer installed, it takes aproximately 6 minutes to start the WebUI **every time**. Without adetailer it takes 10 seconds.

Startup hangs after `Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled` (see console log below).

In my network monitor I notice that during that wait time, Python connects to Huggingface multiple times. Immediately after a final connection to Huggingface the startup process suddenly resumes. Without !After Detailer installed Automatic1111 _does not_ attempt to connect to Huggingface!

My guess is that the startup hangs because of these connections to Huggingface for !After Detailer. Are they really necessary or could you remove them? I have deinstalled !After Detailer for the moment.

System: M2 MacBook Air, macOS 13.4

### Full console logs

```Shell
Last login: Wed Jun 21 08:57:24 on ttys000
Restored session: Mi 21 Jun 2023 09:04:55 CEST
USERNAME@Air-von-USERNAME ~ % bash

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ cd stable-diffusion-webui
bash-3.2$ ./webui.sh

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on USERNAME user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.12 (main, Jun  7 2023, 00:38:32) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Version: v1.3.2
Commit hash: baf6946e06249c5af9851c60171692c44ef633e0
Installing requirements



Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
[-] ADetailer initialized. version: 23.6.2, num models: 8
2023-06-21 09:12:01,465 - ControlNet - INFO - ControlNet v1.1.224
ControlNet preprocessor location: /Users/USERNAME/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2023-06-21 09:12:01,500 - ControlNet - INFO - ControlNet v1.1.224
Image Browser: ImageReward is not installed, cannot be used.
Loading weights [5abd718d60] from /Users/USERNAME/stable-diffusion-webui/models/Stable-diffusion/amIReal_V3.safetensors
Creating model from config: /Users/USERNAME/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 408.6s (import torch: 0.7s, import gradio: 0.5s, import ldm: 0.2s, other imports: 0.5s, list SD models: 0.2s, load scripts: 405.6s, reload hypernetworks: 0.2s, create ui: 0.5s, gradio launch: 0.2s).
Loading VAE weights specified in settings: /Users/USERNAME/stable-diffusion-webui/models/VAE/vae-ft-mse-840000-ema-pruned.safetensors
Applying optimization: InvokeAI... done.
Textual inversion embeddings loaded(26): Asian-Less-Neg, bad-hands-5, bad-image-v2-39000, bad-picture-chill-75v, bad_pictures, bad_prompt_version2, BadDream, badhandsv5-neg, badhandv4, BadNegAnatomyV1-neg, CyberRealistic_Negative-neg, easynegative, epiCNegative, kkw-ph1, kkw-ph1-neg, negative_hand-neg, ng_deepnegative_v1_75t, np_simple_negatives, PureErosFace_V1, realisticvision-negative-embedding, rmadanegative402_sd15-neg, rmadanegative4_sd15-neg, ulzzang-6500, UnrealisticDream, verybadimagenegative_v1.2-6400, verybadimagenegative_v1.3
Textual inversion embeddings skipped(7): PhotoHelper, nrealfixer, CinemaHelper, PortraitHelper, rmadanegative-neg, VintageHelper, nfixer
Model loaded in 3.7s (load weights from disk: 0.2s, create model: 0.9s, apply weights to model: 1.0s, apply half(): 0.9s, load VAE: 0.3s, move model to device: 0.5s).
```

**Comment by Bing-su** [comment]
I've added a no huggingface option for users with slow huggingface. Try adding `--ad-no-huggingface` to your command line options.

**Comment by blobbfobb** [comment]
Thank you! Currently the startup is quick with and without that command line option. I'll observe and report.

**Comment by blobbfobb** [comment]
If I startup with `--ad-no-hungingface`, (sometimes?) not all models are available in the extension and I get this error:

```Error running postprocess_batch: /Users/USERNAME/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py
Traceback (most recent call last):
  File "/Users/USERNAME/stable-diffusion-webui/modules/scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "/Users/USERNAME/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 560, in postprocess_image
    is_processed |= self._postprocess_image(p, pp, args, n=n)
  File "/Users/USERNAME/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 494, in _postprocess_image
    ad_model = self.get_ad_model(args.ad_model)
  File "/Users/USERNAME/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 420, in get_ad_model
    raise ValueError(msg)
ValueError: [-] ADetailer: Model 'face_yolo8s.pt' not found. Available models: ['mediapipe_face_full', 'mediapipe_face_short', 'mediapipe_face_mesh']```

**Comment by Bing-su** [comment]
That's right. This option disables the use of models uploaded to the huggingface.

**Comment by blobbfobb** [comment]
Ah, okay, I finally understand. So, I downloaded the models to the adetailer models folder. Now, how do I "enable that option"?
