### ISSUE TITLE
[Bug]: ADetailArgs object has no attribute 'ad_use_noise_multiplier'

### ISSUE THREAD

**Issue by photodarren** [Bing-su/adetailer#154]
### Describe the bug

Running Automatic1111 on a Macbookpro. The script no longer finds the faces and fixes them. 
Error 

Error running postprocess_batch: /Users/darrenhughes/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py
Traceback (most recent call last):
  File "/Users/darrenhughes/stable-diffusion-webui/modules/scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "/Users/darrenhughes/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 560, in postprocess_image
    is_processed |= self._postprocess_image(p, pp, args, n=n)
  File "/Users/darrenhughes/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 482, in _postprocess_image
    i2i = self.get_i2i_p(p, args, pp.image)
  File "/Users/darrenhughes/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 348, in get_i2i_p
    initial_noise_multiplier = self.get_initial_noise_multiplier(p, args)
  File "/Users/darrenhughes/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 286, in get_initial_noise_multiplier
    if args.ad_use_noise_multiplier:
AttributeError: 'ADetailerArgs' object has no attribute 'ad_use_noise_multiplier'

I get this every time I run an image generation, and it doesn't work. 

I notice a recent pull request was for a person 'fixing' the noise multiplier. 
I wonder if this has broken something, or his code has errors for those of us that don't touch noise settings. 

### Full console logs

```Shell
Get this error every time. Was not getting it till the latest commit (21 June 23)

Error running postprocess_batch: /Users/darrenhughes/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py
Traceback (most recent call last):
  File "/Users/darrenhughes/stable-diffusion-webui/modules/scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "/Users/darrenhughes/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 560, in postprocess_image
    is_processed |= self._postprocess_image(p, pp, args, n=n)
  File "/Users/darrenhughes/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 482, in _postprocess_image
    i2i = self.get_i2i_p(p, args, pp.image)
  File "/Users/darrenhughes/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 348, in get_i2i_p
    initial_noise_multiplier = self.get_initial_noise_multiplier(p, args)
  File "/Users/darrenhughes/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 286, in get_initial_noise_multiplier
    if args.ad_use_noise_multiplier:
AttributeError: 'ADetailerArgs' object has no attribute 'ad_use_noise_multiplier'
```

### List of installed extensions

Stable-Diffusion-Webui-Civitai-Helper	https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper.git	main	[920ca326](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/commit/920ca3267f789a72e3225c99f069bf0be0db795d)	Tue May 23 11:53:22 2023	unknown
a1111-mini-paint	https://github.com/0Tick/a1111-mini-paint	main	[8545c9cd](https://github.com/0Tick/a1111-mini-paint/commit/8545c9cdd1f142424e714fad02e03a0f087c55db)	Mon Jun 12 14:04:04 2023	unknown
a1111-sd-webui-tagcomplete	https://github.com/DominikDoom/a1111-sd-webui-tagcomplete.git	main	[d7075c54](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/commit/d7075c5468c9483c89253510d2f080c6071bd513)	Tue Jun 20 16:50:39 2023	unknown
adetailer	https://github.com/Bing-su/adetailer	main	[a1032d89](https://github.com/Bing-su/adetailer/commit/a1032d898018bd37816f26e2ac1a70c618c1b3e8)	Tue Jun 20 14:38:19 2023	unknown
canvas-zoom	https://github.com/richrobber2/canvas-zoom.git	main	[ae44f7fb](https://github.com/richrobber2/canvas-zoom/commit/ae44f7fba3fcc8d118f8905a0888585dd2728a61)	Sat Jun 17 21:41:34 2023	unknown
openpose-editor	https://github.com/fkunn1326/openpose-editor.git	master	[722bca6f](https://github.com/fkunn1326/openpose-editor/commit/722bca6fb9b062815d13b950e7040589abaec797)	Sat Jun 3 04:54:52 2023	unknown
sd-dynamic-prompts	https://github.com/adieyal/sd-dynamic-prompts.git	main	[525ee62a](https://github.com/adieyal/sd-dynamic-prompts/commit/525ee62a9a1ce308a8ae932883be0f4f264282c4)	Mon Jun 19 09:23:10 2023	unknown
sd-dynamic-thresholding	https://github.com/mcmonkeyprojects/sd-dynamic-thresholding.git	master	[023d3e51](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/commit/023d3e51b1a96bd2cc7d6e9ec5229b08e41da730)	Sun Jun 18 19:48:58 2023	unknown
sd-extension-system-info	https://github.com/vladmandic/sd-extension-system-info.git	main	[47df4ccc](https://github.com/vladmandic/sd-extension-system-info/commit/47df4cccb8003ceeb22566ac38c56a0b41819806)	Mon Jun 19 20:39:44 2023	unknown
sd-webui-3d-open-pose-editor	https://github.com/nonnonstop/sd-webui-3d-open-pose-editor.git	main	[f2d5aac5](https://github.com/nonnonstop/sd-webui-3d-open-pose-editor/commit/f2d5aac51d891bc5f266b1549f3cf4495fc52160)	Sat Apr 15 13:21:06 2023	unknown
sd-webui-ar	https://github.com/alemelis/sd-webui-ar.git	main	[9df49dc2](https://github.com/alemelis/sd-webui-ar/commit/9df49dc2d7da7333ac918fbce926c2370a3b8b53)	Wed Apr 12 09:23:17 2023	unknown
sd-webui-aspect-ratio-helper	https://github.com/thomasasfk/sd-webui-aspect-ratio-helper.git	main	[99fcf9b0](https://github.com/thomasasfk/sd-webui-aspect-ratio-helper/commit/99fcf9b0a4e3f8c8cac07b12d17b66f12297b828)	Sun Jun 4 15:39:07 2023	unknown
sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet.git	main	[5fc95279](https://github.com/Mikubill/sd-webui-controlnet/commit/5fc952793aa97bdd0078574b3be8bc98e1fcf2cd)	Sun Jun 18 17:43:46 2023	unknown
sd-webui-depth-lib	https://github.com/jexom/sd-webui-depth-lib	main	[efa9f616](https://github.com/jexom/sd-webui-depth-lib/commit/efa9f616b30ea0f27e5dadf40ab41815012d1d78)	Mon Apr 10 05:27:11 2023	unknown
sd-webui-inpaint-anything	https://github.com/Uminosachi/sd-webui-inpaint-anything.git	main	[d10a4850](https://github.com/Uminosachi/sd-webui-inpaint-anything/commit/d10a4850005525741cfef8d69fae8920402a647e)	Tue Jun 20 07:34:48 2023	unknown
sd-webui-prompt-all-in-one	https://github.com/Physton/sd-webui-prompt-all-in-one	main	[30acf430](https://github.com/Physton/sd-webui-prompt-all-in-one/commit/30acf430e0c3883f9141592b00784914e18b951b)	Fri May 26 05:57:59 2023	unknown
sd-webui-stablesr	https://github.com/pkuliyi2015/sd-webui-stablesr.git	master	[17b75e98](https://github.com/pkuliyi2015/sd-webui-stablesr/commit/17b75e98360c75b70cb7c9c6be02b886fbd73162)	Tue May 23 10:12:17 2023	unknown
stable-diffusion-webui-eyemask	https://github.com/ilian6806/stable-diffusion-webui-eyemask.git	master	[7b803a43](https://github.com/ilian6806/stable-diffusion-webui-eyemask/commit/7b803a438f02b381903916b65cc5b15c98e3231c)	Fri Jun 2 11:15:19 2023	unknown
stable-diffusion-webui-images-browser	https://github.com/AlUlkesh/stable-diffusion-webui-images-browser.git	main	[b2f6e4cb](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/commit/b2f6e4cbe507078e3bf2b9d5fce6f83e2e233aa8)	Thu Jun 8 08:11:43 2023	unknown
stable-diffusion-webui-state	https://github.com/ilian6806/stable-diffusion-webui-state.git	main	[85d8ef19](https://github.com/ilian6806/stable-diffusion-webui-state/commit/85d8ef191d28a918036881ab47523e0c02467ccc)	Sat Jun 10 12:39:50 2023	unknown
stable-diffusion-webui-vectorstudio	https://github.com/GeorgLegato/stable-diffusion-webui-vectorstudio	master	[03535f64](https://github.com/GeorgLegato/stable-diffusion-webui-vectorstudio/commit/03535f64caef1de151122574cf4a39943db6e1eb)	Sun May 28 14:27:48 2023	unknown
ultimate-upscale-for-automatic1111	https://github.com/Coyote-A/ultimate-upscale-for-automatic1111	master	[c99f382b](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/commit/c99f382b31509b87b4d512e70e9caf08ae7a079f)	Tue Jun 13 04:29:35 2023	unknown
LDSR	[built-in](http://127.0.0.1:7860/)	None		Wed Jun 21 10:42:26 2023	
Lora	[built-in](http://127.0.0.1:7860/)	None		Wed Jun 21 10:42:26 2023	
ScuNET	[built-in](http://127.0.0.1:7860/)	None		Wed Jun 21 10:42:26 2023	
SwinIR	[built-in](http://127.0.0.1:7860/)	None		Wed Jun 21 10:42:26 2023	
prompt-bracket-checker	[built-in](http://127.0.0.1:7860/)	None		Wed Jun 21 10:42:26 2023

**Comment by statopre** [comment]
just updated my extensions and now I'm getting this error, too:
Error running postprocess_batch: C:\Programme - Extra\StableDiffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
Traceback (most recent call last):
  File "C:\Programme - Extra\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "C:\Programme - Extra\StableDiffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 560, in postprocess_image
    is_processed |= self._postprocess_image(p, pp, args, n=n)
  File "C:\Programme - Extra\StableDiffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 482, in _postprocess_image
    i2i = self.get_i2i_p(p, args, pp.image)
  File "C:\Programme - Extra\StableDiffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 348, in get_i2i_p
    initial_noise_multiplier = self.get_initial_noise_multiplier(p, args)
  File "C:\Programme - Extra\StableDiffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 286, in get_initial_noise_multiplier
    if args.ad_use_noise_multiplier:
AttributeError: 'ADetailerArgs' object has no attribute 'ad_use_noise_multiplier'

**Comment by Qxzz2** [comment]
I'm also getting this error, identical to mpiquero.

**Comment by mpiquero7164** [comment]
For others with the same error. unchecked installed. deleted folder in extensions. restarted kernel and reinstalled a third time. and restarted kernel again. seems to be working again. if in doubt, reinstall and restart.
