### ISSUE TITLE
Adetailer runs even if off

### ISSUE THREAD

**Issue by Dawgmastah** [Bing-su/adetailer#16]
I have another extension, similar to adetailer, however when trying to do comparison runs, disabling adetailer (latest version), its causing issues anyway

Error running postprocess_batch: X:\STABLEDIFFUSION\AUTOMATIC111\extensions\adetailer\scripts\!adetailer.py
Traceback (most recent call last):
  File "X:\STABLEDIFFUSION\AUTOMATIC111\modules\scripts.py", line 462, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "X:\STABLEDIFFUSION\AUTOMATIC111\extensions\adetailer\scripts\!adetailer.py", line 438, in postprocess_image
    args = get_args(*args_)
  File "X:\STABLEDIFFUSION\AUTOMATIC111\extensions\adetailer\adetailer\args.py", line 73, in get_args
    arg_dict = {all_args.attr: args[i] for i, all_args in enumerate(ALL_ARGS)}
  File "X:\STABLEDIFFUSION\AUTOMATIC111\extensions\adetailer\adetailer\args.py", line 73, in <dictcomp>
    arg_dict = {all_args.attr: args[i] for i, all_args in enumerate(ALL_ARGS)}
IndexError: tuple index out of range

This causes automatic to become unresponsive unless closed

**Comment by Bing-su** [comment]
Do you get the same error after restarting?

**Comment by Dawgmastah** [comment]
Yes if I try running the ZoomEnhance from the Unprompted extension again.
Id I dont use that shortcode I havent run into issues yet

**Comment by Bing-su** [comment]
https://github.com/ThereforeGames/unprompted/issues/93
This issue seems to be similar to yours.
