### ISSUE TITLE
[Bug]: Startup SD error

### ISSUE THREAD

**Issue by rtsbtx** [Bing-su/adetailer#165]
### Describe the bug

Startup SD error

### The entire console log, including python version information, webui version, commit hash, commandline arguments and error traces.

```Shell
Error loading script: !adetailer.py
Traceback (most recent call last):
  File "/home/ubuntu/stable-diffusion-webui/modules/scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/home/ubuntu/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 19, in <module>
    from adetailer import (
  File "/home/ubuntu/stable-diffusion-webui/extensions/adetailer/adetailer/__init__.py", line 2, in <module>
    from .args import AD_ENABLE, ALL_ARGS, ADetailerArgs, EnableChecker
  File "/home/ubuntu/stable-diffusion-webui/extensions/adetailer/adetailer/args.py", line 37, in <module>
    class ADetailerArgs(BaseModel, extra=Extra.forbid):
  File "/home/ubuntu/stable-diffusion-webui/extensions/adetailer/adetailer/args.py", line 69, in ADetailerArgs
    def ad_controlnt_module_validator(cls, values):  # noqa: N805
  File "pydantic/class_validators.py", line 127, in pydantic.class_validators.root_validator
  File "pydantic/class_validators.py", line 156, in pydantic.class_validators._prepare_validator
pydantic.errors.ConfigError: duplicate validator function "adetailer.args.ADetailerArgs.ad_controlnt_module_validator"; if this is intended, set `allow_reuse=True`
```

**Comment by Bing-su** [comment]
Please upload the entire console log. I'm confused as to why the script is being called twice.
