### ISSUE TITLE
[Bug]: ADetailer's ControlNet model: control_v11f1e_sd15tile [a371b31b]

### ISSUE THREAD

**Issue by Zullian** [Bing-su/adetailer#168]
### Describe the bug

With enabled
![image](https://github.com/Bing-su/adetailer/assets/3374100/ba3fec2c-34c8-4516-8b82-c0e393a6b9bc)
![image](https://github.com/Bing-su/adetailer/assets/3374100/62d58736-0be4-48a3-82a4-341c4edcf037)
![image](https://github.com/Bing-su/adetailer/assets/3374100/2e7be244-adee-42f5-a0d2-3d25cf1229c4)

I get following error:

```sh
0: 640x640 2 persons, 10.0ms
Speed: 2.0ms preprocess, 10.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)
2023-06-28 17:51:46,725 - ControlNet - INFO - Loading model from cache: control_v11f1e_sd15_tile [a371b31b]
2023-06-28 17:51:46,753 - ControlNet - INFO - Loading preprocessor: none
2023-06-28 17:51:46,753 - ControlNet - INFO - preprocessor resolution = 512
Error running postprocess_batch: C:\sd.webui\webui\extensions\adetailer\scripts\!adetailer.py
Traceback (most recent call last):
  File "C:\sd.webui\webui\modules\scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "C:\sd.webui\webui\extensions\adetailer\scripts\!adetailer.py", line 560, in postprocess_image
    is_processed |= self._postprocess_image(p, pp, args, n=n)
  File "C:\sd.webui\webui\extensions\adetailer\scripts\!adetailer.py", line 530, in _postprocess_image
    processed = process_images(p2)
  File "C:\sd.webui\webui\modules\processing.py", line 610, in process_images
    res = process_images_inner(p)
  File "C:\sd.webui\webui\modules\processing.py", line 670, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "C:\sd.webui\webui\modules\processing.py", line 1139, in init
    self.sampler = sd_samplers.create_sampler(self.sampler_name, self.sd_model)
  File "C:\sd.webui\webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 362, in <lambda>
    sd_samplers.create_sampler = lambda name, model: self.create_sampler_hijack(
  File "C:\sd.webui\webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 422, in create_sampler_hijack
    self.delegate.prepare_controlnet_tensors(refresh=True)
  File "C:\sd.webui\webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\utils.py", line 243, in wrapper
    return fn(*args, **kwargs)
  File "C:\sd.webui\webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\abstractdiffusion.py", line 466, in prepare_controlnet_tensors
    control_tile = torch.cat(single_batch_tensors, dim=0)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 512 but got size 256 for tensor number 1 in the list.
```

Error is happening only when both options are enabled together "Use separate width/height" and "ControlNet model - tile resample"
![image](https://github.com/Bing-su/adetailer/assets/3374100/965db596-0f46-41c0-918a-5008d86b1456)

and if all scripts are allowed 
![image](https://github.com/Bing-su/adetailer/assets/3374100/c25ea3d9-e62c-49dc-9c22-fb7780287e81)

then with this script "tilediffusion.py" if I use upscaler and put slider to anything above 1
![image](https://github.com/Bing-su/adetailer/assets/3374100/7e5475c1-5fc3-4a8d-b3a1-bbca8316452d)

I get following error due to 2nd upscaling of image before ADetailer:

```sh
0: 640x640 1 person, 8.5ms
Speed: 3.0ms preprocess, 8.5ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)
MixtureOfDiffusers Sampling:   0%|                                                              | 0/20 [00:04<?, ?it/s]
[Tiled Diffusion] upscaling image with 4x_NMKD-Siax_200k...
[Tiled Diffusion] ControlNet found, support is enabled.
2023-06-28 21:44:20,946 - ControlNet - INFO - Loading model from cache: control_v11f1e_sd15_tile [a371b31b]
2023-06-28 21:44:21,235 - ControlNet - INFO - Loading preprocessor: none
2023-06-28 21:44:21,235 - ControlNet - INFO - preprocessor resolution = 2248
MixtureOfDiffusers Sampling:   0%|                                                              | 0/20 [00:00<?, ?it/s]Mixture of Diffusers hooked into 'Euler a' sampler, Tile size: 160x160, Tile batches: 1, Batch size: 8. (ext: ContrlNet)
Error running postprocess_batch: C:\sd.webui\webui\extensions\adetailer\scripts\!adetailer.py
Traceback (most recent call last):
  File "C:\sd.webui\webui\modules\scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "C:\sd.webui\webui\extensions\adetailer\scripts\!adetailer.py", line 560, in postprocess_image
    is_processed |= self._postprocess_image(p, pp, args, n=n)
  File "C:\sd.webui\webui\extensions\adetailer\scripts\!adetailer.py", line 530, in _postprocess_image
    processed = process_images(p2)
  File "C:\sd.webui\webui\modules\processing.py", line 610, in process_images
    res = process_images_inner(p)
  File "C:\sd.webui\webui\modules\processing.py", line 670, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "C:\sd.webui\webui\modules\processing.py", line 1191, in init
    image_masked.paste(image.convert("RGBA").convert("RGBa"), mask=ImageOps.invert(self.mask_for_overlay.convert('L')))
  File "C:\sd.webui\system\python\lib\site-packages\PIL\Image.py", line 1732, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match
```

### The entire console log, including python version information, webui version, commit hash, commandline arguments and error traces.

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.3.2
Commit hash: baf6946e06249c5af9851c60171692c44ef633e0
Installing requirements




Fetching updates for midas...
Checking out commit for midas with hash: 1645b7e...






Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72



Launching Web UI with arguments: --opt-sdp-no-mem-attention --api --theme=dark
No module 'xformers'. Proceeding without it.
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: C:\sd.webui\webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
[-] ADetailer initialized. version: 23.6.4, num models: 12
2023-06-28 17:32:51,046 - ControlNet - INFO - ControlNet v1.1.227
ControlNet preprocessor location: C:\sd.webui\webui\extensions\sd-webui-controlnet\annotator\downloads
2023-06-28 17:32:51,119 - ControlNet - INFO - ControlNet v1.1.227
2023-06-28 17:32:51,473 - roop - INFO - roop v0.0.2
2023-06-28 17:32:51,475 - roop - INFO - roop v0.0.2
Loading weights [71776d06b6] from C:\sd.webui\webui\models\Stable-diffusion\1-consistentFactor_euclidV51.safetensors
Creating model from config: C:\sd.webui\webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
DiffusionWrapper has 859.52 M params.
[AgentScheduler] Runner is paused
[AgentScheduler] Registering APIs
Startup time: 8.8s (import torch: 1.1s, import gradio: 0.8s, import ldm: 0.4s, other imports: 0.9s, load scripts: 4.1s, create ui: 0.6s, gradio launch: 0.6s, scripts app_started_callback: 0.2s).
Loading VAE weights specified in settings: C:\sd.webui\webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt.vae.pt
Applying optimization: sdp-no-mem... done.
Textual inversion embeddings loaded(8): bad-picture-chill-75v, badhandsv5-neg, badhandv4, By bad artist -neg, discomixAnime_v1, easynegative, negative_hand-neg, wlop_style
Model loaded in 8.6s (load weights from disk: 0.8s, create model: 0.8s, apply weights to model: 5.0s, apply half(): 0.3s, load VAE: 0.2s, move model to device: 0.5s, load textual inversion embeddings: 0.9s).
```

### List of installed extensions

![image](https://github.com/Bing-su/adetailer/assets/3374100/995defc7-c2d2-4d89-883c-f864c921917e)

**Comment by Bing-su** [comment]
Thanks for the report, it's hard to make adetailer compatible with all extensions, especially those that touch the internal functions of sd-webui.

**Comment by Zullian** [comment]
I see, and is there any way I can use detailer as inpaint only, when I have large images 4k resolution, and I want to use detailer only to fix face which is let's say 768x768, even tho I set denoising to 0 on img2img, with large images I must enable "Tiled VAE" script, which then "Encode image --> does nothing (denoising 0) --> Decode image"  and takes a lot of unnecessary time, to basically leave image the same so detailer can be run on it after.

And this way with large images I can't even use batch size more than 1 cus this 1st process of encode-decode takes a lot of VRAM, and it could basicly be skipped.

**Comment by Bing-su** [comment]
Just turn off adetailer and inpaint directly from the inpainting tab...

**Comment by Zullian** [comment]
I know, but idk why, I get better results using adetailer.
