### ISSUE TITLE
[Bug]: Error running postprocess_image

### ISSUE THREAD

**Issue by efraxs** [Bing-su/adetailer#173]
### Describe the bug

When i try to use lineart controlnet with adetailer it complete the controlnet task but with the adetailer it shows 

### The entire console log, including python version information, webui version, commit hash, commandline arguments and error traces.

```Shell
`2023-06-29 20:42:59,648 - ControlNet - INFO - Loading model from cache: controlnet11Models_lineart [5c23b17d] 5.47it/s]
2023-06-29 20:42:59,667 - ControlNet - INFO - Loading preprocessor: lineart
2023-06-29 20:42:59,668 - ControlNet - INFO - preprocessor resolution = 328
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  4.47it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  5.10it/s]
0: 640x384 1 face, 13.0ms
Speed: 7.0ms preprocess, 13.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)
  0%|                                                                                            | 0/9 [00:00<?, ?it/s]
*** Error running postprocess_image: C:\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 560, in postprocess_image
        is_processed |= self._postprocess_image(p, pp, args, n=n)
      File "C:\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 530, in _postprocess_image
        processed = process_images(p2)
      File "C:\stable-diffusion-webui\modules\processing.py", line 620, in process_images
        res = process_images_inner(p)
      File "C:\stable-diffusion-webui\modules\processing.py", line 739, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "C:\stable-diffusion-webui\modules\processing.py", line 1316, in sample
        samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
      File "C:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 409, in sample_img2img
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "C:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 278, in launch_sampling
        return func()
      File "C:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 409, in <lambda>
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 190, in forward
        devices.test_for_nans(x_out, "unet")
      File "C:\stable-diffusion-webui\modules\devices.py", line 158, in test_for_nans
        raise NansException(message)
    modules.devices.NansException: A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type. Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check.

---
Total progress: 100%|████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.13it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  5.10it/s]`
```

### List of installed extensions

D-Prompt-Enhancer
tylePile
detailer
booru2prompt
lip-interrogator-ext
gif2gif
prompt-master
sd-dynamic-prompts
sd-webui-controlnet
stable-diffusion-webui-images-browser
stable-diffusion-webui-wd14-tagger
stable-diffusion-webui-wildcards

**Comment by Bing-su** [comment]
see:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6923
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7633
https://github.com/Bing-su/adetailer/issues/164
