### ISSUE TITLE
[Bug]: Can't use "ad_model": "mediapipe_face_all"

### ISSUE THREAD

**Issue by Lemniscatas** [Bing-su/adetailer#176]
### Describe the bug

Hello!

How can I use "mediapipe_face_all" instead of "mediapipe_face_mesh" in API?

And the second question: 
![image](https://github.com/Bing-su/adetailer/assets/134967230/dce7e06b-0794-4b4e-ba1e-3d369d9741fb)

How can I choose module in ControlNet with API?

### The entire console log, including python version information, webui version, commit hash, commandline arguments and error traces.

```Shell
Error running postprocess_batch: C:\Users\user\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
Traceback (most recent call last):
  File "C:\Users\user\stable-diffusion-webui\modules\scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "C:\Users\user\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 560, in postprocess_image
    is_processed |= self._postprocess_image(p, pp, args, n=n)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 498, in _postprocess_image
    pred = predictor(ad_model, pp.image, args.ad_confidence, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\stable-diffusion-webui\extensions\adetailer\adetailer\mediapipe.py", line 24, in mediapipe_predict
    raise RuntimeError(msg)
RuntimeError: [-] ADetailer: Invalid mediapipe model type: mediapipe_face_all
```

**Comment by Lemniscatas** [comment]
I'm sorry, I was inattentive, and wrote "mediapipe_face_all" instead of "mediapipe_face_full". Therefore, there was an error. But How can I choose module in ControlNet with API?, still a question...
