### ISSUE TITLE
Extension failed to run, Pls advice

### ISSUE THREAD

**Issue by zappazack** [Bing-su/adetailer#19]
Receiving the following issue:

Error running postprocess_batch: C:\Users\User\Documents\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
Traceback (most recent call last):
  File "C:\Users\User\Documents\stable-diffusion-webui\modules\scripts.py", line 462, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "C:\Users\User\Documents\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 446, in postprocess_image
    i2i = self.get_i2i_p(p, args, pp.image)
  File "C:\Users\User\Documents\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 409, in get_i2i_p
    self.update_controlnet_args(i2i, args)
  File "C:\Users\User\Documents\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 424, in update_controlnet_args
    self.controlnet_ext.update_scripts_args(
  File "C:\Users\User\Documents\stable-diffusion-webui\extensions\adetailer\controlnet_ext\controlnet_ext.py", line 67, in update_scripts_args
    self._update_scripts_args(p, model, weight)
  File "C:\Users\User\Documents\stable-diffusion-webui\extensions\adetailer\controlnet_ext\controlnet_ext.py", line 57, in _update_scripts_args
    control_mode=self.external_cn.ControlMode.BALANCED,
AttributeError: module 'extensions.sd-webui-controlnet.scripts.external_code' has no attribute 'ControlMode'

Pls advice!

**Comment by Bing-su** [comment]
`ControlNetMode` came out of Mikubill/sd-webui-controlnet a couple of weeks ago, so I can't keep up with all the older versions, sorry.
