### ISSUE TITLE
[Bug]: RuntimeError: Given groups=1

### ISSUE THREAD

**Issue by Neytiri7** [Bing-su/adetailer#195]
### The entire console log, including python version information, webui version, commit hash, commandline arguments and error traces.

```Shell
*** Error running postprocess_image: O:\AI\SynologyDrive\repo\extensions\adetailer\scripts\![adetailer.py](https://oo.pe/http://adetailer.py)

    Traceback (most recent call last):

      File "O:\AI\SynologyDrive\repo\modules\scripts.py", line 514, in postprocess_image

        script.postprocess_image(p, pp, *script_args)

      File "O:\AI\SynologyDrive\repo\extensions\adetailer\adetailer\traceback.py", line 156, in wrapper

        raise error from None

    RuntimeError:

    ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮

    │                                                   System info                                                    │

    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │

    │ ┃             ┃ Value                                                                                          ┃ │

    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │

    │ │    Platform │ Windows-10-10.0.22631-SP0                                                                      │ │

    │ │      Python │ 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]             │ │

    │ │     Version │ v1.4.0                                                                                         │ │

    │ │      Commit │ 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8                                                       │ │

    │ │ Commandline │ ['[launch.py](https://oo.pe/http://launch.py)', '--opt-split-attention', '--autolaunch', '--update-all-extensions', '--lowvram', │ │

    │ │             │ '--xformers', '--use-cpu', 'adetailer']                                                        │ │

    │ └─────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘ │

    │                                                      Inputs                                                      │

    │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │

    │ ┃                 ┃ Value                                                                                      ┃ │

    │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │

    │ │          prompt │ ((ultra realistic:1.3)), (best quality:1.3), (illustration), (hyper detailed), (high       │ │

    │ │                 │ quality), perfect face, masterpiece,  intricate details,                                   │ │

    │ │                 │ <lora:adapted_model_converted:0.7>, <lyco:GoodHands-beta2:0.7>, 1girl, mature female,      │ │

    │ │                 │ small hands, small_head, __001/얼굴_표정__ face, __001/묘사_색상__ color hair,             │ │

    │ │                 │ __001/묘사_색상__ color eyes, __001/얼굴_머리길이__, __001/얼굴_머리스타일_여성__ hair,    │ │

    │ │                 │ __001/묘사_가슴크기__, __001/묘사_체형__ body, __001/묘사_피부톤__ skin,                   │ │

    │ │                 │ __001/기타_시점__, __001/묘사_연령대__, __001/묘사_제스쳐__, __001/시점_앵글__,            │ │

    │ │ negative_prompt │ EasyNegativeV2, FastNegativeV2, {1$$EasyNegative|verybadimagenegative_v1.3},               │ │

    │ │                 │ ng_deepnegative_v1_75t, (negative_hand-neg:2), (worst quality:2), (low quality:2), (normal │ │

    │ │                 │ quality:2), ugly, analogphoto, grayscale:1.2, monochrome, jpeg artifacts, sepia, bad       │ │

    │ │                 │ anatomy, ugly face, long neck, cropped, muscle, necklace, earrings, (Dimple chin, Cleft    │ │

    │ │                 │ chin), strabismus, crossed eyes, squint,                                                   │ │

    │ │          n_iter │ 1                                                                                          │ │

    │ │      batch_size │ 1                                                                                          │ │

    │ │           width │ 512                                                                                        │ │

    │ │          height │ 768                                                                                        │ │

    │ │    sampler_name │ DPM++ 2M SDE Karras                                                                        │ │

    │ │       enable_hr │ True                                                                                       │ │

    │ │     hr_upscaler │ 4x-UltraSharp                                                                              │ │

    │ │      checkpoint │ Artemis-foundation_v9.safetensors                                                          │ │

    │ │             vae │ vae-ft-mse-840000-ema-pruned.ckpt                                                          │ │

    │ │            unet │ Automatic                                                                                  │ │

    │ └─────────────────┴────────────────────────────────────────────────────────────────────────────────────────────┘ │

    │                 ADetailer                                                                                        │

    │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓                                                                        │

    │ ┃                     ┃ Value           ┃                                                                        │

    │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩                                                                        │

    │ │             version │ 23.7.5          │                                                                        │

    │ │            ad_model │ face_yolov8n.pt │                                                                        │

    │ │           ad_prompt │                 │                                                                        │

    │ │  ad_negative_prompt │                 │                                                                        │

    │ │ ad_controlnet_model │ None            │                                                                        │

    │ │              is_api │ False           │                                                                        │

    │ └─────────────────────┴─────────────────┘                                                                        │

    │ ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮             │

    │ │ O:\AI\SynologyDrive\repo\extensions\adetailer\adetailer\traceback.py:136 in wrapper              │             │

    │ │                                                                                                  │             │

    │ │   133 │   │   width = width - 4 if width > 4 else None                                           │             │

    │ │   134 │   │   console = Console(file=string, force_terminal=force_terminal, width=width)         │             │

    │ │   135 │   │   try:                                                                               │             │

    │ │ ❱ 136 │   │   │   return func(*args, **kwargs)                                                   │             │

    │ │   137 │   │   except Exception as e:                                                             │             │

    │ │   138 │   │   │   tables = [                                                                     │             │

    │ │   139 │   │   │   │   get_table(title, data)                                                     │             │

    │ │                                                                                                  │             │

    │ │ O:\AI\SynologyDrive\repo\extensions\adetailer\scripts\![adetailer.py:613](https://oo.pe/http://adetailer.py:613) in postprocess_image     │             │

    │ │                                                                                                  │             │

    │ │   610 │   │   │   for n, args in enumerate(arg_list):                                            │             │

    │ │   611 │   │   │   │   if [args.ad](https://oo.pe/http://args.ad)_model == "None":                                                │             │

    │ │   612 │   │   │   │   │   continue                                                               │             │

    │ │ ❱ 613 │   │   │   │   is_processed |= self._postprocess_image(p, pp, args, n=n)                  │             │

    │ │   614 │   │                                                                                      │             │

    │ │   615 │   │   if is_processed:                                                                   │             │

    │ │   616 │   │   │   [self.save](https://oo.pe/http://self.save)_image(                                                               │             │

    │ │                                                                                                  │             │

    │ │ O:\AI\SynologyDrive\repo\extensions\adetailer\scripts\![adetailer.py:573](https://oo.pe/http://adetailer.py:573) in _postprocess_image    │             │

    │ │                                                                                                  │             │

    │ │   570 │   │   │   p2.subseed = subseed + j                                                       │             │

    │ │   571 │   │   │                                                                                  │             │

    │ │   572 │   │   │   try:                                                                           │             │

    │ │ ❱ 573 │   │   │   │   processed = process_images(p2)                                             │             │

    │ │   574 │   │   │   except NansException as e:                                                     │             │

    │ │   575 │   │   │   │   msg = f"[-] ADetailer: 'NansException' occurred with {ordinal(n + 1)} se   │             │

    │ │   576 │   │   │   │   print(msg, file=sys.stderr)                                                │             │

    │ │                                                                                                  │             │

    │ │ O:\AI\SynologyDrive\repo\modules\processing.py:620 in process_images                             │             │

    │ │                                                                                                  │             │

    │ │    617 │   │                                                                                     │             │

    │ │    618 │   │   sd_models.apply_token_merging([p.sd](https://oo.pe/http://p.sd)_model, p.get_token_merging_ratio())            │             │

    │ │    619 │   │                                                                                     │             │

    │ │ ❱  620 │   │   res = process_images_inner(p)                                                     │             │

    │ │    621 │                                                                                         │             │

    │ │    622 │   finally:                                                                              │             │

    │ │    623 │   │   sd_models.apply_token_merging([p.sd](https://oo.pe/http://p.sd)_model, 0)                                      │             │

    │ │                                                                                                  │             │

    │ │ O:\AI\SynologyDrive\repo\modules\processing.py:786 in process_images_inner                       │             │

    │ │                                                                                                  │             │

    │ │    783 │   │   │   │   │   │   [images.save](https://oo.pe/http://images.save)_image(image_without_cc, p.outpath_samples, "", p.see  │             │

    │ │    784 │   │   │   │   │   image = apply_color_correction(p.color_corrections[i], image)         │             │

    │ │    785 │   │   │   │                                                                             │             │

    │ │ ❱  786 │   │   │   │   image = apply_overlay(image, p.paste_to, i, p.overlay_images)             │             │

    │ │    787 │   │   │   │                                                                             │             │

    │ │    788 │   │   │   │   if opts.samples_save and not [p.do](https://oo.pe/http://p.do)_not_save_samples:                       │             │

    │ │    789 │   │   │   │   │   [images.save](https://oo.pe/http://images.save)_image(image, p.outpath_samples, "", p.seeds[i], p.prompt  │             │

    │ │                                                                                                  │             │

    │ │ O:\AI\SynologyDrive\repo\modules\processing.py:70 in apply_overlay                               │             │

    │ │                                                                                                  │             │

    │ │     67 │   if paste_loc is not None:                                                             │             │

    │ │     68 │   │   x, y, w, h = paste_loc                                                            │             │

    │ │     69 │   │   base_image = [Image.new](https://oo.pe/http://Image.new)('RGBA', (overlay.width, overlay.height))                   │             │

    │ │ ❱   70 │   │   image = images.resize_image(1, image, w, h)                                       │             │

    │ │     71 │   │   base_image.paste(image, (x, y))                                                   │             │

    │ │     72 │   │   image = base_image                                                                │             │

    │ │     73                                                                                           │             │

    │ │                                                                                                  │             │

    │ │ O:\AI\SynologyDrive\repo\modules\images.py:288 in resize_image                                   │             │

    │ │                                                                                                  │             │

    │ │   285 │   │   src_w = width if ratio > src_ratio else im.width * height // im.height             │             │

    │ │   286 │   │   src_h = height if ratio <= src_ratio else im.height * width // im.width            │             │

    │ │   287 │   │                                                                                      │             │

    │ │ ❱ 288 │   │   resized = resize(im, src_w, src_h)                                                 │             │

    │ │   289 │   │   res = [Image.new](https://oo.pe/http://Image.new)("RGB", (width, height))                                            │             │

    │ │   290 │   │   res.paste(resized, box=(width // 2 - src_w // 2, height // 2 - src_h // 2))        │             │

    │ │   291                                                                                            │             │

    │ │                                                                                                  │             │

    │ │ O:\AI\SynologyDrive\repo\modules\images.py:271 in resize                                         │             │

    │ │                                                                                                  │             │

    │ │   268 │   │   │   else:                                                                          │             │

    │ │   269 │   │   │   │   upscaler = upscalers[0]                                                    │             │

    │ │   270 │   │   │                                                                                  │             │

    │ │ ❱ 271 │   │   │   im = upscaler.scaler.upscale(im, scale, [upscaler.data](https://oo.pe/http://upscaler.data)_path)                    │             │

    │ │   272 │   │                                                                                      │             │

    │ │   273 │   │   if im.width != w or im.height != h:                                                │             │

    │ │   274 │   │   │   im = im.resize((w, h), resample=LANCZOS)                                       │             │

    │ │                                                                                                  │             │

    │ │ O:\AI\SynologyDrive\repo\modules\upscaler.py:62 in upscale                                       │             │

    │ │                                                                                                  │             │

    │ │    59 │   │   for _ in range(3):                                                                 │             │

    │ │    60 │   │   │   shape = (img.width, img.height)                                                │             │

    │ │    61 │   │   │                                                                                  │             │

    │ │ ❱  62 │   │   │   img = [self.do](https://oo.pe/http://self.do)_upscale(img, selected_model)                                     │             │

    │ │    63 │   │   │                                                                                  │             │

    │ │    64 │   │   │   if shape == (img.width, img.height):                                           │             │

    │ │    65 │   │   │   │   break                                                                      │             │

    │ │                                                                                                  │             │

    │ │ O:\AI\SynologyDrive\repo\modules\esrgan_model.py:150 in do_upscale                               │             │

    │ │                                                                                                  │             │

    │ │   147 │   │   if model is None:                                                                  │             │

    │ │   148 │   │   │   return img                                                                     │             │

    │ │   149 │   │   [model.to](https://oo.pe/http://model.to)(devices.device_esrgan)                                                    │             │

    │ │ ❱ 150 │   │   img = esrgan_upscale(model, img)                                                   │             │

    │ │   151 │   │   return img                                                                         │             │

    │ │   152 │                                                                                          │             │

    │ │   153 │   def load_model(self, path: str):                                                       │             │

    │ │                                                                                                  │             │

    │ │ O:\AI\SynologyDrive\repo\modules\esrgan_model.py:224 in esrgan_upscale                           │             │

    │ │                                                                                                  │             │

    │ │   221 │   │   for tiledata in row:                                                               │             │

    │ │   222 │   │   │   x, w, tile = tiledata                                                          │             │

    │ │   223 │   │   │                                                                                  │             │

    │ │ ❱ 224 │   │   │   output = upscale_without_tiling(model, tile)                                   │             │

    │ │   225 │   │   │   scale_factor = output.width // tile.width                                      │             │

    │ │   226 │   │   │                                                                                  │             │

    │ │   227 │   │   │   newrow.append([x * scale_factor, w * scale_factor, output])                    │             │

    │ │                                                                                                  │             │

    │ │ O:\AI\SynologyDrive\repo\modules\esrgan_model.py:203 in upscale_without_tiling                   │             │

    │ │                                                                                                  │             │

    │ │   200 │   img = torch.from_numpy(img).float()                                                    │             │

    │ │   201 │   img = img.unsqueeze(0).to(devices.device_esrgan)                                       │             │

    │ │   202 │   with [torch.no](https://oo.pe/http://torch.no)_grad():                                                                  │             │

    │ │ ❱ 203 │   │   output = model(img)                                                                │             │

    │ │   204 │   output = output.squeeze().float().cpu().clamp_(0, 1).numpy()                           │             │

    │ │   205 │   output = 255. * np.moveaxis(output, 0, 2)                                              │             │

    │ │   206 │   output = output.astype(np.uint8)                                                       │             │

    │ │                                                                                                  │             │

    │ │ O:\AI\SynologyDrive\repo\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl    │             │

    │ │                                                                                                  │             │

    │ │   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │             │

    │ │   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │             │

    │ │   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │             │

    │ │ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │             │

    │ │   1502 │   │   # Do not call functions when jit is used                                          │             │

    │ │   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │             │

    │ │   1504 │   │   backward_pre_hooks = []                                                           │             │

    │ │                                                                                                  │             │

    │ │ O:\AI\SynologyDrive\repo\modules\esrgan_model_arch.py:61 in forward                              │             │

    │ │                                                                                                  │             │

    │ │    58 │   │   else:                                                                              │             │

    │ │    59 │   │   │   feat = x                                                                       │             │

    │ │    60 │   │                                                                                      │             │

    │ │ ❱  61 │   │   return self.model(feat)                                                            │             │

    │ │    62                                                                                            │             │

    │ │    63                                                                                            │             │

    │ │    64 class RRDB(nn.Module):                                                                     │             │

    │ │                                                                                                  │             │

    │ │ O:\AI\SynologyDrive\repo\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl    │             │

    │ │                                                                                                  │             │

    │ │   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │             │

    │ │   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │             │

    │ │   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │             │

    │ │ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │             │

    │ │   1502 │   │   # Do not call functions when jit is used                                          │             │

    │ │   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │             │

    │ │   1504 │   │   backward_pre_hooks = []                                                           │             │

    │ │                                                                                                  │             │

    │ │ O:\AI\SynologyDrive\repo\venv\lib\site-packages\torch\nn\modules\container.py:217 in forward     │             │

    │ │                                                                                                  │             │

    │ │   214 │   # with Any as TorchScript expects a more precise type                                  │             │

    │ │   215 │   def forward(self, input):                                                              │             │

    │ │   216 │   │   for module in self:                                                                │             │

    │ │ ❱ 217 │   │   │   input = module(input)                                                          │             │

    │ │   218 │   │   return input                                                                       │             │

    │ │   219 │                                                                                          │             │

    │ │   220 │   def append(self, module: Module) -> 'Sequential':                                      │             │

    │ │                                                                                                  │             │

    │ │ O:\AI\SynologyDrive\repo\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl    │             │

    │ │                                                                                                  │             │

    │ │   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │             │

    │ │   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │             │

    │ │   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │             │

    │ │ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │             │

    │ │   1502 │   │   # Do not call functions when jit is used                                          │             │

    │ │   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │             │

    │ │   1504 │   │   backward_pre_hooks = []                                                           │             │

    │ │                                                                                                  │             │

    │ │ O:\AI\SynologyDrive\repo\extensions-builtin\Lora\lora.py:415 in lora_Conv2d_forward              │             │

    │ │                                                                                                  │             │

    │ │   412 │                                                                                          │             │

    │ │   413 │   lora_apply_weights(self)                                                               │             │

    │ │   414 │                                                                                          │             │

    │ │ ❱ 415 │   return torch.nn.Conv2d_forward_before_lora(self, input)                                │             │

    │ │   416                                                                                            │             │

    │ │   417                                                                                            │             │

    │ │   418 def lora_Conv2d_load_state_dict(self, *args, **kwargs):                                    │             │

    │ │                                                                                                  │             │

    │ │ O:\AI\SynologyDrive\repo\extensions\a1111-sd-webui-lycoris\lycoris.py:753 in lyco_Conv2d_forward │             │

    │ │                                                                                                  │             │

    │ │   750 def lyco_Conv2d_forward(self, input):                                                      │             │

    │ │   751 │   lyco_apply_weights(self)                                                               │             │

    │ │   752 │                                                                                          │             │

    │ │ ❱ 753 │   return torch.nn.Conv2d_forward_before_lyco(self, input)                                │             │

    │ │   754                                                                                            │             │

    │ │   755                                                                                            │             │

    │ │   756 def lyco_Conv2d_load_state_dict(self, *args, **kwargs):                                    │             │

    │ │                                                                                                  │             │

    │ │ O:\AI\SynologyDrive\repo\venv\lib\site-packages\torch\nn\modules\conv.py:463 in forward          │             │

    │ │                                                                                                  │             │

    │ │    460 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                         │             │

    │ │    461 │                                                                                         │             │

    │ │    462 │   def forward(self, input: Tensor) -> Tensor:                                           │             │

    │ │ ❱  463 │   │   return self._conv_forward(input, self.weight, self.bias)                          │             │

    │ │    464                                                                                           │             │

    │ │    465 class Conv3d(_ConvNd):                                                                    │             │

    │ │    466 │   __doc__ = r"""Applies a 3D convolution over an input signal composed of several inpu  │             │

    │ │                                                                                                  │             │

    │ │ O:\AI\SynologyDrive\repo\venv\lib\site-packages\torch\nn\modules\conv.py:459 in _conv_forward    │             │

    │ │                                                                                                  │             │

    │ │    456 │   │   │   return F.conv2d(F.pad(input, self._reversed_padding_repeated_twice, mode=sel  │             │

    │ │    457 │   │   │   │   │   │   │   weight, bias, self.stride,                                    │             │

    │ │    458 │   │   │   │   │   │   │   _pair(0), self.dilation, self.groups)                         │             │

    │ │ ❱  459 │   │   return F.conv2d(input, weight, bias, self.stride,                                 │             │

    │ │    460 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                         │             │

    │ │    461 │                                                                                         │             │

    │ │    462 │   def forward(self, input: Tensor) -> Tensor:                                           │             │

    │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯             │

    │ RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 192, 192] to have 3 channels,   │

    │ but got 4 channels instead                                                                                       │

    ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by Bing-su** [comment]
아마 업스케일러중 esrgan와 관련된 문제인것 같습니다.

**Comment by Neytiri7** [comment]
당분간  esrgan 계열 업스케일러는 사용하면 안되겠네요~ ㅠ.ㅠ
그래도 이미지는 잘 생성되긴 하더라구요~~^^

**Comment by Neytiri7** [comment]
esrgan 아닌 업스케일러가 있을까요??
 그래도 이미지는 잘 만들어지고 있는데, 사용해도 적용은 되는거겠죠??

**Comment by Bing-su** [comment]
다른 업스케일러 중 에러가 안나는걸 일단 사용해보시는게 좋겠습니다

**Comment by Neytiri7** [comment]
ScuNET 이걸로 바꿔서 써보고 있는데...
같은 오류가 나옵니다.

그런데, 동작하는 과정을 보면, 정상적으로 동작은 하고 있는듯 싶네요.
