### ISSUE TITLE
[Bug]:  AssertionError: bad sampler name: <modules.sd_samplers_kdiffusion.KDiffusionSampler object at 0x0000016397CD49A0>

### ISSUE THREAD

**Issue by ZeroCool22** [Bing-su/adetailer#217]
### Describe the bug

After updating to the last version of the DETAILER and the WEBUI i start getting this error.

**WEBUI Version:**

```
commit f865d3e11647dfd6c7b2cdf90dde24680e58acd8 (HEAD -> master, tag: v1.4.1, origin/master, origin/HEAD)
Author: AUTOMATIC1111 <16777216c@gmail.com>
Date:   Tue Jul 11 06:23:52 2023 +0300

    add changelog for 1.4.1
```

### The entire console log, including python version information, webui version, commit hash, commandline arguments and error traces.

```Shell
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.58it/s]
Total progress:  44%|████████████████████████████                                    | 140/320 [00:59<01:09,  2.58it/s]
0: 640x480 1 face, 10.0ms
Speed: 0.0ms preprocess, 10.0ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 480)
*** Error running postprocess_image: C:\Users\ZeroCool22\Desktop\Auto\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "C:\Users\ZeroCool22\Desktop\Auto\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\Users\ZeroCool22\Desktop\Auto\extensions\adetailer\adetailer\traceback.py", line 157, in wrapper
        raise error from None
    AssertionError:
    ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
    │                                                   System info                                                    │
    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃             ┃ Value                                                                                          ┃ │
    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │    Platform │ Windows-10-10.0.19045-SP0                                                                      │ │
    │ │      Python │ 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]               │ │
    │ │     Version │ v1.4.1                                                                                         │ │
    │ │      Commit │ f865d3e11647dfd6c7b2cdf90dde24680e58acd8                                                       │ │
    │ │ Commandline │ ['launch.py', '--xformers', '--api', '--vae-path',                                             │ │
    │ │             │ 'C:\\Users\\ZeroCool22\\Desktop\\Auto\\models\\Stable-diffusion\\vae-ft-mse-840000-ema-pruned… │ │
    │ └─────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘ │
    │                                                      Inputs                                                      │
    │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃                 ┃ Value                                                                                      ┃ │
    │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │          prompt │xxx                                                                    │ │
    │ │ negative_prompt │ xxxx                           │ │
    │ │          n_iter │ 16                                                                                         │ │
    │ │      batch_size │ 1                                                                                          │ │
    │ │           width │ 512                                                                                        │ │
    │ │          height │ 704                                                                                        │ │
    │ │    sampler_name │ Euler a                                                                                    │ │
    │ │       enable_hr │ False                                                                                      │ │
    │ │     hr_upscaler │ None                                                                                       │ │
    │ │      checkpoint │ paragonV10_v10VAE.safetensors [5a6045090a]                                                 │ │
    │ │             vae │ Automatic                                                                                  │ │
    │ │            unet │ Automatic                                                                                  │ │
    │ └─────────────────┴────────────────────────────────────────────────────────────────────────────────────────────┘ │
    │                 ADetailer                                                                                        │
    │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓                                                                        │
    │ ┃                     ┃ Value           ┃                                                                        │
    │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩                                                                        │
    │ │             version │ 23.7.7          │                                                                        │
    │ │            ad_model │ face_yolov8n.pt │                                                                        │
    │ │           ad_prompt │                 │                                                                        │
    │ │  ad_negative_prompt │                 │                                                                        │
    │ │ ad_controlnet_model │ None            │                                                                        │
    │ │              is_api │ False           │                                                                        │
    │ └─────────────────────┴─────────────────┘                                                                        │
    │ ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮             │
    │ │ C:\Users\ZeroCool22\Desktop\Auto\extensions\adetailer\adetailer\traceback.py:137 in wrapper      │             │
    │ │                                                                                                  │             │
    │ │   134 │   │   width = width - 4 if width > 4 else None                                           │             │
    │ │   135 │   │   console = Console(file=string, force_terminal=force_terminal, width=width)         │             │
    │ │   136 │   │   try:                                                                               │             │
    │ │ ❱ 137 │   │   │   return func(*args, **kwargs)                                                   │             │
    │ │   138 │   │   except Exception as e:                                                             │             │
    │ │   139 │   │   │   tables = [                                                                     │             │
    │ │   140 │   │   │   │   get_table(title, data)                                                     │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\ZeroCool22\Desktop\Auto\extensions\adetailer\scripts\!adetailer.py:628 in               │             │
    │ │ postprocess_image                                                                                │             │
    │ │                                                                                                  │             │
    │ │   625 │   │   │   for n, args in enumerate(arg_list):                                            │             │
    │ │   626 │   │   │   │   if args.ad_model == "None":                                                │             │
    │ │   627 │   │   │   │   │   continue                                                               │             │
    │ │ ❱ 628 │   │   │   │   is_processed |= self._postprocess_image(p, pp, args, n=n)                  │             │
    │ │   629 │   │                                                                                      │             │
    │ │   630 │   │   if is_processed:                                                                   │             │
    │ │   631 │   │   │   self.save_image(                                                               │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\ZeroCool22\Desktop\Auto\extensions\adetailer\scripts\!adetailer.py:588 in               │             │
    │ │ _postprocess_image                                                                               │             │
    │ │                                                                                                  │             │
    │ │   585 │   │   │   p2.subseed = subseed + j                                                       │             │
    │ │   586 │   │   │                                                                                  │             │
    │ │   587 │   │   │   try:                                                                           │             │
    │ │ ❱ 588 │   │   │   │   processed = process_images(p2)                                             │             │
    │ │   589 │   │   │   except NansException as e:                                                     │             │
    │ │   590 │   │   │   │   msg = f"[-] ADetailer: 'NansException' occurred with {ordinal(n + 1)} se   │             │
    │ │   591 │   │   │   │   print(msg, file=sys.stderr)                                                │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\ZeroCool22\Desktop\Auto\modules\processing.py:620 in process_images                     │             │
    │ │                                                                                                  │             │
    │ │    617 │   │                                                                                     │             │
    │ │    618 │   │   sd_models.apply_token_merging(p.sd_model, p.get_token_merging_ratio())            │             │
    │ │    619 │   │                                                                                     │             │
    │ │ ❱  620 │   │   res = process_images_inner(p)                                                     │             │
    │ │    621 │                                                                                         │             │
    │ │    622 │   finally:                                                                              │             │
    │ │    623 │   │   sd_models.apply_token_merging(p.sd_model, 0)                                      │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\ZeroCool22\Desktop\Auto\modules\processing.py:680 in process_images_inner               │             │
    │ │                                                                                                  │             │
    │ │    677 │                                                                                         │             │
    │ │    678 │   with torch.no_grad(), p.sd_model.ema_scope():                                         │             │
    │ │    679 │   │   with devices.autocast():                                                          │             │
    │ │ ❱  680 │   │   │   p.init(p.all_prompts, p.all_seeds, p.all_subseeds)                            │             │
    │ │    681 │   │   │                                                                                 │             │
    │ │    682 │   │   │   # for OSX, loading the model during sampling changes the generated picture,   │             │
    │ │    683 │   │   │   if shared.opts.live_previews_enable and opts.show_progress_type == "Approx N  │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\ZeroCool22\Desktop\Auto\modules\processing.py:1185 in init                              │             │
    │ │                                                                                                  │             │
    │ │   1182 │   │   self.image_conditioning = None                                                    │             │
    │ │   1183 │                                                                                         │             │
    │ │   1184 │   def init(self, all_prompts, all_seeds, all_subseeds):                                 │             │
    │ │ ❱ 1185 │   │   self.sampler = sd_samplers.create_sampler(self.sampler_name, self.sd_model)       │             │
    │ │   1186 │   │   crop_region = None                                                                │             │
    │ │   1187 │   │                                                                                     │             │
    │ │   1188 │   │   image_mask = self.image_mask                                                      │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\ZeroCool22\Desktop\Auto\modules\sd_samplers.py:29 in create_sampler                     │             │
    │ │                                                                                                  │             │
    │ │   26 def create_sampler(name, model):                                                            │             │
    │ │   27 │   config = find_sampler_config(name)                                                      │             │
    │ │   28 │                                                                                           │             │
    │ │ ❱ 29 │   assert config is not None, f'bad sampler name: {name}'                                  │             │
    │ │   30 │                                                                                           │             │
    │ │   31 │   sampler = config.constructor(model)                                                     │             │
    │ │   32 │   sampler.config = config                                                                 │             │
    │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯             │
    │ AssertionError: bad sampler name: <modules.sd_samplers_kdiffusion.KDiffusionSampler object at                    │
    │ 0x000001639B7F8460>
```

### List of installed extensions

![Screenshot_12](https://github.com/Bing-su/adetailer/assets/13344308/0e35751d-80e2-4012-af21-e9da694aa1c3)

**Comment by theWitchR** [comment]
@ZeroCool22 Getting the same error on LastBen's fast Stable diffusion colab notebook

**Comment by Bing-su** [comment]
Sorry about that. There was a typo.
