### ISSUE TITLE
[Bug]: Error running postprocess_image

### ISSUE THREAD

**Issue by xp70** [Bing-su/adetailer#236]
### Describe the bug

when load yolov models i get this error but mediapipe_face_full works fine

### Console logs, from start to end.

```Shell
fatal: not a git repository (or any of the parent directories): .git
venv "C:\Users\SSN\Desktop\stable-diffusion-webui-1.5.0\venv\Scripts\Python.exe"
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.5.0
Commit hash: <none>

Launching Web UI with arguments: --xformers --no-half --disable-nan-check
[-] ADetailer initialized. version: 23.7.9, num models: 14
Loading weights [e4a30e4607] from C:\Users\SSN\Desktop\stable-diffusion-webui-1.5.0\models\Stable-diffusion\majicmixRealistic_v6.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 16.8s (launcher: 2.8s, import torch: 3.6s, import gradio: 1.0s, setup paths: 0.8s, other imports: 0.9s, load scripts: 6.6s, scripts before_ui_callback: 0.1s, create ui: 0.6s, gradio launch: 0.3s).
Creating model from config: C:\Users\SSN\Desktop\stable-diffusion-webui-1.5.0\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: Doggettx... done.
Model loaded in 4.9s (load weights from disk: 1.2s, create model: 0.5s, apply weights to model: 0.9s, move model to device: 2.1s, calculate empty prompt: 0.2s).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:26<00:00,  1.32s/it]
C:\Users\SSN\.cache\huggingface\hub\models--Bingsu--adetailer\snapshots\fdb6e26f5212c6a7184b359f62cc4b41fd731bb3\face_yolov8n.pt

*** Error running postprocess_image: C:\Users\SSN\Desktop\stable-diffusion-webui-1.5.0\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "C:\Users\SSN\Desktop\stable-diffusion-webui-1.5.0\modules\scripts.py", line 543, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\Users\SSN\Desktop\stable-diffusion-webui-1.5.0\extensions\adetailer\adetailer\traceback.py", line 157, in wrapper
        raise error from None
    NotImplementedError:
    ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
    │                                            System info                                                           │
    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓               │
    │ ┃             ┃ Value                                                                            ┃               │
    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩               │
    │ │    Platform │ Windows-10-10.0.19045-SP0                                                        │               │
    │ │      Python │ 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] │               │
    │ │     Version │ 1.5.0                                                                            │               │
    │ │      Commit │ <none>                                                                           │               │
    │ │ Commandline │ ['launch.py', '--xformers', '--no-half', '--disable-nan-check']                  │               │
    │ └─────────────┴──────────────────────────────────────────────────────────────────────────────────┘               │
    │                                                      Inputs                                                      │
    │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃                 ┃ Value                                                                                      ┃ │
    │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │          prompt │ zrpgstyle, masterpiece, highly detailed, grumpy angry old wizard furiously pacing, staff,  │ │
    │ │                 │ (flies:1.6), (flies everywhere:1.4), tall thin body, dirty ragged old clothes,             │ │
    │ │                 │ (unwashed:1.6) face hands, long messy unwashed unkempt grey hair, long robes, torn         │ │
    │ │                 │ clothes, holes in clothes, (pointy hat:1.2), long grey beard, (very wrinkled face:1.0),    │ │
    │ │                 │ flies in background                                                                        │ │
    │ │ negative_prompt │ (low quality, bad quality, worst quality:1.4), (text, writing, words, signature,           │ │
    │ │                 │ watermark, logo:1.4), (badhandv4:1.0), six fingers, four fingers, deformed, malformed,     │ │
    │ │                 │ mutated, contorted, extra limbs, extra legs, extra arms, large flies, big flies, wings on  │ │
    │ │                 │ back                                                                                       │ │
    │ │          n_iter │ 1                                                                                          │ │
    │ │      batch_size │ 1                                                                                          │ │
    │ │           width │ 512                                                                                        │ │
    │ │          height │ 512                                                                                        │ │
    │ │    sampler_name │ DPM++ 2M SDE Karras                                                                        │ │
    │ │       enable_hr │ False                                                                                      │ │
    │ │     hr_upscaler │ Latent                                                                                     │ │
    │ │      checkpoint │ majicmixRealistic_v6.safetensors                                                           │ │
    │ │             vae │ Automatic                                                                                  │ │
    │ │            unet │ Automatic                                                                                  │ │
    │ └─────────────────┴────────────────────────────────────────────────────────────────────────────────────────────┘ │
    │                 ADetailer                                                                                        │
    │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓                                                                        │
    │ ┃                     ┃ Value           ┃                                                                        │
    │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩                                                                        │
    │ │             version │ 23.7.9          │                                                                        │
    │ │            ad_model │ face_yolov8n.pt │                                                                        │
    │ │           ad_prompt │                 │                                                                        │
    │ │  ad_negative_prompt │                 │                                                                        │
    │ │ ad_controlnet_model │ None            │                                                                        │
    │ │              is_api │ False           │                                                                        │
    │ └─────────────────────┴─────────────────┘                                                                        │
    │ ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮             │
    │ │ C:\Users\SSN\Desktop\stable-diffusion-webui-1.5.0\extensions\adetailer\adetailer\traceback.py:13 │             │
    │ │ 7 in wrapper                                                                                     │             │
    │ │                                                                                                  │             │
    │ │   134 │   │   width = width - 4 if width > 4 else None                                           │             │
    │ │   135 │   │   console = Console(file=string, force_terminal=force_terminal, width=width)         │             │
    │ │   136 │   │   try:                                                                               │             │
    │ │ ❱ 137 │   │   │   return func(*args, **kwargs)                                                   │             │
    │ │   138 │   │   except Exception as e:                                                             │             │
    │ │   139 │   │   │   tables = [                                                                     │             │
    │ │   140 │   │   │   │   get_table(title, data)                                                     │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\SSN\Desktop\stable-diffusion-webui-1.5.0\extensions\adetailer\scripts\!adetailer.py:627 │             │
    │ │ in postprocess_image                                                                             │             │
    │ │                                                                                                  │             │
    │ │   624 │   │   │   for n, args in enumerate(arg_list):                                            │             │
    │ │   625 │   │   │   │   if args.ad_model == "None":                                                │             │
    │ │   626 │   │   │   │   │   continue                                                               │             │
    │ │ ❱ 627 │   │   │   │   is_processed |= self._postprocess_image(p, pp, args, n=n)                  │             │
    │ │   628 │   │                                                                                      │             │
    │ │   629 │   │   if is_processed:                                                                   │             │
    │ │   630 │   │   │   self.save_image(                                                               │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\SSN\Desktop\stable-diffusion-webui-1.5.0\extensions\adetailer\scripts\!adetailer.py:550 │             │
    │ │ in _postprocess_image                                                                            │             │
    │ │                                                                                                  │             │
    │ │   547 │   │   │   kwargs["device"] = self.ultralytics_device                                     │             │
    │ │   548 │   │                                                                                      │             │
    │ │   549 │   │   with change_torch_load():                                                          │             │
    │ │ ❱ 550 │   │   │   pred = predictor(ad_model, pp.image, args.ad_confidence, **kwargs)             │             │
    │ │   551 │   │                                                                                      │             │
    │ │   552 │   │   masks = self.pred_preprocessing(pred, args)                                        │             │
    │ │   553                                                                                            │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\SSN\Desktop\stable-diffusion-webui-1.5.0\extensions\adetailer\adetailer\ultralytics.py: │             │
    │ │ 32 in ultralytics_predict                                                                        │             │
    │ │                                                                                                  │             │
    │ │   29 │   model_path = str(model_path)                                                            │             │
    │ │   30 │   print(str(model_path))                                                                  │             │
    │ │   31 │   model = load_yolo(model_path)                                                           │             │
    │ │ ❱ 32 │   pred = model(image, conf=confidence, device=device)                                     │             │
    │ │   33 │                                                                                           │             │
    │ │   34 │   bboxes = pred[0].boxes.xyxy.cpu().numpy()                                               │             │
    │ │   35 │   if bboxes.size == 0:                                                                    │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\SSN\Desktop\stable-diffusion-webui-1.5.0\venv\lib\site-packages\ultralytics\engine\mode │             │
    │ │ l.py:110 in __call__                                                                             │             │
    │ │                                                                                                  │             │
    │ │   107 │                                                                                          │             │
    │ │   108 │   def __call__(self, source=None, stream=False, **kwargs):                               │             │
    │ │   109 │   │   """Calls the 'predict' function with given arguments to perform object detection   │             │
    │ │ ❱ 110 │   │   return self.predict(source, stream, **kwargs)                                      │             │
    │ │   111 │                                                                                          │             │
    │ │   112 │   def __getattr__(self, attr):                                                           │             │
    │ │   113 │   │   """Raises error if object has no requested attribute."""                           │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\SSN\Desktop\stable-diffusion-webui-1.5.0\venv\lib\site-packages\torch\utils\_contextlib │             │
    │ │ .py:115 in decorate_context                                                                      │             │
    │ │                                                                                                  │             │
    │ │   112 │   @functools.wraps(func)                                                                 │             │
    │ │   113 │   def decorate_context(*args, **kwargs):                                                 │             │
    │ │   114 │   │   with ctx_factory():                                                                │             │
    │ │ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │             │
    │ │   116 │                                                                                          │             │
    │ │   117 │   return decorate_context                                                                │             │
    │ │   118                                                                                            │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\SSN\Desktop\stable-diffusion-webui-1.5.0\venv\lib\site-packages\ultralytics\engine\mode │             │
    │ │ l.py:254 in predict                                                                              │             │
    │ │                                                                                                  │             │
    │ │   251 │   │   │   self.predictor.args = get_cfg(self.predictor.args, overrides)                  │             │
    │ │   252 │   │   │   if 'project' in overrides or 'name' in overrides:                              │             │
    │ │   253 │   │   │   │   self.predictor.save_dir = self.predictor.get_save_dir()                    │             │
    │ │ ❱ 254 │   │   return self.predictor.predict_cli(source=source) if is_cli else self.predictor(s   │             │
    │ │   255 │                                                                                          │             │
    │ │   256 │   def track(self, source=None, stream=False, persist=False, **kwargs):                   │             │
    │ │   257 │   │   """                                                                                │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\SSN\Desktop\stable-diffusion-webui-1.5.0\venv\lib\site-packages\ultralytics\engine\pred │             │
    │ │ ictor.py:195 in __call__                                                                         │             │
    │ │                                                                                                  │             │
    │ │   192 │   │   if stream:                                                                         │             │
    │ │   193 │   │   │   return self.stream_inference(source, model, *args, **kwargs)                   │             │
    │ │   194 │   │   else:                                                                              │             │
    │ │ ❱ 195 │   │   │   return list(self.stream_inference(source, model, *args, **kwargs))  # merge    │             │
    │ │   196 │                                                                                          │             │
    │ │   197 │   def predict_cli(self, source=None, model=None):                                        │             │
    │ │   198 │   │   """Method used for CLI prediction. It uses always generator as outputs as not re   │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\SSN\Desktop\stable-diffusion-webui-1.5.0\venv\lib\site-packages\torch\utils\_contextlib │             │
    │ │ .py:35 in generator_context                                                                      │             │
    │ │                                                                                                  │             │
    │ │    32 │   │   try:                                                                               │             │
    │ │    33 │   │   │   # Issuing `None` to a generator fires it up                                    │             │
    │ │    34 │   │   │   with ctx_factory():                                                            │             │
    │ │ ❱  35 │   │   │   │   response = gen.send(None)                                                  │             │
    │ │    36 │   │   │                                                                                  │             │
    │ │    37 │   │   │   while True:                                                                    │             │
    │ │    38 │   │   │   │   try:                                                                       │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\SSN\Desktop\stable-diffusion-webui-1.5.0\venv\lib\site-packages\ultralytics\engine\pred │             │
    │ │ ictor.py:255 in stream_inference                                                                 │             │
    │ │                                                                                                  │             │
    │ │   252 │   │   │                                                                                  │             │
    │ │   253 │   │   │   # Postprocess                                                                  │             │
    │ │   254 │   │   │   with profilers[2]:                                                             │             │
    │ │ ❱ 255 │   │   │   │   self.results = self.postprocess(preds, im, im0s)                           │             │
    │ │   256 │   │   │   self.run_callbacks('on_predict_postprocess_end')                               │             │
    │ │   257 │   │   │                                                                                  │             │
    │ │   258 │   │   │   # Visualize, save, write results                                               │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\SSN\Desktop\stable-diffusion-webui-1.5.0\venv\lib\site-packages\ultralytics\models\yolo │             │
    │ │ \detect\predict.py:14 in postprocess                                                             │             │
    │ │                                                                                                  │             │
    │ │   11 │                                                                                           │             │
    │ │   12 │   def postprocess(self, preds, img, orig_imgs):                                           │             │
    │ │   13 │   │   """Postprocesses predictions and returns a list of Results objects."""              │             │
    │ │ ❱ 14 │   │   preds = ops.non_max_suppression(preds,                                              │             │
    │ │   15 │   │   │   │   │   │   │   │   │   │   self.args.conf,                                     │             │
    │ │   16 │   │   │   │   │   │   │   │   │   │   self.args.iou,                                      │             │
    │ │   17 │   │   │   │   │   │   │   │   │   │   agnostic=self.args.agnostic_nms,                    │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\SSN\Desktop\stable-diffusion-webui-1.5.0\venv\lib\site-packages\ultralytics\utils\ops.p │             │
    │ │ y:261 in non_max_suppression                                                                     │             │
    │ │                                                                                                  │             │
    │ │   258 │   │   # Batched NMS                                                                      │             │
    │ │   259 │   │   c = x[:, 5:6] * (0 if agnostic else max_wh)  # classes                             │             │
    │ │   260 │   │   boxes, scores = x[:, :4] + c, x[:, 4]  # boxes (offset by class), scores           │             │
    │ │ ❱ 261 │   │   i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS                           │             │
    │ │   262 │   │   i = i[:max_det]  # limit detections                                                │             │
    │ │   263 │   │   if merge and (1 < n < 3E3):  # Merge NMS (boxes merged using weighted mean)        │             │
    │ │   264 │   │   │   # Update boxes as boxes(i,4) = weights(i,n) * boxes(n,4)                       │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\SSN\Desktop\stable-diffusion-webui-1.5.0\venv\lib\site-packages\torchvision\ops\boxes.p │             │
    │ │ y:41 in nms                                                                                      │             │
    │ │                                                                                                  │             │
    │ │    38 │   if not torch.jit.is_scripting() and not torch.jit.is_tracing():                        │             │
    │ │    39 │   │   _log_api_usage_once(nms)                                                           │             │
    │ │    40 │   _assert_has_ops()                                                                      │             │
    │ │ ❱  41 │   return torch.ops.torchvision.nms(boxes, scores, iou_threshold)                         │             │
    │ │    42                                                                                            │             │
    │ │    43                                                                                            │             │
    │ │    44 def batched_nms(                                                                           │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\SSN\Desktop\stable-diffusion-webui-1.5.0\venv\lib\site-packages\torch\_ops.py:502 in    │             │
    │ │ __call__                                                                                         │             │
    │ │                                                                                                  │             │
    │ │   499 │   │   # is still callable from JIT                                                       │             │
    │ │   500 │   │   # We save the function ptr as the `op` attribute on                                │             │
    │ │   501 │   │   # OpOverloadPacket to access it here.                                              │             │
    │ │ ❱ 502 │   │   return self._op(*args, **kwargs or {})                                             │             │
    │ │   503 │                                                                                          │             │
    │ │   504 │   # TODO: use this to make a __dir__                                                     │             │
    │ │   505 │   def overloads(self):                                                                   │             │
    │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯             │
    │ NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be      │
    │ because the operator doesn't exist for this backend, or was omitted during the selective/custom build process    │
    │ (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit                    │
    │ https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends:    │
    │ [CPU, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate,       │
    │ Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS,       │
    │ AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched,       │
    │ FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode,   │
    │ PythonDispatcher].                                                                                               │
    │                                                                                                                  │
    │ CPU: registered at C:\Users\circleci\project\torchvision\csrc\ops\cpu\nms_kernel.cpp:112 [kernel]                │
    │ QuantizedCPU: registered at C:\Users\circleci\project\torchvision\csrc\ops\quantized\cpu\qnms_kernel.cpp:124     │
    │ [kernel]                                                                                                         │
    │ BackendSelect: fallthrough registered at ..\aten\src\ATen\core\BackendSelectFallbackKernel.cpp:3 [backend        │
    │ fallback]                                                                                                        │
    │ Python: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:144 [backend fallback]                      │
    │ FuncTorchDynamicLayerBackMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:491 [backend fallback]  │
    │ Functionalize: registered at ..\aten\src\ATen\FunctionalizeFallbackKernel.cpp:280 [backend fallback]             │
    │ Named: registered at ..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]                           │
    │ Conjugate: registered at ..\aten\src\ATen\ConjugateFallback.cpp:17 [backend fallback]                            │
    │ Negative: registered at ..\aten\src\ATen\native\NegateFallback.cpp:19 [backend fallback]                         │
    │ ZeroTensor: registered at ..\aten\src\ATen\ZeroTensorFallback.cpp:86 [backend fallback]                          │
    │ ADInplaceOrView: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:63 [backend          │
    │ fallback]                                                                                                        │
    │ AutogradOther: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:30 [backend fallback]  │
    │ AutogradCPU: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:34 [backend fallback]    │
    │ AutogradCUDA: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:42 [backend fallback]   │
    │ AutogradXLA: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:46 [backend fallback]    │
    │ AutogradMPS: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:54 [backend fallback]    │
    │ AutogradXPU: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:38 [backend fallback]    │
    │ AutogradHPU: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:67 [backend fallback]    │
    │ AutogradLazy: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:50 [backend fallback]   │
    │ AutogradMeta: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:58 [backend fallback]   │
    │ Tracer: registered at ..\torch\csrc\autograd\TraceTypeManual.cpp:294 [backend fallback]                          │
    │ AutocastCPU: fallthrough registered at ..\aten\src\ATen\autocast_mode.cpp:487 [backend fallback]                 │
    │ AutocastCUDA: fallthrough registered at ..\aten\src\ATen\autocast_mode.cpp:354 [backend fallback]                │
    │ FuncTorchBatched: registered at ..\aten\src\ATen\functorch\LegacyBatchingRegistrations.cpp:815 [backend          │
    │ fallback]                                                                                                        │
    │ FuncTorchVmapMode: fallthrough registered at ..\aten\src\ATen\functorch\VmapModeRegistrations.cpp:28 [backend    │
    │ fallback]                                                                                                        │
    │ Batched: registered at ..\aten\src\ATen\LegacyBatchingRegistrations.cpp:1073 [backend fallback]                  │
    │ VmapMode: fallthrough registered at ..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]             │
    │ FuncTorchGradWrapper: registered at ..\aten\src\ATen\functorch\TensorWrapper.cpp:210 [backend fallback]          │
    │ PythonTLSSnapshot: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:152 [backend fallback]           │
    │ FuncTorchDynamicLayerFrontMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:487 [backend fallback] │
    │ PythonDispatcher: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:148 [backend fallback]            │
    │                                                                                                                  │
    ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:27<00:00,  1.39s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:27<00:00,  1.30s/it]
```

**Comment by Bing-su** [comment]
https://discuss.pytorch.org/t/notimplementederror-could-not-run-torchvision-nms-with-arguments-from-the-cuda-backend-this-could-be-because-the-operator-doesnt-exist-for-this-backend/132352
torchvision 설치에 문제가 있는것 같으니 재설치를 해보시는게 좋겠습니다.
