### ISSUE TITLE
Error when trying to load Adetailer

### ISSUE THREAD

**Issue by elreymu** [Bing-su/adetailer#248]
### Describe the bug

I am getting this error when Automatic1111 is trying to load the extension

### Console logs, from start to end.

```Shell
Already up to date.
venv "C:\Diffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.5.1
Commit hash: 68f336bd994bed5442ad95bad6b6ad5564a5409a

Launching Web UI with arguments: --autolaunch --gradio-img2img-tool color-sketch --precision autocast
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
*** Error loading script: !adetailer.py
    Traceback (most recent call last):
      File "C:\Diffusion\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Diffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Diffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 20, in <module>
        from adetailer import (
      File "C:\Diffusion\stable-diffusion-webui\extensions\adetailer\adetailer\__init__.py", line 4, in <module>
        from .mediapipe import mediapipe_predict
      File "C:\Diffusion\stable-diffusion-webui\extensions\adetailer\adetailer\mediapipe.py", line 5, in <module>
        import mediapipe as mp
      File "C:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\mediapipe\__init__.py", line 16, in <module>
        import mediapipe.python.solutions as solutions
      File "C:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\mediapipe\python\solutions\__init__.py", line 17, in <module>
        import mediapipe.python.solutions.drawing_styles
      File "C:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\mediapipe\python\solutions\drawing_styles.py", line 20, in <module>
        from mediapipe.python.solutions.drawing_utils import DrawingSpec
      File "C:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\mediapipe\python\solutions\drawing_utils.py", line 24, in <module>
        from mediapipe.framework.formats import detection_pb2
      File "C:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\mediapipe\framework\formats\detection_pb2.py", line 8, in <module>
        from google.protobuf.internal import builder as _builder
    ImportError: cannot import name 'builder' from 'google.protobuf.internal' (C:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\google\protobuf\internal\__init__.py)

---
Loading weights [178bb6c544] from C:\Diffusion\stable-diffusion-webui\models\Stable-diffusion\Any Novel 1.ckpt
Running on local URL:  http://127.0.0.1:7863
```

### List of installed extensions

I disabled all other extensions and i am still getting that error but here's the list anyway:

Hypernetwork-MonkeyPatch-Extension
a1111-sd-webui-lycoris
a1111-sd-webui-tagcomplete
adetailer
multidiffusion-upscaler-for-automatic1111
novelai-2-local-prompt
sd-dynamic-prompts
sd-webui-additional-networks
sd-webui-controlnet
sd-webui-multiple-hypernetworks
sd-webui-segment-anything
stable-diffusion-webui-composable-lora
stable-diffusion-webui-randomize
stable-diffusion-webui-two-shot
stable-diffusion-webui-wd14-tagger
stable-diffusion-webui-wildcards
ultimate-upscale-for-automatic1111
LDSR
Lora
ScuNET
SwinIR
canvas-zoom-and-pan
extra-options-section
mobile
prompt-bracket-checker

**Comment by Bing-su** [comment]
제보에 감사드립니다. mediapipe를 사용하려면 protobuf의 버전은 `3.20.*`대로 맞춰져있어야 하나, 어떤 알수 없는 이유에 의해 `4.*`버전이 설치되는 경우가 있습니다.
직접 가상환경에서 `pip install "protobuf>=3.20,<4"`를 실행해서 protobuf의 버전을 맞춰본 뒤, 재실행해보세요.

**Comment by elreymu** [comment]
I have protobuf version 3.20
But i am still getting that same error.

**Comment by Danamir** [comment]
I had the same problem, but the proposed solution is working for me. It just displayed this error on install, but otherwise all seems to be working fine : 

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tb-nightly 2.11.0a20220914 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 which is incompatible.
tensorflow-intel 2.11.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 which is incompatible.
```

**Comment by elreymu** [comment]
I tried the solution, i now have version 3.20.3 
and i am getting the same error:

`*** Error loading script: !adetailer.py
    Traceback (most recent call last):
      File "C:\Diffusion\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Diffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Diffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 20, in <module>
        from adetailer import (
      File "C:\Diffusion\stable-diffusion-webui\extensions\adetailer\adetailer\__init__.py", line 4, in <module>
        from .mediapipe import mediapipe_predict
      File "C:\Diffusion\stable-diffusion-webui\extensions\adetailer\adetailer\mediapipe.py", line 5, in <module>
        import mediapipe as mp
      File "C:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\mediapipe\__init__.py", line 16, in <module>
        import mediapipe.python.solutions as solutions
      File "C:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\mediapipe\python\solutions\__init__.py", line 17, in <module>
        import mediapipe.python.solutions.drawing_styles
      File "C:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\mediapipe\python\solutions\drawing_styles.py", line 20, in <module>
        from mediapipe.python.solutions.drawing_utils import DrawingSpec
      File "C:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\mediapipe\python\solutions\drawing_utils.py", line 24, in <module>
        from mediapipe.framework.formats import detection_pb2
      File "C:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\mediapipe\framework\formats\detection_pb2.py", line 8, in <module>
        from google.protobuf.internal import builder as _builder
    ImportError: cannot import name 'builder' from 'google.protobuf.internal' (C:\Diffusion\stable-diffusion-webui\venv\lib\site-packages\google\protobuf\internal\__init__.py)
`

**Comment by ArtificialOtaku** [comment]
Same error here.

**Comment by elreymu** [comment]
I managed to fix it.
When installing protobuf in my venv, the builder.py file is missing, for some reason the file builder.py is not included in the package.
So what i did is to go to the protobuf repository, looked up builder.pý
download the file and pasted it into this directory in stable diffussion :
\venv\Lib\site-packages\google\protobuf\internal

Ran stable diffussion and it's working now.

**Comment by dwu11** [comment]
@elreymu `Repeated field containers are now generic in field types and could be used
in type annotations.
*[Breaking change] Protobuf python generated codes are simplified. Descriptors and message
classes' definitions are now dynamic created in internal/builder.py.
Insertion Points for messages classes are discarded.`

From the 3.2 patch notes: https://github.com/protocolbuffers/protobuf/releases/tag/v3.20.0

Automatic1111 stable-diffusion-webui uses protobuf 3.19.6 which doesn't have builder.py. This is a compatibility issue involving tensorflow dependencies.

**Comment by ArtificialOtaku** [comment]
> I managed to fix it. When installing protobuf in my venv, the builder.py file is missing, for some reason the file builder.py is not included in the package. So what i did is to go to the protobuf repository, looked up builder.pý download the file and pasted it into this directory in stable diffussion : \venv\Lib\site-packages\google\protobuf\internal
> 
> Ran stable diffussion and it's working now.

That was quite the journey, but your solution works, thanks!
