### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'ultralytics'

### ISSUE THREAD

**Issue by jjangga0214** [Bing-su/adetailer#252]
### Describe the bug

When installing the extension, an error happens.

### Console logs, from start to end.

```bash
2023-07-31T06:21:50.107153369Z *** Error loading script: !adetailer.py
2023-07-31T06:21:50.107651737Z     Traceback (most recent call last):
2023-07-31T06:21:50.107664327Z       File "/workspace/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
2023-07-31T06:21:50.107666757Z         script_module = script_loading.load_module(scriptfile.path)
2023-07-31T06:21:50.107669097Z       File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
2023-07-31T06:21:50.107671127Z         module_spec.loader.exec_module(module)
2023-07-31T06:21:50.107672997Z       File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-07-31T06:21:50.107674867Z       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-07-31T06:21:50.107676527Z       File "/workspace/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 20, in <module>
2023-07-31T06:21:50.107678347Z         from adetailer import (
2023-07-31T06:21:50.107680747Z       File "/workspace/stable-diffusion-webui/extensions/adetailer/adetailer/__init__.py", line 5, in <module>
2023-07-31T06:21:50.107688297Z         from .ultralytics import ultralytics_predict
2023-07-31T06:21:50.107690727Z       File "/workspace/stable-diffusion-webui/extensions/adetailer/adetailer/ultralytics.py", line 8, in <module>
2023-07-31T06:21:50.107692597Z         from ultralytics import YOLO
2023-07-31T06:21:50.107693977Z     ModuleNotFoundError: No module named 'ultralytics'
```

**Comment by Bing-su** [comment]
see: https://github.com/Bing-su/adetailer/discussions/205
`--skip-install` 인자를 확인해보셔야 할 것 같습니다.

**Comment by RedOceanCC** [comment]
> see: #205
> `--skip-install` 인자를 확인해보셔야 할 것 같습니다.

Could you please advise me, I have exactly the same log, what should be done with --skip-install ?

**Comment by jjangga0214** [comment]
@RedOceanCC Extensions can optionally have install.py. Check out the official [docs](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Developing-extensions#installpy).
In case of adetailer, it installs dependencies including ultralytics.
()
https://github.com/Bing-su/adetailer/blob/f18e00b40826381352ab9d7ca75f7af85065a31b/install.py#L44-L54

install.py is automatically executed in a normal environment. 
This *may* contain arbitrary dangerous code, it's always recommended to install only trustable extensions.
`--skip-install` obviously is an option to ignore it, for safety.
Runpod template that defines a docker image for Stable Diffusion has the option.
You can either define your own custom Runpod template or manually execute the install.py.
