### ISSUE TITLE
[Bug]: Error when running adetailer with SDXL

### ISSUE THREAD

**Issue by GuruVirus** [Bing-su/adetailer#255]
### Describe the bug

Adetailer crashes immediately during inference.

### Screenshots

![image](https://github.com/Bing-su/adetailer/assets/4285187/c2294102-5a00-4939-b8fd-b456c5460702)

![image](https://github.com/Bing-su/adetailer/assets/4285187/26dc360d-d065-4d36-948a-43a58f1e0db2)

### Console logs, from start to end.

```Shell
*** Error running postprocess_image: C:\sdxl\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "C:\sdxl\modules\scripts.py", line 575, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\sdxl\extensions\adetailer\adetailer\traceback.py", line 159, in wrapper
        raise error from None
    NotImplementedError:

    │ ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮             │    │ │ C:\sdxl\extensions\adetailer\adetailer\traceback.py:139 in wrapper                 │             │    │ │                                                                                                  │             │    │ │   136 │   │   width = width - 4 if width > 4 else None                                           │             │    │ │   137 │   │   console = Console(file=string, width=width)                                        │             │    │ │   138 │   │   try:                                                                               │             │    │ │ ❱ 139 │   │   │   return func(*args, **kwargs)                                                   │             │    │ │   140 │   │   except Exception as e:                                                             │             │    │ │   141 │   │   │   tables = [                                                                     │             │    │ │   142 │   │   │   │   get_table(title, data)                                                     │             │    │ │                                                                                                  │             │    │ │ C:\sdxl\extensions\adetailer\scripts\!adetailer.py:630 in postprocess_image        │             │    │ │                                                                                                  │             │    │ │   627 │   │   │   for n, args in enumerate(arg_list):                                            │             │    │ │   628 │   │   │   │   if args.ad_model == "None":                                                │             │    │ │   629 │   │   │   │   │   continue                                                               │             │    │ │ ❱ 630 │   │   │   │   is_processed |= self._postprocess_image(p, pp, args, n=n)                  │             │    │ │   631 │   │                                                                                      │             │    │ │   632 │   │   if is_processed:                                                                   │             │    │ │   633 │   │   │   self.save_image(                                                               │             │    │ │                                                                                                  │             │    │ │ C:\sdxl\extensions\adetailer\scripts\!adetailer.py:553 in _postprocess_image       │             │    │ │                                                                                                  │             │    │ │   550 │   │   │   kwargs["device"] = self.ultralytics_device                                     │             │    │ │   551 │   │                                                                                      │             │    │ │   552 │   │   with change_torch_load():                                                          │             │    │ │ ❱ 553 │   │   │   pred = predictor(ad_model, pp.image, args.ad_confidence, **kwargs)             │             │    │ │   554 │   │                                                                                      │             │    │ │   555 │   │   masks = self.pred_preprocessing(pred, args)                                        │             │    │ │   556                                                                                            │             │    │ │                                                                                                  │             │    │ │ C:\sdxl\extensions\adetailer\adetailer\ultralytics.py:21 in ultralytics_predict    │             │    │ │                                                                                                  │             │    │ │   18 │   device: str = "",                                                                       │             │    │ │   19 ) -> PredictOutput:                                                                         │             │    │ │   20 │   model = YOLO(model_path)                                                                │             │    │ │ ❱ 21 │   pred = model(image, conf=confidence, device=device)                                     │             │    │ │   22 │                                                                                           │             │    │ │   23 │   bboxes = pred[0].boxes.xyxy.cpu().numpy()                                               │             │    │ │   24 │   if bboxes.size == 0:                                                                    │             │    │ │                                                                                                  │             │    │ │ C:\sdxl\venv\lib\site-packages\ultralytics\engine\model.py:98 in __call__          │             │    │ │                                                                                                  │             │    │ │    95 │                                                                                          │             │    │ │    96 │   def __call__(self, source=None, stream=False, **kwargs):                               │             │    │ │    97 │   │   """Calls the 'predict' function with given arguments to perform object detection   │             │    │ │ ❱  98 │   │   return self.predict(source, stream, **kwargs)                                      │             │    │ │    99 │                                                                                          │             │    │ │   100 │   @staticmethod                                                                          │             │    │ │   101 │   def is_hub_model(model):                                                               │             │    │ │                                                                                                  │             │    │ │ C:\sdxl\venv\lib\site-packages\torch\utils\_contextlib.py:115 in decorate_context  │             │    │ │                                                                                                  │             │    │ │   112 │   @functools.wraps(func)                                                                 │             │    │ │   113 │   def decorate_context(*args, **kwargs):                                                 │             │    │ │   114 │   │   with ctx_factory():                                                                │             │    │ │ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │             │    │ │   116 │                                                                                          │             │    │ │   117 │   return decorate_context                                                                │             │    │ │   118                                                                                            │             │    │ │                                                                                                  │             │    │ │ C:\sdxl\venv\lib\site-packages\ultralytics\engine\model.py:246 in predict          │             │    │ │                                                                                                  │             │    │ │   243 │   │   # Set prompts for SAM/FastSAM                                                      │             │    │ │   244 │   │   if len and hasattr(self.predictor, 'set_prompts'):                                 │             │    │ │   245 │   │   │   self.predictor.set_prompts(prompts)                                            │             │    │ │ ❱ 246 │   │   return self.predictor.predict_cli(source=source) if is_cli else self.predictor(s   │             │    │ │   247 │                                                                                          │             │    │ │   248 │   def track(self, source=None, stream=False, persist=False, **kwargs):                   │             │    │ │   249 │   │   """                                                                                │             │    │ │                                                                                                  │             │    │ │ C:\sdxl\venv\lib\site-packages\ultralytics\engine\predictor.py:197 in __call__     │             │    │ │                                                                                                  │             │    │ │   194 │   │   if stream:                                                                         │             │    │ │   195 │   │   │   return self.stream_inference(source, model, *args, **kwargs)                   │             │    │ │   196 │   │   else:                                                                              │             │    │ │ ❱ 197 │   │   │   return list(self.stream_inference(source, model, *args, **kwargs))  # merge    │             │    │ │   198 │                                                                                          │             │    │ │   199 │   def predict_cli(self, source=None, model=None):                                        │             │    │ │   200 │   │   """Method used for CLI prediction. It uses always generator as outputs as not re   │             │    │ │                                                                                                  │             │    │ │ C:\ai_sdxl_2023-07-27\venv\lib\site-packages\torch\utils\_contextlib.py:35 in generator_context  │             │    │ │                                                                                                  │             │    │ │    32 │   │   try:                                                                               │             │    │ │    33 │   │   │   # Issuing `None` to a generator fires it up                                    │             │    │ │    34 │   │   │   with ctx_factory():                                                            │             │    │ │ ❱  35 │   │   │   │   response = gen.send(None)                                                  │             │    │ │    36 │   │   │                                                                                  │             │    │ │    37 │   │   │   while True:                                                                    │             │    │ │    38 │   │   │   │   try:                                                                       │             │    │ │                                                                                                  │             │    │ │ C:\sdxl\venv\lib\site-packages\ultralytics\engine\predictor.py:257 in              │             │    │ │ stream_inference                                                                                 │             │    │ │                                                                                                  │             │    │ │   254 │   │   │                                                                                  │             │    │ │   255 │   │   │   # Postprocess                                                                  │             │    │ │   256 │   │   │   with profilers[2]:                                                             │             │    │ │ ❱ 257 │   │   │   │   self.results = self.postprocess(preds, im, im0s)                           │             │    │ │   258 │   │   │   self.run_callbacks('on_predict_postprocess_end')                               │             │    │ │   259 │   │   │                                                                                  │             │    │ │   260 │   │   │   # Visualize, save, write results                                               │             │    │ │                                                                                                  │             │    │ │ C:\sdxl\venv\lib\site-packages\ultralytics\models\yolo\detect\predict.py:14 in     │             │    │ │ postprocess                                                                                      │             │    │ │                                                                                                  │             │    │ │   11 │                                                                                           │             │    │ │   12 │   def postprocess(self, preds, img, orig_imgs):                                           │             │    │ │   13 │   │   """Postprocesses predictions and returns a list of Results objects."""              │             │    │ │ ❱ 14 │   │   preds = ops.non_max_suppression(preds,                                              │             │    │ │   15 │   │   │   │   │   │   │   │   │   │   self.args.conf,                                     │             │    │ │   16 │   │   │   │   │   │   │   │   │   │   self.args.iou,                                      │             │    │ │   17 │   │   │   │   │   │   │   │   │   │   agnostic=self.args.agnostic_nms,                    │             │    │ │                                                                                                  │             │    │ │ C:\sdxl\venv\lib\site-packages\ultralytics\utils\ops.py:261 in non_max_suppression │             │    │ │                                                                                                  │             │    │ │   258 │   │   # Batched NMS                                                                      │             │    │ │   259 │   │   c = x[:, 5:6] * (0 if agnostic else max_wh)  # classes                             │             │    │ │   260 │   │   boxes, scores = x[:, :4] + c, x[:, 4]  # boxes (offset by class), scores           │             │    │ │ ❱ 261 │   │   i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS                           │             │    │ │   262 │   │   i = i[:max_det]  # limit detections                                                │             │    │ │   263 │   │   if merge and (1 < n < 3E3):  # Merge NMS (boxes merged using weighted mean)        │             │    │ │   264 │   │   │   # Update boxes as boxes(i,4) = weights(i,n) * boxes(n,4)                       │             │    │ │                                                                                                  │             │    │ │ C:\sdxl\venv\lib\site-packages\torchvision\ops\boxes.py:41 in nms                  │             │    │ │                                                                                                  │             │    │ │    38 │   if not torch.jit.is_scripting() and not torch.jit.is_tracing():                        │             │    │ │    39 │   │   _log_api_usage_once(nms)                                                           │             │    │ │    40 │   _assert_has_ops()                                                                      │             │    │ │ ❱  41 │   return torch.ops.torchvision.nms(boxes, scores, iou_threshold)                         │             │    │ │    42                                                                                            │             │    │ │    43                                                                                            │             │    │ │    44 def batched_nms(                                                                           │             │    │ │                                                                                                  │             │    │ │ C:\ai_sdxl_2023-07-27\venv\lib\site-packages\torch\_ops.py:502 in __call__                       │             │    │ │                                                                                                  │             │    │ │   499 │   │   # is still callable from JIT                                                       │             │    │ │   500 │   │   # We save the function ptr as the `op` attribute on                                │             │    │ │   501 │   │   # OpOverloadPacket to access it here.                                              │             │    │ │ ❱ 502 │   │   return self._op(*args, **kwargs or {})                                             │             │    │ │   503 │                                                                                          │             │    │ │   504 │   # TODO: use this to make a __dir__                                                     │             │    │ │   505 │   def overloads(self):  

 NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build).
```

### List of installed extensions

![image](https://github.com/Bing-su/adetailer/assets/4285187/088d2ff7-6562-46e0-abfd-c602af7a4724)

**Comment by Bing-su** [comment]
It's not an issue with SDXL, your torchvision installation is incorrect, try reinstalling. 
https://discuss.pytorch.org/t/notimplementederror-could-not-run-torchvision-nms-with-arguments-from-the-cuda-backend-this-could-be-because-the-operator-doesnt-exist-for-this-backend/132352
