### ISSUE TITLE
[Bug]: ERROR on installation

### ISSUE THREAD

**Issue by p0mad** [Bing-su/adetailer#256]
### Describe the bug

Both installation from extension tab by search or manually install would fail!

### Console logs, from start to end.

```Shell
---
*** Error completing request
*** Arguments: ('', 'https://github.com/Bing-su/adetailer', '') {}
    Traceback (most recent call last):
      File "D:\q\modules\call_queue.py", line 58, in f        res = list(func(*args, **kwargs))
      File "D:\q\modules\ui_extensions.py", line 620, 
in <lambda>
        fn=modules.ui.wrap_gradio_call(lambda *args: [gr.update(), *install_extension_from_url(*args)], extra_outputs=[gr.update(), gr.update()]),
      File "D:\q\modules\ui_extensions.py", line 375, 
in install_extension_from_url
        raise err
      File "D:\q\modules\ui_extensions.py", line 367, 
in install_extension_from_url
        os.rename(tmpdir, target_dir)
    PermissionError: [WinError 5] Access is denied: 'D:\\q\\tmp\\adetailer' -> 'D:\\q\\extensions\\adetailer'
```

**Comment by p0mad** [comment]
version: [v1.5.1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/68f336bd994bed5442ad95bad6b6ad5564a5409a)  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.32.0  •  checkpoint: [4199bcdd14](https://google.com/search?q=4199bcdd147e11328d5f3560301d5a7ab4ac7eeefbf49dc3eb663cb3e772b9ac)
