### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by anaksunamoo** [Bing-su/adetailer#265]
### Describe the bug

Error when trying to load Adetailer

### Console logs, from start to end.

```Shell
Error loading script: !adetailer.py
    Traceback (most recent call last):
      File "C:\Users\Desktop\test\repo\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\Desktop\test\repo\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\Desktop\test\repo\extensions\adetailer\scripts\!adetailer.py", line 20, in <module>
        from adetailer import (
      File "C:\Users\Desktop\test\repo\extensions\adetailer\adetailer\__init__.py", line 5, in <module>
        from .ultralytics import ultralytics_predict
      File "C:\Users\Desktop\test\repo\extensions\adetailer\adetailer\ultralytics.py", line 8, in <module>
        from ultralytics import YOLO
      File "C:\Users\Desktop\test\cache\virtualenv\lib\site-packages\ultralytics\__init__.py", line 5, in <module>
        from ultralytics.hub import start
      File "C:\UsersDesktop\test\cache\virtualenv\lib\site-packages\ultralytics\hub\__init__.py", line 5, in <module>
        from ultralytics.data.utils import HUBDatasetStats
      File "C:\UsersDesktop\test\cache\virtualenv\lib\site-packages\ultralytics\data\__init__.py", line 3, in <module>
        from .base import BaseDataset
      File "C:\UsersDesktop\test\cache\virtualenv\lib\site-packages\ultralytics\data\base.py", line 18, in <module>        from ultralytics.utils import DEFAULT_CFG, LOCAL_RANK, LOGGER, NUM_THREADS, TQDM_BAR_FORMAT
      File "C:\Users\Desktop\test\cache\virtualenv\lib\site-packages\ultralytics\utils\__init__.py", line 840, in <module>
        SETTINGS = SettingsManager()  # initialize settings
      File "C:\UsersDesktop\test\cache\virtualenv\lib\site-packages\ultralytics\utils\__init__.py", line 780, in __init__
        self.load()
      File "C:\Users\Desktop\test\cache\virtualenv\lib\site-packages\ultralytics\utils\__init__.py", line 794, in load
        self.update(yaml_load(self.file))
      File "C:\Users\Desktop\test\cache\virtualenv\lib\site-packages\ultralytics\utils\__init__.py", line 802, in update
        new = dict(*args, **kwargs)
    TypeError: 'NoneType' object is not iterable
```

### List of installed extensions

a1111-sd-webui-lycoris
a1111-sd-webui-tagcomplete
adetailer
multidiffusion-upscaler-for-automatic1111
novelai-2-local-prompt
sd-dynamic-prompts
sd-webui-additional-networks
sd-webui-controlnet
sd-webui-multiple-hypernetworks
sd-webui-segment-anything
stable-diffusion-webui-composable-lora
stable-diffusion-webui-randomize
stable-diffusion-webui-two-shot
stable-diffusion-webui-wd14-tagger
stable-diffusion-webui-wildcards
ultimate-upscale-for-automatic1111
LDSR
Lora
ScuNET
SwinIR
canvas-zoo
ultralytics

**Comment by Bing-su** [comment]
ultralytics 8.0.147버전의 버그이니 ultralytics를 8.0.148이상으로 업데이트하고 다시 시도해보세요
https://github.com/ultralytics/ultralytics/issues/4163
