### ISSUE TITLE
[Bug]: Extension doesn't load if stable-diffusion-webui-wd14-tagger also installed

### ISSUE THREAD

**Issue by xahldera** [Bing-su/adetailer#269]
### Describe the bug

The extension doesn't load. Nothing appears in webui when this extension and [stable-diffusion-webui-wd14-tagger](https://github.com/picobyte/stable-diffusion-webui-wd14-tagger) is installed and active at the same time. It works when stable-diffusion-webui-wd14-tagger is disabled

### Console logs, from start to end.

```Shell
Already up to date.
venv "[REDACTED]\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.5.1
Commit hash: 68f336bd994bed5442ad95bad6b6ad5564a5409a
Collecting protobuf<=3.9999,>=3.20
  Using cached protobuf-3.20.3-cp310-cp310-win_amd64.whl (904 kB)
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.19.6
    Uninstalling protobuf-3.19.6:
      Successfully uninstalled protobuf-3.19.6
Successfully installed protobuf-3.20.3





loading WD14-tagger reqs from [REDACTED]\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt
Checking WD14-tagger requirements.

Launching Web UI with arguments: --precision autocast --no-half-vae --xformers
[REDACTED]\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py:116: PkgResourcesDeprecationWarning: otobuf is an invalid version and will not be supported in a future release
  warnings.warn(
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
*** Error loading script: !adetailer.py
    Traceback (most recent call last):
      File "[REDACTED]\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "[REDACTED]\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "[REDACTED]\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 20, in <module>
        from adetailer import (
      File "[REDACTED]\stable-diffusion-webui\extensions\adetailer\adetailer\__init__.py", line 4, in <module>
        from .mediapipe import mediapipe_predict
      File "[REDACTED]\stable-diffusion-webui\extensions\adetailer\adetailer\mediapipe.py", line 5, in <module>
        import mediapipe as mp
      File "[REDACTED]\stable-diffusion-webui\venv\lib\site-packages\mediapipe\__init__.py", line 16, in <module>
        import mediapipe.python.solutions as solutions
      File "[REDACTED]\stable-diffusion-webui\venv\lib\site-packages\mediapipe\python\solutions\__init__.py", line 17, in <module>
        import mediapipe.python.solutions.drawing_styles
      File "[REDACTED]\stable-diffusion-webui\venv\lib\site-packages\mediapipe\python\solutions\drawing_styles.py", line 20, in <module>
        from mediapipe.python.solutions.drawing_utils import DrawingSpec
      File "[REDACTED]\stable-diffusion-webui\venv\lib\site-packages\mediapipe\python\solutions\drawing_utils.py", line 24, in <module>
        from mediapipe.framework.formats import detection_pb2
      File "[REDACTED]\stable-diffusion-webui\venv\lib\site-packages\mediapipe\framework\formats\detection_pb2.py", line 8, in <module>
        from google.protobuf.internal import builder as _builder
    ImportError: cannot import name 'builder' from 'google.protobuf.internal' ([REDACTED]\stable-diffusion-webui\venv\lib\site-packages\google\protobuf\internal\__init__.py)

---
2023-08-12 00:17:01,529 - ControlNet - INFO - ControlNet v1.1.237
ControlNet preprocessor location: [REDACTED]\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-08-12 00:17:01,820 - ControlNet - INFO - ControlNet v1.1.237
== WD14 tagger /gpu:0, uname_result(system='Windows', node='REDACTED', release='10', version='10.0.19045', machine='AMD64') ==
Loading weights [5778b6ceb9] from [REDACTED]\stable-diffusion-webui\models\Stable-diffusion\[REDACTED]
Creating model from config: [REDACTED]\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: [REDACTED]\stable-diffusion-webui\models\VAE\orangemix.vae.pt
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 59.0s (launcher: 26.6s, import torch: 10.4s, import gradio: 1.6s, setup paths: 1.1s, other imports: 1.4s, setup codeformer: 0.1s, list SD models: 1.2s, load scripts: 6.8s, create ui: 8.9s, gradio launch: 0.7s, app_started_callback: 0.1s).
Applying attention optimization: xformers... done.
Model loaded in 11.1s (load weights from disk: 1.8s, create model: 1.8s, apply weights to model: 1.1s, apply half(): 3.1s, load VAE: 2.2s, move model to device: 0.9s, calculate empty prompt: 0.1s).
```

### List of installed extensions

a1111-sd-webui-tagcomplete
adetailer
sd-dynamic-thresholding
sd-extension-system-info
sd-webui-check-tensors
sd-webui-controlnet
sd-webui-cutoff
sd-webui-supermerger
sdweb-merge-block-weighted-gui
stable-diffusion-webui-anti-burn
stable-diffusion-webui-images-browser
stable-diffusion-webui-model-toolkit
stable-diffusion-webui-wd14-tagger
stable-diffusion-webui-two-shot

**Comment by Bing-su** [comment]
같은 protobuf 패키지를 사용하는 tensorflow와 호환이 안좋습니다. 아마 `stable-diffusion-webui-wd14-tagger`를 먼저 설치하고 `adetailer`를 나중에 설치하면 동작할겁니다.

**Comment by xahldera** [comment]
I'm sorry. I don't understand. Machine translator suggests you are saying I should reinstall tagger first then adetailer?
죄송하지만 한국어를 못 알아듣겠어요. 번역 서비스를 사용하여 답장을 읽고 있습니다. "stable-diffusion-webui-wd14-tagger"를 먼저 재설치한 후 "adetailer" 를 재설치하라는 건가요?
