### ISSUE TITLE
[Bug]: Error calling: /content/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py/ui

### ISSUE THREAD

**Issue by michgscod** [Bing-su/adetailer#304]
### Describe the bug

I tried to load the ADetailer extension with this Google Colab Notebook: https://colab.research.google.com/github/sagiodev/stablediffusion_webui/blob/master/StableDiffusionUI_ngrok_sagiodev.ipynb and encounter the following issue where ADetailer won't work on the generation.

### Console logs, from start to end.

```Shell
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Version: v1.5.1
Commit hash: 68f336bd994bed5442ad95bad6b6ad5564a5409a

Launching Web UI with arguments: --gradio-img2img-tool color-sketch --enable-insecure-extension-access --gradio-queue --xformers --ngrok 2SdrzVk2PEMUY10EPoPxjOYuZ48_5sAfkcf86s3BwMrAB1C5y --gradio-auth a:a
2023-08-31 15:17:25.610456: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-31 15:17:26.640083: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
ngrok authtoken detected, trying to connect...
ngrok connected to localhost:7860! URL: https://[redacted].ngrok-free.app
You can use this link after the launch is complete.
Downloading face_yolov8n.pt: 100% 6.21M/6.21M [00:00<00:00, 157MB/s]
Downloading face_yolov8s.pt: 100% 22.5M/22.5M [00:00<00:00, 310MB/s]
Downloading hand_yolov8n.pt: 100% 6.22M/6.22M [00:00<00:00, 334MB/s]
Downloading person_yolov8n-seg.pt: 100% 6.75M/6.75M [00:00<00:00, 370MB/s]
Downloading person_yolov8s-seg.pt: 100% 23.8M/23.8M [00:00<00:00, 323MB/s]
[-] ADetailer initialized. version: 23.9.0, num models: 9
Loading weights [fc2511737a] from /content/stable-diffusion-webui/models/Stable-diffusion/chilloutmix_NiPrunedFp32Fix.safetensors
*** Error calling: /content/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py/ui
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/scripts.py", line 339, in wrap_call
        return func(*args, **kwargs)
      File "/content/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 131, in ui
        components, infotext_fields = adui(num_models, is_img2img, webui_info)
      File "/content/stable-diffusion-webui/extensions/adetailer/adetailer/ui.py", line 104, in adui
        state, infofields = one_ui_group(
      File "/content/stable-diffusion-webui/extensions/adetailer/adetailer/ui.py", line 178, in one_ui_group
        inpainting(w, n, is_img2img, webui_info)
      File "/content/stable-diffusion-webui/extensions/adetailer/adetailer/ui.py", line 431, in inpainting
        *webui_info.checkpoints_list(use_short=True),
    TypeError: checkpoint_tiles() got an unexpected keyword argument 'use_short'

---
*** Error calling: /content/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py/ui
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/scripts.py", line 339, in wrap_call
        return func(*args, **kwargs)
      File "/content/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 131, in ui
        components, infotext_fields = adui(num_models, is_img2img, webui_info)
      File "/content/stable-diffusion-webui/extensions/adetailer/adetailer/ui.py", line 104, in adui
        state, infofields = one_ui_group(
      File "/content/stable-diffusion-webui/extensions/adetailer/adetailer/ui.py", line 178, in one_ui_group
        inpainting(w, n, is_img2img, webui_info)
      File "/content/stable-diffusion-webui/extensions/adetailer/adetailer/ui.py", line 431, in inpainting
        *webui_info.checkpoints_list(use_short=True),
    TypeError: checkpoint_tiles() got an unexpected keyword argument 'use_short'

---
Running on local URL:  http://[redacted]

To create a public link, set `share=True` in `launch()`.
Startup time: 16.6s (launcher: 2.0s, import torch: 5.8s, import gradio: 0.7s, setup paths: 1.0s, other imports: 0.8s, list SD models: 2.6s, load scripts: 2.3s, create ui: 1.0s, gradio launch: 0.2s).
Creating model from config: /content/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: /content/stable-diffusion-webui/models/VAE/vae-ft-ema-560000-ema-pruned.ckpt
Applying attention optimization: xformers... done.
Model loaded in 7.4s (load weights from disk: 1.3s, create model: 1.9s, apply weights to model: 3.3s, load VAE: 0.5s, load textual inversion embeddings: 0.1s, calculate empty prompt: 0.2s).

[-] ADetailer: Invalid arguments passed to ADetailer.
    input: ()
    ADetailer disabled.

  0% 0/20 [00:00<?, ?it/s]
  5% 1/20 [00:03<00:58,  3.06s/it]
 15% 3/20 [00:03<00:13,  1.26it/s]
 25% 5/20 [00:03<00:05,  2.53it/s]
 30% 6/20 [00:03<00:04,  3.22it/s]
 35% 7/20 [00:03<00:03,  3.89it/s]
 40% 8/20 [00:04<00:02,  4.45it/s]
 45% 9/20 [00:04<00:02,  5.00it/s]
 50% 10/20 [00:04<00:01,  5.45it/s]
 55% 11/20 [00:04<00:01,  5.82it/s]
 60% 12/20 [00:04<00:01,  6.13it/s]
 65% 13/20 [00:04<00:01,  6.35it/s]
 70% 14/20 [00:04<00:00,  6.48it/s]
 75% 15/20 [00:05<00:00,  6.59it/s]
 80% 16/20 [00:05<00:00,  6.64it/s]
 85% 17/20 [00:05<00:00,  6.57it/s]
 90% 18/20 [00:05<00:00,  6.59it/s]
 95% 19/20 [00:05<00:00,  6.67it/s]
100% 20/20 [00:05<00:00,  3.42it/s]

[-] ADetailer: Invalid arguments passed to ADetailer.
    input: ()
    ADetailer disabled.
```

### List of installed extensions

I tried both installing my usual extensions list and installing only the ADetailer, but the errors are the same.

**Comment by CookieMeowie** [comment]
New build seems to have entirely broken it on my end as well. Using the previous build worked fine as a temporary solution. (v23.8.1)

**Comment by jasoncow007** [comment]
confirmed，me too, and one more issue——set more than 2 module（3）， only show 1

**Comment by Neverdusk** [comment]
Want to confirm that I have this issue as well. I can launch the webui, but ADetailer disables itself from this error.

**Comment by naduarte2** [comment]
Same issue of [-] ADetailer: Invalid arguments passed to ADetailer. The auto-update make my !adetailer go to v23.9.0 and SD WebUI goes to v1.6.0, and together really sucks compared to v23.8.1/UI v.1.5.2. 

Just manually installing v23.8.1 from https://github.com/Bing-su/adetailer/archive/refs/tags/v23.8.1.zip solved the problem for me. Also unchecking all the auto-updates (WebUI and extensiones) until stability reach, the new WebUI also gives me a lot of problems with Deforum and many other extensions.

**Comment by naduarte2** [comment]
```python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Version: v1.5.1
Commit hash: 68f336bd994bed5442ad95bad6b6ad5564a5409a

Launching Web UI with arguments: --gradio-img2img-tool color-sketch --enable-insecure-extension-access --gradio-queue --xformers --ngrok 2SdrzVk2PEMUY10EPoPxjOYuZ48_5sAfkcf86s3BwMrAB1C5y --gradio-auth a:a
2023-08-31 15:17:25.610456: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-31 15:17:26.640083: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
ngrok authtoken detected, trying to connect...
ngrok connected to localhost:7860! URL: https://[redacted].ngrok-free.app
You can use this link after the launch is complete.
Downloading face_yolov8n.pt: 100% 6.21M/6.21M [00:00<00:00, 157MB/s]
Downloading face_yolov8s.pt: 100% 22.5M/22.5M [00:00<00:00, 310MB/s]
Downloading hand_yolov8n.pt: 100% 6.22M/6.22M [00:00<00:00, 334MB/s]
Downloading person_yolov8n-seg.pt: 100% 6.75M/6.75M [00:00<00:00, 370MB/s]
Downloading person_yolov8s-seg.pt: 100% 23.8M/23.8M [00:00<00:00, 323MB/s]
[-] ADetailer initialized. version: 23.9.0, num models: 9
Loading weights [fc2511737a] from /content/stable-diffusion-webui/models/Stable-diffusion/chilloutmix_NiPrunedFp32Fix.safetensors
*** Error calling: /content/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py/ui
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/scripts.py", line 339, in wrap_call
        return func(*args, **kwargs)
      File "/content/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 131, in ui
        components, infotext_fields = adui(num_models, is_img2img, webui_info)
      File "/content/stable-diffusion-webui/extensions/adetailer/adetailer/ui.py", line 104, in adui
        state, infofields = one_ui_group(
      File "/content/stable-diffusion-webui/extensions/adetailer/adetailer/ui.py", line 178, in one_ui_group
        inpainting(w, n, is_img2img, webui_info)
      File "/content/stable-diffusion-webui/extensions/adetailer/adetailer/ui.py", line 431, in inpainting
        *webui_info.checkpoints_list(use_short=True),
    TypeError: checkpoint_tiles() got an unexpected keyword argument 'use_short'

---
*** Error calling: /content/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py/ui
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/scripts.py", line 339, in wrap_call
        return func(*args, **kwargs)
      File "/content/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 131, in ui
        components, infotext_fields = adui(num_models, is_img2img, webui_info)
      File "/content/stable-diffusion-webui/extensions/adetailer/adetailer/ui.py", line 104, in adui
        state, infofields = one_ui_group(
      File "/content/stable-diffusion-webui/extensions/adetailer/adetailer/ui.py", line 178, in one_ui_group
        inpainting(w, n, is_img2img, webui_info)
      File "/content/stable-diffusion-webui/extensions/adetailer/adetailer/ui.py", line 431, in inpainting
        *webui_info.checkpoints_list(use_short=True),
    TypeError: checkpoint_tiles() got an unexpected keyword argument 'use_short'

---
Running on local URL:  http://[redacted]

To create a public link, set `share=True` in `launch()`.
Startup time: 16.6s (launcher: 2.0s, import torch: 5.8s, import gradio: 0.7s, setup paths: 1.0s, other imports: 0.8s, list SD models: 2.6s, load scripts: 2.3s, create ui: 1.0s, gradio launch: 0.2s).
Creating model from config: /content/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: /content/stable-diffusion-webui/models/VAE/vae-ft-ema-560000-ema-pruned.ckpt
Applying attention optimization: xformers... done.
Model loaded in 7.4s (load weights from disk: 1.3s, create model: 1.9s, apply weights to model: 3.3s, load VAE: 0.5s, load textual inversion embeddings: 0.1s, calculate empty prompt: 0.2s).

[-] ADetailer: Invalid arguments passed to ADetailer.
    input: ()
    ADetailer disabled.

  0% 0/20 [00:00<?, ?it/s]
  5% 1/20 [00:03<00:58,  3.06s/it]
 15% 3/20 [00:03<00:13,  1.26it/s]
 25% 5/20 [00:03<00:05,  2.53it/s]
 30% 6/20 [00:03<00:04,  3.22it/s]
 35% 7/20 [00:03<00:03,  3.89it/s]
 40% 8/20 [00:04<00:02,  4.45it/s]
 45% 9/20 [00:04<00:02,  5.00it/s]
 50% 10/20 [00:04<00:01,  5.45it/s]
 55% 11/20 [00:04<00:01,  5.82it/s]
 60% 12/20 [00:04<00:01,  6.13it/s]
 65% 13/20 [00:04<00:01,  6.35it/s]
 70% 14/20 [00:04<00:00,  6.48it/s]
 75% 15/20 [00:05<00:00,  6.59it/s]
 80% 16/20 [00:05<00:00,  6.64it/s]
 85% 17/20 [00:05<00:00,  6.57it/s]
 90% 18/20 [00:05<00:00,  6.59it/s]
 95% 19/20 [00:05<00:00,  6.67it/s]
100% 20/20 [00:05<00:00,  3.42it/s]

[-] ADetailer: Invalid arguments passed to ADetailer.
    input: ()
    ADetailer disabled.
```

**Comment by drantini** [comment]
Can confirm this error happens, reverting to older version like @naduarte2 for now works.

**Comment by Kenneth-boop** [comment]
Also confirming the issue after updating extensions today.

**Comment by piratex123** [comment]
> New build seems to have entirely broken it on my end as well. Using the previous build worked fine as a temporary solution. (v23.8.1)

How do you use a previous build please!

**Comment by 88888888github** [comment]
I suggest implementing an automatic 3-day delay for web UI updates, or alternatively, an automatic update once it has been tested and confirmed to be issue-free.

**Comment by Bing-su** [comment]
I'll fix it when I get home from work. since @michgscod's ngrok token has been exposed, I'm going to delete this issue soon. @michgscod, you should reissue the ngrok token.

**Comment by naduarte2** [comment]
> > New build seems to have entirely broken it on my end as well. Using the previous build worked fine as a temporary solution. (v23.8.1)
> 
> How do you use a previous build please!

Steps:
1. download https://github.com/Bing-su/adetailer/archive/refs/tags/v23.8.1.zip
2. delete "./extensions/adetailer/" folder containing v23.9.0.
3. extract the adetailer-23.8.1 folder of the zip in ./extensions/,
4. run A1111 again and goodbye F*** 23.9.0.
5. Also it's really recommended to uncheck all the auto-updates (WebUI and extensions) until stability reach of all the extensions you use, the new WebUI v1.6.0 also gives a lot of problems with Deforum and many other extensions.

**Comment by ZeroCool22** [comment]
> > > New build seems to have entirely broken it on my end as well. Using the previous build worked fine as a temporary solution. (v23.8.1)
> > 
> > 
> > How do you use a previous build please!
> 
> Steps:
> 
>     1. download https://github.com/Bing-su/adetailer/archive/refs/tags/v23.8.1.zip
> 
>     2. delete "./extensions/adetailer/" folder containing v23.9.0.
> 
>     3. extract the adetailer-23.8.1 folder of the zip in ./extensions/,
> 
>     4. run A1111 again and goodbye F*** 23.9.0.
> 
>     5. Also it's really recommended to uncheck all the auto-updates (WebUI and extensions) until stability reach of all the extensions you use, the new WebUI v1.6.0 also gives a lot of problems with Deforum and many other extensions.

But now adetailer doesn't show a new version when checks for updates:

![Screenshot_3](https://github.com/Bing-su/adetailer/assets/13344308/75866a94-2d71-4bc8-b721-0c6d937ed666)

**Comment by michgscod** [comment]
> I'll fix it when I get home from work. since @michgscod's ngrok token has been exposed, I'm going to delete this issue soon. @michgscod, you should reissue the ngrok token.

thanks mate. i have reset my token, sorry for that.
