### ISSUE TITLE
[Bug]: ONly able to have 1 model tab

### ISSUE THREAD

**Issue by nikgrid7** [Bing-su/adetailer#305]
### Describe the bug

After the latest update I'm only able to have 1 model tab even though I have 2 in the settings

### Screenshots

![image](https://github.com/Bing-su/adetailer/assets/113899776/df509115-147d-48cd-8038-845667c48ffa)

![image](https://github.com/Bing-su/adetailer/assets/113899776/a250ff07-dbb8-46e4-8706-7c606d72a100)

### Console logs, from start to end.

```Shell
venv "G:\Apps\Stable_Diffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: v1.5.1
Commit hash: 68f336bd994bed5442ad95bad6b6ad5564a5409a






Installing sd-webui-controlnet requirement: changing opencv-python version from 4.7.0.72 to 4.8.0


Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72


Installing requirements for TemporalKit extension

Launching Web UI with arguments: --xformers --api --opt-sdp-no-mem-attention
reading checkpoint metadata: G:\Apps\Stable_Diffusion\stable-diffusion-webui\models\Stable-diffusion\Inpainting\absolutereality_v181.safetensors: AssertionError
Traceback (most recent call last):
  File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\modules\sd_models.py", line 63, in __init__
    self.metadata = read_metadata_from_safetensors(filename)
  File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\modules\sd_models.py", line 231, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: G:\Apps\Stable_Diffusion\stable-diffusion-webui\models\Stable-diffusion\Inpainting\absolutereality_v181.safetensors is not a safetensors file

Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: G:\Apps\Stable_Diffusion\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json

========================= a1111-sd-webui-lycoris =========================
Starting from stable-diffusion-webui version 1.5.0
a1111-sd-webui-lycoris extension is no longer needed

All its features have been integrated into the native LoRA extension
LyCORIS models can now be used as if there are regular LoRA models

This extension has been automatically deactivated
Please remove this extension
==========================================================================

Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 23.9.0, num models: 14
2023-09-01 22:41:09,520 - ControlNet - INFO - ControlNet v1.1.313
ControlNet preprocessor location: G:\Apps\Stable_Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-09-01 22:41:10,358 - ControlNet - INFO - ControlNet v1.1.313
2023-09-01 22:41:16,341 - roop - INFO - roop v0.0.2
2023-09-01 22:41:16,427 - roop - INFO - roop v0.0.2
reading lora G:\Apps\Stable_Diffusion\stable-diffusion-webui\models\Lora\Helper\emotion_angry_slider_v1.safetensors: AssertionError
Traceback (most recent call last):
  File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 35, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "lora/" + self.name, filename, read_metadata)
  File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\modules\cache.py", line 111, in cached_data_for_file
    value = func()
  File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 28, in read_metadata
    metadata = sd_models.read_metadata_from_safetensors(filename)
  File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\modules\sd_models.py", line 231, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: G:\Apps\Stable_Diffusion\stable-diffusion-webui\models\Lora\Helper\emotion_angry_slider_v1.safetensors is not a safetensors file

Loading weights [15012c538f] from G:\Apps\Stable_Diffusion\stable-diffusion-webui\models\Stable-diffusion\Photorealistic\realisticVisionV51_v51VAE.safetensors
*** Error calling: G:\Apps\Stable_Diffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py/ui
    Traceback (most recent call last):
      File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\modules\scripts.py", line 339, in wrap_call
        return func(*args, **kwargs)
      File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 131, in ui
        components, infotext_fields = adui(num_models, is_img2img, webui_info)
      File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\extensions\adetailer\adetailer\ui.py", line 104, in adui
        state, infofields = one_ui_group(
      File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\extensions\adetailer\adetailer\ui.py", line 178, in one_ui_group
        inpainting(w, n, is_img2img, webui_info)
      File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\extensions\adetailer\adetailer\ui.py", line 431, in inpainting
        *webui_info.checkpoints_list(use_short=True),
    TypeError: checkpoint_tiles() got an unexpected keyword argument 'use_short'

---
Creating model from config: G:\Apps\Stable_Diffusion\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
*** Error calling: G:\Apps\Stable_Diffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py/ui
    Traceback (most recent call last):
      File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\modules\scripts.py", line 339, in wrap_call
        return func(*args, **kwargs)
      File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 131, in ui
        components, infotext_fields = adui(num_models, is_img2img, webui_info)
      File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\extensions\adetailer\adetailer\ui.py", line 104, in adui
        state, infofields = one_ui_group(
      File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\extensions\adetailer\adetailer\ui.py", line 178, in one_ui_group
        inpainting(w, n, is_img2img, webui_info)
      File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\extensions\adetailer\adetailer\ui.py", line 431, in inpainting
        *webui_info.checkpoints_list(use_short=True),
    TypeError: checkpoint_tiles() got an unexpected keyword argument 'use_short'

---
loading settings: JSONDecodeError
Traceback (most recent call last):
  File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\modules\ui_loadsave.py", line 26, in __init__
    self.ui_settings = self.read_from_file()
  File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\modules\ui_loadsave.py", line 117, in read_from_file
    return json.load(file)
  File "C:\Users\The Razorback\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\The Razorback\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\The Razorback\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\The Razorback\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[VRAMEstimator] Loaded benchmark data.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 175.8s (launcher: 98.1s, import torch: 4.1s, import gradio: 1.3s, setup paths: 0.8s, import ldm: 0.1s, other imports: 7.6s, opts onchange: 0.3s, setup codeformer: 0.8s, list extensions: 0.2s, list SD models: 3.2s, load scripts: 28.5s, initialize extra networks: 0.8s, create ui: 22.5s, gradio launch: 4.6s, app_started_callback: 2.8s).
Applying attention optimization: xformers... done.
Model loaded in 119.1s (load weights from disk: 11.1s, create model: 2.8s, apply weights to model: 79.1s, apply half(): 5.7s, apply dtype to VAE: 0.2s, load VAE: 1.3s, move model to device: 3.4s, hijack: 0.4s, load textual inversion embeddings: 4.4s, calculate empty prompt: 10.7s).
reading checkpoint metadata: G:\Apps\Stable_Diffusion\stable-diffusion-webui\models\Stable-diffusion\Inpainting\absolutereality_v181.safetensors: AssertionError
Traceback (most recent call last):
  File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\modules\sd_models.py", line 63, in __init__
    self.metadata = read_metadata_from_safetensors(filename)
  File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\modules\sd_models.py", line 231, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: G:\Apps\Stable_Diffusion\stable-diffusion-webui\models\Stable-diffusion\Inpainting\absolutereality_v181.safetensors is not a safetensors file

reading lora G:\Apps\Stable_Diffusion\stable-diffusion-webui\models\Lora\Helper\emotion_angry_slider_v1.safetensors: AssertionError
Traceback (most recent call last):
  File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 35, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "lora/" + self.name, filename, read_metadata)
  File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\modules\cache.py", line 111, in cached_data_for_file
    value = func()
  File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 28, in read_metadata
    metadata = sd_models.read_metadata_from_safetensors(filename)
  File "G:\Apps\Stable_Diffusion\stable-diffusion-webui\modules\sd_models.py", line 231, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: G:\Apps\Stable_Diffusion\stable-diffusion-webui\models\Lora\Helper\emotion_angry_slider_v1.safetensors is not a safetensors file

Latent
txt2img_hr_latent
                                  Latent
txt2img_hr_latentit [00:00, ?it/s]
Latent
txt2img_hr_latent
Latent
txt2img_hr_latent
Latent
txt2img_hr_latent
Latent
txt2img_hr_latent
Latent
txt2img_hr_latent
Latent
txt2img_hr_latent

[-] ADetailer: Invalid arguments passed to ADetailer.
    input: ()
    ADetailer disabled.

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:13<00:00,  1.48it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:56<00:00,  2.80s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [01:21<00:00,  2.84s/it]
[-] ADetailer: Invalid arguments passed to ADetailer.
    input: ()
    ADetailer disabled.

Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [02:00<00:00,  3.02s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [02:00<00:00,  2.84s/it]
```

**Comment by Bing-su** [comment]
This is a duplicate of #304.
