### ISSUE TITLE
[Bug]: Using custom bbox detection model with ADetailer results in ['models.yolo'] not found

### ISSUE THREAD

**Issue by rackSD** [Bing-su/adetailer#314]
### Describe the bug

Trying to use a custom trained yolov5 model results in error and WebUI attempts to download a `models.yolo` package.

### Console logs, from start to end.

```Shell
venv "F:\Stable Diffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Launching Web UI with arguments: --opt-sdp-attention
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
[-] ADetailer initialized. version: 23.9.1, num models: 11
Loading weights [8112ab8b43] from F:\Stable Diffusion\stable-diffusion-webui\models\Stable-diffusion\Anime\Based64\based65_v20.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 12.5s (prepare environment: 2.3s, import torch: 3.2s, import gradio: 0.8s, setup paths: 0.7s, initialize shared: 0.3s, other imports: 0.6s, setup codeformer: 0.1s, list SD models: 0.4s, load scripts: 3.2s, create ui: 0.5s, gradio launch: 0.4s).
Creating model from config: F:\Stable Diffusion\stable-diffusion-webui\configs\v1-inference.yaml
Loading VAE weights specified in settings: F:\Stable Diffusion\stable-diffusion-webui\models\VAE\kl-f8-anime2.ckpt
Applying attention optimization: sdp... done.
Model loaded in 7.1s (load weights from disk: 1.2s, create model: 0.3s, apply weights to model: 2.9s, apply half(): 1.2s, load VAE: 0.4s, calculate empty prompt: 1.0s).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  8.38it/s]
WARNING  F:\Stable Diffusion\stable-diffusion-webui\models\adetailer\chest.pt appears to require 'models.yolo', which is not in ultralytics requirements.
AutoInstall will run now for 'models.yolo' but this feature will be removed in the future.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'
requirements: Ultralytics requirement ['models.yolo'] not found, attempting AutoUpdate...
ERROR: Could not find a version that satisfies the requirement models.yolo (from versions: none)
ERROR: No matching distribution found for models.yolo

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
requirements:  Command 'pip install --no-cache "models.yolo" ' returned non-zero exit status 1.
*** Error running postprocess_image: F:\Stable Diffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "F:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "F:\Stable Diffusion\stable-diffusion-webui\extensions\adetailer\adetailer\traceback.py", line 159, in wrapper
        raise error from None
    ModuleNotFoundError:
    ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
    │                                                   System info                                                    │
    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃             ┃ Value                                                                                          ┃ │
    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │    Platform │ Windows-10-10.0.19044-SP0                                                                      │ │
    │ │      Python │ 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]               │ │
    │ │     Version │ v1.6.0                                                                                         │ │
    │ │      Commit │ 5ef669de080814067961f28357256e8fe27544f4                                                       │ │
    │ │ Commandline │ ['launch.py', '--opt-sdp-attention']                                                           │ │
    │ │   Libraries │ {'torch': '2.0.1+cu118', 'torchvision': '0.15.2+cu118', 'ultralytics': '8.0.169', 'mediapipe': │ │
    │ │             │ '0.10.3'}                                                                                      │ │
    │ └─────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘ │
    │                                  Inputs                                                                          │
    │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                                         │
    │ ┃                 ┃ Value                                              ┃                                         │
    │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩                                         │
    │ │          prompt │ 1girl, standing                                    │                                         │
    │ │ negative_prompt │ EasyNegative                                       │                                         │
    │ │          n_iter │ 1                                                  │                                         │
    │ │      batch_size │ 1                                                  │                                         │
    │ │           width │ 576                                                │                                         │
    │ │          height │ 832                                                │                                         │
    │ │    sampler_name │ DPM++ 2M Karras                                    │                                         │
    │ │       enable_hr │ False                                              │                                         │
    │ │     hr_upscaler │ 4x-AnimeSharp                                      │                                         │
    │ │      checkpoint │ Anime\Based64\based65_v20.safetensors [8112ab8b43] │                                         │
    │ │             vae │ kl-f8-anime2.ckpt                                  │                                         │
    │ │            unet │ Automatic                                          │                                         │
    │ └─────────────────┴────────────────────────────────────────────────────┘                                         │
    │             ADetailer                                                                                            │
    │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┓                                                                               │
    │ ┃                     ┃ Value    ┃                                                                               │
    │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━┩                                                                               │
    │ │             version │ 23.9.1   │                                                                               │
    │ │            ad_model │ chest.pt │                                                                               │
    │ │           ad_prompt │          │                                                                               │
    │ │  ad_negative_prompt │          │                                                                               │
    │ │ ad_controlnet_model │ None     │                                                                               │
    │ │              is_api │ False    │                                                                               │
    │ └─────────────────────┴──────────┘                                                                               │
    │ ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮             │
    │ │ F:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\ultralytics\nn\tasks.py:527 in │             │
    │ │ torch_safe_load                                                                                  │             │
    │ │                                                                                                  │             │
    │ │   524 │   │   │   │   'ultralytics.yolo.utils': 'ultralytics.utils',                             │             │
    │ │   525 │   │   │   │   'ultralytics.yolo.v8': 'ultralytics.models.yolo',                          │             │
    │ │   526 │   │   │   │   'ultralytics.yolo.data': 'ultralytics.data'}):  # for legacy 8.0 Classif   │             │
    │ │ ❱ 527 │   │   │   return torch.load(file, map_location='cpu'), file  # load                      │             │
    │ │   528 │                                                                                          │             │
    │ │   529 │   except ModuleNotFoundError as e:  # e.name is missing module name                      │             │
    │ │   530 │   │   if e.name == 'models':                                                             │             │
    │ │                                                                                                  │             │
    │ │ F:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py:809 in  │             │
    │ │ load                                                                                             │             │
    │ │                                                                                                  │             │
    │ │    806 │   │   │   │   │   │   return _load(opened_zipfile, map_location, _weights_only_unpickl  │             │
    │ │    807 │   │   │   │   │   except RuntimeError as e:                                             │             │
    │ │    808 │   │   │   │   │   │   raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None   │             │
    │ │ ❱  809 │   │   │   │   return _load(opened_zipfile, map_location, pickle_module, **pickle_load_  │             │
    │ │    810 │   │   if weights_only:                                                                  │             │
    │ │    811 │   │   │   try:                                                                          │             │
    │ │    812 │   │   │   │   return _legacy_load(opened_file, map_location, _weights_only_unpickler,   │             │
    │ │                                                                                                  │             │
    │ │ F:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py:1172 in │             │
    │ │ _load                                                                                            │             │
    │ │                                                                                                  │             │
    │ │   1169 │                                                                                         │             │
    │ │   1170 │   unpickler = UnpicklerWrapper(data_file, **pickle_load_args)                           │             │
    │ │   1171 │   unpickler.persistent_load = persistent_load                                           │             │
    │ │ ❱ 1172 │   result = unpickler.load()                                                             │             │
    │ │   1173 │                                                                                         │             │
    │ │   1174 │   torch._utils._validate_loaded_sparse_tensors()                                        │             │
    │ │   1175                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\pickle.py:1213 in load                │             │
    │ │                                                                                                  │             │
    │ │   1210 │   │   │   │   if not key:                                                               │             │
    │ │   1211 │   │   │   │   │   raise EOFError                                                        │             │
    │ │   1212 │   │   │   │   assert isinstance(key, bytes_types)                                       │             │
    │ │ ❱ 1213 │   │   │   │   dispatch[key[0]](self)                                                    │             │
    │ │   1214 │   │   except _Stop as stopinst:                                                         │             │
    │ │   1215 │   │   │   return stopinst.value                                                         │             │
    │ │   1216                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\pickle.py:1529 in load_global         │             │
    │ │                                                                                                  │             │
    │ │   1526 │   def load_global(self):                                                                │             │
    │ │   1527 │   │   module = self.readline()[:-1].decode("utf-8")                                     │             │
    │ │   1528 │   │   name = self.readline()[:-1].decode("utf-8")                                       │             │
    │ │ ❱ 1529 │   │   klass = self.find_class(module, name)                                             │             │
    │ │   1530 │   │   self.append(klass)                                                                │             │
    │ │   1531 │   dispatch[GLOBAL[0]] = load_global                                                     │             │
    │ │   1532                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ F:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py:1165 in │             │
    │ │ find_class                                                                                       │             │
    │ │                                                                                                  │             │
    │ │   1162 │   │   │   │   except KeyError:                                                          │             │
    │ │   1163 │   │   │   │   │   pass                                                                  │             │
    │ │   1164 │   │   │   mod_name = load_module_mapping.get(mod_name, mod_name)                        │             │
    │ │ ❱ 1165 │   │   │   return super().find_class(mod_name, name)                                     │             │
    │ │   1166 │                                                                                         │             │
    │ │   1167 │   # Load the data (which may in turn use `persistent_load` to load tensors)             │             │
    │ │   1168 │   data_file = io.BytesIO(zip_file.get_record(pickle_file))                              │             │
    │ │                                                                                                  │             │
    │ │ F:\Stable                                                                                        │             │
    │ │ Diffusion\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\_graveyard\legacy_impo │             │
    │ │ rt_unpickler.py:24 in find_class                                                                 │             │
    │ │                                                                                                  │             │
    │ │   21 │   │   # this warning won't trigger for standalone as these imports are identical          │             │
    │ │   22 │   │   if module != new_module:                                                            │             │
    │ │   23 │   │   │   warnings.warn(f"Redirecting import of {module}.{name} to {new_module}.{name}    │             │
    │ │ ❱ 24 │   │   return super().find_class(new_module, name)                                         │             │
    │ │   25                                                                                             │             │
    │ │   26                                                                                             │             │
    │ │   27 def compare_version(package: str, op: Callable, version: str, use_base_version: bool = F    │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\pickle.py:1580 in find_class          │             │
    │ │                                                                                                  │             │
    │ │   1577 │   │   │   │   module, name = _compat_pickle.NAME_MAPPING[(module, name)]                │             │
    │ │   1578 │   │   │   elif module in _compat_pickle.IMPORT_MAPPING:                                 │             │
    │ │   1579 │   │   │   │   module = _compat_pickle.IMPORT_MAPPING[module]                            │             │
    │ │ ❱ 1580 │   │   __import__(module, level=0)                                                       │             │
    │ │   1581 │   │   if self.proto >= 4:                                                               │             │
    │ │   1582 │   │   │   return _getattribute(sys.modules[module], name)[0]                            │             │
    │ │   1583 │   │   else:                                                                             │             │
    │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯             │
    │ ModuleNotFoundError: No module named 'models.yolo'                                                               │
    │                                                                                                                  │
    │ During handling of the above exception, another exception occurred:                                              │
    │                                                                                                                  │
    │ ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮             │
    │ │ F:\Stable Diffusion\stable-diffusion-webui\extensions\adetailer\adetailer\traceback.py:139 in    │             │
    │ │ wrapper                                                                                          │             │
    │ │                                                                                                  │             │
    │ │   136 │   │   width = width - 4 if width > 4 else None                                           │             │
    │ │   137 │   │   console = Console(file=string, width=width)                                        │             │
    │ │   138 │   │   try:                                                                               │             │
    │ │ ❱ 139 │   │   │   return func(*args, **kwargs)                                                   │             │
    │ │   140 │   │   except Exception as e:                                                             │             │
    │ │   141 │   │   │   tables = [                                                                     │             │
    │ │   142 │   │   │   │   get_table(title, data)                                                     │             │
    │ │                                                                                                  │             │
    │ │ F:\Stable Diffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py:641 in     │             │
    │ │ postprocess_image                                                                                │             │
    │ │                                                                                                  │             │
    │ │   638 │   │   │   for n, args in enumerate(arg_list):                                            │             │
    │ │   639 │   │   │   │   if args.ad_model == "None":                                                │             │
    │ │   640 │   │   │   │   │   continue                                                               │             │
    │ │ ❱ 641 │   │   │   │   is_processed |= self._postprocess_image_inner(p, pp, args, n=n)            │             │
    │ │   642 │   │                                                                                      │             │
    │ │   643 │   │   if is_processed:                                                                   │             │
    │ │   644 │   │   │   self.save_image(                                                               │             │
    │ │                                                                                                  │             │
    │ │ F:\Stable Diffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py:564 in     │             │
    │ │ _postprocess_image_inner                                                                         │             │
    │ │                                                                                                  │             │
    │ │   561 │   │   │   kwargs["device"] = self.ultralytics_device                                     │             │
    │ │   562 │   │                                                                                      │             │
    │ │   563 │   │   with change_torch_load():                                                          │             │
    │ │ ❱ 564 │   │   │   pred = predictor(ad_model, pp.image, args.ad_confidence, **kwargs)             │             │
    │ │   565 │   │                                                                                      │             │
    │ │   566 │   │   masks = self.pred_preprocessing(pred, args)                                        │             │
    │ │   567                                                                                            │             │
    │ │                                                                                                  │             │
    │ │ F:\Stable Diffusion\stable-diffusion-webui\extensions\adetailer\adetailer\ultralytics.py:20 in   │             │
    │ │ ultralytics_predict                                                                              │             │
    │ │                                                                                                  │             │
    │ │   17 │   confidence: float = 0.3,                                                                │             │
    │ │   18 │   device: str = "",                                                                       │             │
    │ │   19 ) -> PredictOutput:                                                                         │             │
    │ │ ❱ 20 │   model = YOLO(model_path)                                                                │             │
    │ │   21 │   pred = model(image, conf=confidence, device=device)                                     │             │
    │ │   22 │                                                                                           │             │
    │ │   23 │   bboxes = pred[0].boxes.xyxy.cpu().numpy()                                               │             │
    │ │                                                                                                  │             │
    │ │ F:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\ultralytics\engine\model.py:92 │             │
    │ │ in __init__                                                                                      │             │
    │ │                                                                                                  │             │
    │ │    89 │   │   if suffix in ('.yaml', '.yml'):                                                    │             │
    │ │    90 │   │   │   self._new(model, task)                                                         ��             │
    │ │    91 │   │   else:                                                                              │             │
    │ │ ❱  92 │   │   │   self._load(model, task)                                                        │             │
    │ │    93 │                                                                                          │             │
    │ │    94 │   def __call__(self, source=None, stream=False, **kwargs):                               │             │
    │ │    95 │   │   """Calls the 'predict' function with given arguments to perform object detection   │             │
    │ │                                                                                                  │             │
    │ │ F:\Stable                                                                                        │             │
    │ │ Diffusion\stable-diffusion-webui\venv\lib\site-packages\ultralytics\engine\model.py:138 in _load │             │
    │ │                                                                                                  │             │
    │ │   135 │   │   """                                                                                │             │
    │ │   136 │   │   suffix = Path(weights).suffix                                                      │             │
    │ │   137 │   │   if suffix == '.pt':                                                                │             │
    │ │ ❱ 138 │   │   │   self.model, self.ckpt = attempt_load_one_weight(weights)                       │             │
    │ │   139 │   │   │   self.task = self.model.args['task']                                            │             │
    │ │   140 │   │   │   self.overrides = self.model.args = self._reset_ckpt_args(self.model.args)      │             │
    │ │   141 │   │   │   self.ckpt_path = self.model.pt_path                                            │             │
    │ │                                                                                                  │             │
    │ │ F:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\ultralytics\nn\tasks.py:588 in │             │
    │ │ attempt_load_one_weight                                                                          │             │
    │ │                                                                                                  │             │
    │ │   585                                                                                            │             │
    │ │   586 def attempt_load_one_weight(weight, device=None, inplace=True, fuse=False):                │             │
    │ │   587 │   """Loads a single model weights."""                                                    │             │
    │ │ ❱ 588 │   ckpt, weight = torch_safe_load(weight)  # load ckpt                                    │             │
    │ │   589 │   args = {**DEFAULT_CFG_DICT, **(ckpt.get('train_args', {}))}  # combine model and def   │             │
    │ │   590 │   model = (ckpt.get('ema') or ckpt['model']).to(device).float()  # FP32 model            │             │
    │ │   591                                                                                            │             │
    │ │                                                                                                  │             │
    │ │ F:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\ultralytics\nn\tasks.py:543 in │             │
    │ │ torch_safe_load                                                                                  │             │
    │ │                                                                                                  │             │
    │ │   540 │   │   │   │   │      f"run a command with an official YOLOv8 model, i.e. 'yolo predict   │             │
    │ │   541 │   │   check_requirements(e.name)  # install missing module                               │             │
    │ │   542 │   │                                                                                      │             │
    │ │ ❱ 543 │   │   return torch.load(file, map_location='cpu'), file  # load                          │             │
    │ │   544                                                                                            │             │
    │ │   545                                                                                            │             │
    │ │   546 def attempt_load_weights(weights, device=None, inplace=True, fuse=False):                  │             │
    │ │                                                                                                  │             │
    │ │ F:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py:809 in  │             │
    │ │ load                                                                                             │             │
    │ │                                                                                                  │             │
    │ │    806 │   │   │   │   │   │   return _load(opened_zipfile, map_location, _weights_only_unpickl  │             │
    │ │    807 │   │   │   │   │   except RuntimeError as e:                                             │             │
    │ │    808 │   │   │   │   │   │   raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None   │             │
    │ │ ❱  809 │   │   │   │   return _load(opened_zipfile, map_location, pickle_module, **pickle_load_  │             │
    │ │    810 │   │   if weights_only:                                                                  │             │
    │ │    811 │   │   │   try:                                                                          │             │
    │ │    812 │   │   │   │   return _legacy_load(opened_file, map_location, _weights_only_unpickler,   │             │
    │ │                                                                                                  │             │
    │ │ F:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py:1172 in │             │
    │ │ _load                                                                                            │             │
    │ │                                                                                                  │             │
    │ │   1169 │                                                                                         │             │
    │ │   1170 │   unpickler = UnpicklerWrapper(data_file, **pickle_load_args)                           │             │
    │ │   1171 │   unpickler.persistent_load = persistent_load                                           │             │
    │ │ ❱ 1172 │   result = unpickler.load()                                                             │             │
    │ │   1173 │                                                                                         │             │
    │ │   1174 │   torch._utils._validate_loaded_sparse_tensors()                                        │             │
    │ │   1175                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\pickle.py:1213 in load                │             │
    │ │                                                                                                  │             │
    │ │   1210 │   │   │   │   if not key:                                                               │             │
    │ │   1211 │   │   │   │   │   raise EOFError                                                        │             │
    │ │   1212 │   │   │   │   assert isinstance(key, bytes_types)                                       │             │
    │ │ ❱ 1213 │   │   │   │   dispatch[key[0]](self)                                                    │             │
    │ │   1214 │   │   except _Stop as stopinst:                                                         │             │
    │ │   1215 │   │   │   return stopinst.value                                                         │             │
    │ │   1216                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\pickle.py:1529 in load_global         │             │
    │ │                                                                                                  │             │
    │ │   1526 │   def load_global(self):                                                                │             │
    │ │   1527 │   │   module = self.readline()[:-1].decode("utf-8")                                     │             │
    │ │   1528 │   │   name = self.readline()[:-1].decode("utf-8")                                       │             │
    │ │ ❱ 1529 │   │   klass = self.find_class(module, name)                                             │             │
    │ │   1530 │   │   self.append(klass)                                                                │             │
    │ │   1531 │   dispatch[GLOBAL[0]] = load_global                                                     │             │
    │ │   1532                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ F:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py:1165 in │             │
    │ │ find_class                                                                                       │             │
    │ │                                                                                                  │             │
    │ │   1162 │   │   │   │   except KeyError:                                                          │             │
    │ │   1163 │   │   │   │   │   pass                                                                  │             │
    │ │   1164 │   │   │   mod_name = load_module_mapping.get(mod_name, mod_name)                        │             │
    │ │ ❱ 1165 │   │   │   return super().find_class(mod_name, name)                                     │             │
    │ │   1166 │                                                                                         │             │
    │ │   1167 │   # Load the data (which may in turn use `persistent_load` to load tensors)             │             │
    │ │   1168 │   data_file = io.BytesIO(zip_file.get_record(pickle_file))                              │             │
    │ │                                                                                                  │             │
    │ │ F:\Stable                                                                                        │             │
    │ │ Diffusion\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\_graveyard\legacy_impo │             │
    │ │ rt_unpickler.py:24 in find_class                                                                 │             │
    │ │                                                                                                  │             │
    │ │   21 │   │   # this warning won't trigger for standalone as these imports are identical          │             │
    │ │   22 │   │   if module != new_module:                                                            │             │
    │ │   23 │   │   │   warnings.warn(f"Redirecting import of {module}.{name} to {new_module}.{name}    │             │
    │ │ ❱ 24 │   │   return super().find_class(new_module, name)                                         │             │
    │ │   25                                                                                             │             │
    │ │   26                                                                                             │             │
    │ │   27 def compare_version(package: str, op: Callable, version: str, use_base_version: bool = F    │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\pickle.py:1580 in find_class          │             │
    │ │                                                                                                  │             │
    │ │   1577 │   │   │   │   module, name = _compat_pickle.NAME_MAPPING[(module, name)]                │             │
    │ │   1578 │   │   │   elif module in _compat_pickle.IMPORT_MAPPING:                                 │             │
    │ │   1579 │   │   │   │   module = _compat_pickle.IMPORT_MAPPING[module]                            │             │
    │ │ ❱ 1580 │   │   __import__(module, level=0)                                                       │             │
    │ │   1581 │   │   if self.proto >= 4:                                                               │             │
    │ │   1582 │   │   │   return _getattribute(sys.modules[module], name)[0]                            │             │
    │ │   1583 │   │   else:                                                                             │             │
    │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯             │
    │ ModuleNotFoundError: No module named 'models.yolo'                                                               │
    ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


---
```

### List of installed extensions

![image](https://github.com/Bing-su/adetailer/assets/118420602/39815ba6-4c5d-4303-aaaf-b7285f2eb0d1)
Disabled all extensions except for ADetailer.

**Comment by rackSD** [comment]
Apologies, the model's training method introduced some kind of additional dependency. Training again with the correct parameters resolved the issue.
