### ISSUE TITLE
what's wrong with the error?

### ISSUE THREAD

**Issue by aleylinx** [Bing-su/adetailer#324]
### Question

when i install the adetailer and restart SD,it shows error like this 
`[-] ADetailer: Failed to load model 'face_yolov8n.pt' from huggingface
[-] ADetailer: Failed to load model 'face_yolov8s.pt' from huggingface
[-] ADetailer: Failed to load model 'hand_yolov8n.pt' from huggingface
[-] ADetailer: Failed to load model 'person_yolov8n-seg.pt' from huggingface
[-] ADetailer: Failed to load model 'person_yolov8s-seg.pt' from huggingface
[-] ADetailer initialized. version: 23.9.2, num models: 4`

How to fix this problem?

**Comment by Bing-su** [comment]
There seems to be some environments where huggingface is not accessible. Try adding `--ad-no-huggingface` to your arguments.

**Comment by reklipse** [comment]
same here, --ad-no-huggingface does not help

**Comment by mongalong247** [comment]
I am unsure if this is related, i tried the --ad-no-huggingface and still got the error.  When i ran an update to the latest version this morning I started getting the error below.

*** Error loading script: !adetailer.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 20, in <module>
        from adetailer import (
      File "C:\AI\stable-diffusion-webui\extensions\adetailer\adetailer\__init__.py", line 5, in <module>
        from .ultralytics import ultralytics_predict
      File "C:\AI\stable-diffusion-webui\extensions\adetailer\adetailer\ultralytics.py", line 8, in <module>
        from ultralytics import YOLO
    ImportError: cannot import name 'YOLO' from 'ultralytics' (unknown location)

**Comment by reklipse** [comment]
Same

**Comment by hucaixue** [comment]
same problem

**Comment by hucaixue** [comment]
> There seems to be some environments where huggingface is not accessible. Try adding `--ad-no-huggingface` to your arguments.

Hi, how to add? Thanks!

**Comment by nakedfighter3d** [comment]
Yeah, it was okay previously but recently after the update I also got 
`ImportError: cannot import name 'YOLO' from 'ultralytics' (unknown location)`
