### ISSUE TITLE
I am unsure if this is related, i tried the --ad-no-huggingface and still got the error.  When i ran an update to the latest version this morning I started getting the error below.

### ISSUE THREAD

**Issue by wyw19902006** [Bing-su/adetailer#330]
I am unsure if this is related, i tried the --ad-no-huggingface and still got the error.  When i ran an update to the latest version this morning I started getting the error below.

*** Error loading script: !adetailer.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 20, in <module>
        from adetailer import (
      File "C:\AI\stable-diffusion-webui\extensions\adetailer\adetailer\__init__.py", line 5, in <module>
        from .ultralytics import ultralytics_predict
      File "C:\AI\stable-diffusion-webui\extensions\adetailer\adetailer\ultralytics.py", line 8, in <module>
        from ultralytics import YOLO
    ImportError: cannot import name 'YOLO' from 'ultralytics' (unknown location)

_Originally posted by @mongalong247 in https://github.com/Bing-su/adetailer/issues/324#issuecomment-1718368050_

**Comment by Bing-su** [comment]
Update ultralytics to version 8.0.178 or later in your Python venv.
