### ISSUE TITLE
[Bug]: Error Working with dual GPU laptop, NotImplementedError

### ISSUE THREAD

**Issue by LieDeath** [Bing-su/adetailer#331]
### Describe the bug

This extension failed to work on my computer, no effects, only with cold errors, NotImplementedError. It told me something, that is 
```
Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). 
```
BUT My computer has dual GPU, the GPU0 is intel Xe built in card, and the GPU1 is an nvidia RTX3070, with mix mode on. 
**I have CUDA device!** 
Any ideas? I have reset all the A1111 WEBUI settings, reinstall everything related such as GPU driver, nothing worked. My computer can't shutdown the built in intel GPU.

### Console logs, from start to end.

```Shell
*** Error running postprocess_image: D:\AI7\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "D:\AI7\stable-diffusion-webui\modules\scripts.py", line 575, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\AI7\stable-diffusion-webui\extensions\adetailer\adetailer\traceback.py", line 159, in wrapper
        raise error from None
    NotImplementedError:
    ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
    │                                                   System info                                                    │
    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃             ┃ Value                                                                                          ┃ │
    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │    Platform │ Windows-10-10.0.22621-SP0                                                                      │ │
    │ │      Python │ 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]               │ │
    │ │     Version │ v1.5.2                                                                                         │ │
    │ │      Commit │ c9c8485bc1e8720aba70f029d25cba1c4abf2b5c                                                       │ │
    │ │ Commandline │ ['launch.py', '--xformers', '--xformers-flash-attention', '--opt-sub-quad-attention',          │ │
    │ │             │ '--opt-channelslast', '--disable-nan-check', '--autolaunch', '--disable-safe-unpickle']        │ │
    │ │   Libraries │ {'torch': '2.0.0+cu118', 'torchvision': '0.15.1', 'ultralytics': '8.0.173', 'mediapipe':       │ │
    │ │             │ '0.10.3'}                                                                                      │ │
    │ └─────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘ │
    │                                                      Inputs                                                      │
    │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃                 ┃ Value                                                                                      ┃ │
    │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │          prompt │ Masterpiece, high quality, beautiful wallpaper, 16k, positive perspective, perfect body,   │ │
    │ │                 │ complete body, detailed face, delicate features, (solo:1.2), ((1girl)), thin, sexy,        │ │
    │ │                 │ (medium to large breasts :1.2), (tall body), high height,                                  │ │
    │ │                 │ (Cap :1.3), (racer style clothing :1.4), Sweat, sports bracelets, collars, midriff, black  │ │
    │ │                 │ and yellow tones, (bomber jacket draped over the body), (corset), (miniskirt :1.3),        │ │
    │ │                 │ (broken black over knee socks), (socks broken), (sitting on the car)                       │ │
    │ │ negative_prompt │ paintings, sketches, (worst quality:1.74), (low quality:1.74), (normal quality:1.44),      │ │
    │ │                 │ lowres, normal quality, ((grayscale)), skin spots, acnes, skin blemishes, age spot,        │ │
    │ │                 │ glans,extra fingers,                                                                       │ │
    │ │                 │ fewer fingers,strange fingers,((bad hand)),Hand grip,(lean),Extra ears,(Four ears),Strange │ │
    │ │                 │ eyes,((Bare nipple)),,(three arms),Many hands,(Many arms),((watermarking)),(inaccurate     │ │
    │ │                 │ limb:1.2), furry                                                                           │ │
    │ │          n_iter │ 1                                                                                          │ │
    │ │      batch_size │ 1                                                                                          │ │
    │ │           width │ 704                                                                                        │ │
    │ │          height │ 960                                                                                        │ │
    │ │    sampler_name │ Euler a                                                                                    │ │
    │ │       enable_hr │ True                                                                                       │ │
    │ │     hr_upscaler │ R-ESRGAN 4x+ Anime6B                                                                       │ │
    │ │      checkpoint │ 写实与优雅.ckpt                                                                            │ │
    │ │             vae │ vae-ft-mse-840000-ema-pruned.ckpt                                                          │ │
    │ │            unet │ Automatic                                                                                  │ │
    │ └─────────────────┴────────────────────────────────────────────────────────────────────────────────────────────┘ │
    │                 ADetailer                                                                                        │
    │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓                                                                        │
    │ ┃                     ┃ Value           ┃                                                                        │
    │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩                                                                        │
    │ │             version │ 23.9.2          │                                                                        │
    │ │            ad_model │ face_yolov8n.pt │                                                                        │
    │ │           ad_prompt │                 │                                                                        │
    │ │  ad_negative_prompt │                 │                                                                        │
    │ │ ad_controlnet_model │ None            │                                                                        │
    │ │              is_api │ False           │                                                                        │
    │ └─────────────────────┴─────────────────┘                                                                        │
    │ ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮             │
    │ │ D:\AI7\stable-diffusion-webui\extensions\adetailer\adetailer\traceback.py:139 in wrapper         │             │
    │ │                                                                                                  │             │
    │ │   136 │   │   width = width - 4 if width > 4 else None                                           │             │
    │ │   137 │   │   console = Console(file=string, width=width)                                        │             │
    │ │   138 │   │   try:                                                                               │             │
    │ │ ❱ 139 │   │   │   return func(*args, **kwargs)                                                   │             │
    │ │   140 │   │   except Exception as e:                                                             │             │
    │ │   141 │   │   │   tables = [                                                                     │             │
    │ │   142 │   │   │   │   get_table(title, data)                                                     │             │
    │ │                                                                                                  │             │
    │ │ D:\AI7\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py:656 in                  │             │
    │ │ postprocess_image                                                                                │             │
    │ │                                                                                                  │             │
    │ │   653 │   │   │   for n, args in enumerate(arg_list):                                            │             │
    │ │   654 │   │   │   │   if args.ad_model == "None":                                                │             │
    │ │   655 │   │   │   │   │   continue                                                               │             │
    │ │ ❱ 656 │   │   │   │   is_processed |= self._postprocess_image_inner(p, pp, args, n=n)            │             │
    │ │   657 │   │                                                                                      │             │
    │ │   658 │   │   if is_processed:                                                                   │             │
    │ │   659 │   │   │   self.save_image(                                                               │             │
    │ │                                                                                                  │             │
    │ │ D:\AI7\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py:579 in                  │             │
    │ │ _postprocess_image_inner                                                                         │             │
    │ │                                                                                                  │             │
    │ │   576 │   │   │   kwargs["device"] = self.ultralytics_device                                     │             │
    │ │   577 │   │                                                                                      │             │
    │ │   578 │   │   with change_torch_load():                                                          │             │
    │ │ ❱ 579 │   │   │   pred = predictor(ad_model, pp.image, args.ad_confidence, **kwargs)             │             │
    │ │   580 │   │                                                                                      │             │
    │ │   581 │   │   masks = self.pred_preprocessing(pred, args)                                        │             │
    │ │   582                                                                                            │             │
    │ │                                                                                                  │             │
    │ │ D:\AI7\stable-diffusion-webui\extensions\adetailer\adetailer\ultralytics.py:21 in                │             │
    │ │ ultralytics_predict                                                                              │             │
    │ │                                                                                                  │             │
    │ │   18 │   device: str = "",                                                                       │             │
    │ │   19 ) -> PredictOutput:                                                                         │             │
    │ │   20 │   model = YOLO(model_path)                                                                │             │
    │ │ ❱ 21 │   pred = model(image, conf=confidence, device=device)                                     │             │
    │ │   22 │                                                                                           │             │
    │ │   23 │   bboxes = pred[0].boxes.xyxy.cpu().numpy()                                               │             │
    │ │   24 │   if bboxes.size == 0:                                                                    │             │
    │ │                                                                                                  │             │
    │ │ D:\AI7\stable-diffusion-webui\venv\lib\site-packages\ultralytics\engine\model.py:96 in __call__  │             │
    │ │                                                                                                  │             │
    │ │    93 │                                                                                          │             │
    │ │    94 │   def __call__(self, source=None, stream=False, **kwargs):                               │             │
    │ │    95 │   │   """Calls the 'predict' function with given arguments to perform object detection   │             │
    │ │ ❱  96 │   │   return self.predict(source, stream, **kwargs)                                      │             │
    │ │    97 │                                                                                          │             │
    │ │    98 │   @staticmethod                                                                          │             │
    │ │    99 │   def is_hub_model(model):                                                               │             │
    │ │                                                                                                  │             │
    │ │ D:\AI7\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py:115 in           │             │
    │ │ decorate_context                                                                                 │             │
    │ │                                                                                                  │             │
    │ │   112 │   @functools.wraps(func)                                                                 │             │
    │ │   113 │   def decorate_context(*args, **kwargs):                                                 │             │
    │ │   114 │   │   with ctx_factory():                                                                │             │
    │ │ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │             │
    │ │   116 │                                                                                          │             │
    │ │   117 │   return decorate_context                                                                │             │
    │ │   118                                                                                            │             │
    │ │                                                                                                  │             │
    │ │ D:\AI7\stable-diffusion-webui\venv\lib\site-packages\ultralytics\engine\model.py:238 in predict  │             │
    │ │                                                                                                  │             │
    │ │   235 │   │   │   │   self.predictor.save_dir = get_save_dir(self.predictor.args)                │             │
    │ │   236 │   │   if prompts and hasattr(self.predictor, 'set_prompts'):  # for SAM-type models      │             │
    │ │   237 │   │   │   self.predictor.set_prompts(prompts)                                            │             │
    │ │ ❱ 238 │   │   return self.predictor.predict_cli(source=source) if is_cli else self.predictor(s   │             │
    │ │   239 │                                                                                          │             │
    │ │   240 │   def track(self, source=None, stream=False, persist=False, **kwargs):                   │             │
    │ │   241 │   │   """                                                                                │             │
    │ │                                                                                                  │             │
    │ │ D:\AI7\stable-diffusion-webui\venv\lib\site-packages\ultralytics\engine\predictor.py:194 in      │             │
    │ │ __call__                                                                                         │             │
    │ │                                                                                                  │             │
    │ │   191 │   │   if stream:                                                                         │             │
    │ │   192 │   │   │   return self.stream_inference(source, model, *args, **kwargs)                   │             │
    │ │   193 │   │   else:                                                                              │             │
    │ │ ❱ 194 │   │   │   return list(self.stream_inference(source, model, *args, **kwargs))  # merge    │             │
    │ │   195 │                                                                                          │             │
    │ │   196 │   def predict_cli(self, source=None, model=None):                                        │             │
    │ │   197 │   │   """Method used for CLI prediction. It uses always generator as outputs as not re   │             │
    │ │                                                                                                  │             │
    │ │ D:\AI7\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py:35 in            │             │
    │ │ generator_context                                                                                │             │
    │ │                                                                                                  │             │
    │ │    32 │   │   try:                                                                               │             │
    │ │    33 │   │   │   # Issuing `None` to a generator fires it up                                    │             │
    │ │    34 │   │   │   with ctx_factory():                                                            │             │
    │ │ ❱  35 │   │   │   │   response = gen.send(None)                                                  │             │
    │ │    36 │   │   │                                                                                  │             │
    │ │    37 │   │   │   while True:                                                                    │             │
    │ │    38 │   │   │   │   try:                                                                       │             │
    │ │                                                                                                  │             │
    │ │ D:\AI7\stable-diffusion-webui\venv\lib\site-packages\ultralytics\engine\predictor.py:257 in      │             │
    │ │ stream_inference                                                                                 │             │
    │ │                                                                                                  │             │
    │ │   254 │   │   │                                                                                  │             │
    │ │   255 │   │   │   # Postprocess                                                                  │             │
    │ │   256 │   │   │   with profilers[2]:                                                             │             │
    │ │ ❱ 257 │   │   │   │   self.results = self.postprocess(preds, im, im0s)                           │             │
    │ │   258 │   │   │   self.run_callbacks('on_predict_postprocess_end')                               │             │
    │ │   259 │   │   │                                                                                  │             │
    │ │   260 │   │   │   # Visualize, save, write results                                               │             │
    │ │                                                                                                  │             │
    │ │ D:\AI7\stable-diffusion-webui\venv\lib\site-packages\ultralytics\models\yolo\detect\predict.py:2 │             │
    │ │ 5 in postprocess                                                                                 │             │
    │ │                                                                                                  │             │
    │ │   22 │                                                                                           │             │
    │ │   23 │   def postprocess(self, preds, img, orig_imgs):                                           │             │
    │ │   24 │   │   """Post-processes predictions and returns a list of Results objects."""             │             │
    │ │ ❱ 25 │   │   preds = ops.non_max_suppression(preds,                                              │             │
    │ │   26 │   │   │   │   │   │   │   │   │   │   self.args.conf,                                     │             │
    │ │   27 │   │   │   │   │   │   │   │   │   │   self.args.iou,                                      │             │
    │ │   28 │   │   │   │   │   │   │   │   │   │   agnostic=self.args.agnostic_nms,                    │             │
    │ │                                                                                                  │             │
    │ │ D:\AI7\stable-diffusion-webui\venv\lib\site-packages\ultralytics\utils\ops.py:242 in             │             │
    │ │ non_max_suppression                                                                              │             │
    │ │                                                                                                  │             │
    │ │   239 │   │   # Batched NMS                                                                      │             │
    │ │   240 │   │   c = x[:, 5:6] * (0 if agnostic else max_wh)  # classes                             │             │
    │ │   241 │   │   boxes, scores = x[:, :4] + c, x[:, 4]  # boxes (offset by class), scores           │             │
    │ │ ❱ 242 │   │   i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS                           │             │
    │ │   243 │   │   i = i[:max_det]  # limit detections                                                │             │
    │ │   244 │   │                                                                                      │             │
    │ │   245 │   │   # # Experimental                                                                   │             │
    │ │                                                                                                  │             │
    │ │ D:\AI7\stable-diffusion-webui\venv\lib\site-packages\torchvision\ops\boxes.py:41 in nms          │             │
    │ │                                                                                                  │             │
    │ │    38 │   if not torch.jit.is_scripting() and not torch.jit.is_tracing():                        │             │
    │ │    39 │   │   _log_api_usage_once(nms)                                                           │             │
    │ │    40 │   _assert_has_ops()                                                                      │             │
    │ │ ❱  41 │   return torch.ops.torchvision.nms(boxes, scores, iou_threshold)                         │             │
    │ │    42                                                                                            │             │
    │ │    43                                                                                            │             │
    │ │    44 def batched_nms(                                                                           │             │
    │ │                                                                                                  │             │
    │ │ D:\AI7\stable-diffusion-webui\venv\lib\site-packages\torch\_ops.py:502 in __call__               │             │
    │ │                                                                                                  │             │
    │ │   499 │   │   # is still callable from JIT                                                       │             │
    │ │   500 │   │   # We save the function ptr as the `op` attribute on                                │             │
    │ │   501 │   │   # OpOverloadPacket to access it here.                                              │             │
    │ │ ❱ 502 │   │   return self._op(*args, **kwargs or {})                                             │             │
    │ │   503 │                                                                                          │             │
    │ │   504 │   # TODO: use this to make a __dir__                                                     │             │
    │ │   505 │   def overloads(self):                                                                   │             │
    │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯             │
    │ NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be      │
    │ because the operator doesn't exist for this backend, or was omitted during the selective/custom build process    │
    │ (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit                    │
    │ https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends:    │
    │ [CPU, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate,       │
    │ Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS,       │
    │ AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched,       │
    │ FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode,   │
    │ PythonDispatcher].                                                                                               │
    │                                                                                                                  │
    │ CPU: registered at C:\Users\circleci\project\torchvision\csrc\ops\cpu\nms_kernel.cpp:112 [kernel]                │
    │ QuantizedCPU: registered at C:\Users\circleci\project\torchvision\csrc\ops\quantized\cpu\qnms_kernel.cpp:124     │
    │ [kernel]                                                                                                         │
    │ BackendSelect: fallthrough registered at ..\aten\src\ATen\core\BackendSelectFallbackKernel.cpp:3 [backend        │
    │ fallback]                                                                                                        │
    │ Python: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:144 [backend fallback]                      │
    │ FuncTorchDynamicLayerBackMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:491 [backend fallback]  │
    │ Functionalize: registered at ..\aten\src\ATen\FunctionalizeFallbackKernel.cpp:280 [backend fallback]             │
    │ Named: registered at ..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]                           │
    │ Conjugate: registered at ..\aten\src\ATen\ConjugateFallback.cpp:17 [backend fallback]                            │
    │ Negative: registered at ..\aten\src\ATen\native\NegateFallback.cpp:19 [backend fallback]                         │
    │ ZeroTensor: registered at ..\aten\src\ATen\ZeroTensorFallback.cpp:86 [backend fallback]                          │
    │ ADInplaceOrView: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:63 [backend          │
    │ fallback]                                                                                                        │
    │ AutogradOther: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:30 [backend fallback]  │
    │ AutogradCPU: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:34 [backend fallback]    │
    │ AutogradCUDA: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:42 [backend fallback]   │
    │ AutogradXLA: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:46 [backend fallback]    │
    │ AutogradMPS: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:54 [backend fallback]    │
    │ AutogradXPU: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:38 [backend fallback]    │
    │ AutogradHPU: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:67 [backend fallback]    │
    │ AutogradLazy: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:50 [backend fallback]   │
    │ AutogradMeta: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:58 [backend fallback]   │
    │ Tracer: registered at ..\torch\csrc\autograd\TraceTypeManual.cpp:294 [backend fallback]                          │
    │ AutocastCPU: fallthrough registered at ..\aten\src\ATen\autocast_mode.cpp:487 [backend fallback]                 │
    │ AutocastCUDA: fallthrough registered at ..\aten\src\ATen\autocast_mode.cpp:354 [backend fallback]                │
    │ FuncTorchBatched: registered at ..\aten\src\ATen\functorch\LegacyBatchingRegistrations.cpp:815 [backend          │
    │ fallback]                                                                                                        │
    │ FuncTorchVmapMode: fallthrough registered at ..\aten\src\ATen\functorch\VmapModeRegistrations.cpp:28 [backend    │
    │ fallback]                                                                                                        │
    │ Batched: registered at ..\aten\src\ATen\LegacyBatchingRegistrations.cpp:1073 [backend fallback]                  │
    │ VmapMode: fallthrough registered at ..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]             │
    │ FuncTorchGradWrapper: registered at ..\aten\src\ATen\functorch\TensorWrapper.cpp:210 [backend fallback]          │
    │ PythonTLSSnapshot: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:152 [backend fallback]           │
    │ FuncTorchDynamicLayerFrontMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:487 [backend fallback] │
    │ PythonDispatcher: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:148 [backend fallback]            │
    │                                                                                                                  │
    ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


---
```

**Comment by LieDeath** [comment]
solved by using torch2.0.1+cu118 torchvision0.15.2+cu118

**Comment by Bing-su** [comment]
```sh
    │ │   Libraries │ {'torch': '2.0.0+cu118', 'torchvision': '0.15.1', 'ultralytics': '8.0.173', 'mediapipe':       │ │
    │ │             │ '0.10.3'}                                                                                      │ │
```
`'torchvision': '0.15.1'`

As your version information shows, you will have that problem if you do not install torchvision with CUDA support.
