### ISSUE TITLE
[Bug]: Conflict with controlnet. TypeError: UnetHook.restore() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by YD-River** [Bing-su/adetailer#337]
### Describe the bug

When I generate pictures while both adetailer and controlnet is active, as the generation is over, adetailer gets this error when detecting people in that image

### Console logs, from start to end.

```Shell
0: 640x448 2 persons, 27.9ms
Speed: 4.5ms preprocess, 27.9ms inference, 9.4ms postprocess per image at shape (1, 3, 640, 448)
*** Error running postprocess_image: /content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py
    Traceback (most recent call last):
      File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/modules/scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 560, in postprocess_image
        is_processed |= self._postprocess_image(p, pp, args, n=n)
      File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 529, in _postprocess_image
        cn_restore_unet_hook(p2, self.cn_latest_network)
      File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/adetailer/controlnet_ext/restore.py", line 11, in cn_restore_unet_hook
        cn_latest_network.restore(unet)
    TypeError: UnetHook.restore() takes 1 positional argument but 2 were given
```

### List of installed extensions

mainly controlnet in this case

**Comment by Bing-su** [comment]
That function was unused and I removed it completely in v23.7.10. Which version are you using?

**Comment by YD-River** [comment]
> That function was unused and I removed it completely in v23.7.10. Which version are you using?

Sorry, I forgot to upgrade... The problem has been solved
Thank you!
