### ISSUE TITLE
question

### ISSUE THREAD

**Issue by SimonY2** [Bing-su/adetailer#34]
there is an error when i install it,i want to know how to do with it :
Error loading script: !adetailer.py
Traceback (most recent call last):
  File "/root/autodl-tmp/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/root/autodl-tmp/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/adetailer-main/scripts/!adetailer.py", line 15, in <module>
    from adetailer import (
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/adetailer-main/adetailer/__init__.py", line 5, in <module>
    from .ultralytics import ultralytics_predict
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/adetailer-main/adetailer/ultralytics.py", line 59, in <module>
    def mask_to_pil(masks, shape: tuple[int, int]) -> list[Image.Image]:
TypeError: 'type' object is not subscriptable

**Comment by Bing-su** [comment]
This is an issue with python<=3.8 and I missed it, sorry.
