### ISSUE TITLE
What should I do to avoid this error?

### ISSUE THREAD

**Issue by luneS9999** [Bing-su/adetailer#35]
Error running postprocess_batch: /root/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py
Traceback (most recent call last):
  File "/root/stable-diffusion-webui/modules/scripts.py", line 462, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "/root/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 642, in postprocess_image
    is_processed |= self._postprocess_image(p, pp, args, n=n)
  File "/root/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 587, in _postprocess_image
    pred = predictor(ad_model, pp.image, args.ad_conf, **kwargs)
  File "/root/stable-diffusion-webui/extensions/adetailer/adetailer/ultralytics.py", line 25, in ultralytics_predict
    from ultralytics import YOLO
ModuleNotFoundError: No module named 'ultralytics'

**Comment by Bing-su** [comment]
This means that your installation steps were skipped in some way. Make sure there are no errors in the installation steps.
