### ISSUE TITLE
[Bug]: ADetailer aborts generation in both t2i and i2i if an Inpainting Model is used.

### ISSUE THREAD

**Issue by mariaWitch** [Bing-su/adetailer#357]
### Describe the bug

As title says, any model that is descended from the SD1.5 Inpainting model, appears to fail upon generation due to a tensor size mismatch error. However, this same error does not appear in normal generation in i2i with the same models. Additionally, I have tested and confirmed that this issue occurs even on the base v1.5 inpainting model. This could in theory be considered a critical issue as inpainting models provide significantly better inpainting performance over conventional v1.5 models, and this should be able to support the inpainting checkpoints at the very least on i2i.

### Console logs, from start to end.

```Shell
################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on maria user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Using TCMalloc: libtcmalloc_minimal.so.4
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Version: v1.6.0-209-g7d60076b
Commit hash: 7d60076b8b275771a1aa98f017aff845ef68d964
Launching Web UI with arguments: --xformers --opt-channelslast
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 23.10.0, num models: 9
Loading FABRIC v0.6.3
Loading weights [aa57ce0249] from /home/maria/stable-diffusion/stable-diffusion-webui/models/Stable-diffusion/Aurora-inpainting.inpainting.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: /home/maria/stable-diffusion/stable-diffusion-webui/configs/v1-inpainting-inference.yaml
[Lobe]: Initializing Lobe
Startup time: 12.5s (prepare environment: 2.8s, import torch: 2.2s, import gradio: 1.0s, setup paths: 1.3s, initialize shared: 0.6s, other imports: 0.6s, setup codeformer: 0.2s, load scripts: 0.7s, create ui: 0.4s, gradio launch: 2.7s).
Loading VAE weights specified in settings: /home/maria/stable-diffusion/stable-diffusion-webui/models/VAE/kl-f8-anime2.ckpt
Applying attention optimization: xformers... done.
Model loaded in 7.8s (load weights from disk: 0.8s, create model: 0.2s, apply weights to model: 4.6s, load VAE: 0.6s, calculate empty prompt: 1.5s).
100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:06<00:00,  6.65s/it]
Total progress: 2it [00:35, 17.73s/it]
0: 640x640 1 face, 4.5ms
Speed: 7.0ms preprocess, 4.5ms inference, 3.4ms postprocess per image at shape (1, 3, 640, 640)
  6%|████▎                                                                     | 1/17 [00:07<01:56,  7.28s/it]
*** Error running postprocess_image: /home/maria/stable-diffusion/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py
    Traceback (most recent call last):
      File "/home/maria/stable-diffusion/stable-diffusion-webui/modules/scripts.py", line 679, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "/home/maria/stable-diffusion/stable-diffusion-webui/extensions/adetailer/adetailer/traceback.py", line 159, in wrapper
        raise error from None
    RuntimeError:
    ╭────────────────────────────────────────────────────────────────────────────────────────────────────────╮
    │                                              System info                                               │
    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃             ┃ Value                                                                                ┃ │
    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │    Platform │ Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35                        │ │
    │ │      Python │ 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]                                   │ │
    │ │     Version │ v1.6.0-209-g7d60076b                                                                 │ │
    │ │      Commit │ 7d60076b8b275771a1aa98f017aff845ef68d964                                             │ │
    │ │ Commandline │ ['launch.py', '--xformers', '--opt-channelslast']                                    │ │
    │ │   Libraries │ {'torch': '2.0.1+cu118', 'torchvision': '0.15.2+cu118', 'ultralytics': '8.0.195',    │ │
    │ │             │ 'mediapipe': '0.10.5'}                                                               │ │
    │ └─────────────┴──────────────────────────────────────────────────────────────────────────────────────┘ │
    │                                                 Inputs                                                 │
    │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃                 ┃ Value                                                                            ┃ │
    │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │          prompt │ ((1990s \(style\), retro artstyle)), (SLE, mksks style), moody lighting, dimly   │ │
    │ │                 │ lit, sidelighting, backlighting, masterpiece, best quality, detailed background, │ │
    │ │                 │ scenery, 1girl, sitting, BREAK ouro kronii, dark blue                            │ │
    │ │                 │ hair,hair intakes, headband, dark blue eyes, hololive, 	                   │ │
    │ │                 │ BREAK restaurant, doughnut shop, cafe, <lora:lighting-locon:0.6>,                │ │
    │ │ negative_prompt │ (KHFB, AuroraNegative), (Worst Quality, Low Quality:1.4), (depth of field,       │ │
    │ │                 │ bokeh, blurry:1.4), (multiple_girls:1.2), (multiple views, comic, reference      │ │
    │ │                 │ sheet), border, nsfw, skimpy, grayscale, umbrella, loli, motion lines, error,    │ │
    │ │                 │ bad anatomy                                                                      │ │
    │ │                 │                                                                                  │ │
    │ │          n_iter │ 1                                                                                │ │
    │ │      batch_size │ 1                                                                                │ │
    │ │           width │ 2304                                                                             │ │
    │ │          height │ 2304                                                                             │ │
    │ │    sampler_name │ DPM++ 2M Karras                                                                  │ │
    │ │       enable_hr │ False                                                                            │ │
    │ │     hr_upscaler │                                                                                  │ │
    │ │      checkpoint │ Aurora-inpainting.inpainting.safetensors                                         │ │
    │ │             vae │ kl-f8-anime2.ckpt                                                                │ │
    │ │            unet │ Automatic                                                                        │ │
    │ └─────────────────┴──────────────────────────────────────────────────────────────────────────────────┘ │
    │                 ADetailer                                                                              │
    │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓                                                              │
    │ ┃                     ┃ Value           ┃                                                              │
    │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩                                                              │
    │ │             version │ 23.10.0         │                                                              │
    │ │            ad_model │ face_yolov8n.pt │                                                              │
    │ │           ad_prompt │                 │                                                              │
    │ │  ad_negative_prompt │                 │                                                              │
    │ │ ad_controlnet_model │ None            │                                                              │
    │ │              is_api │ False           │                                                              │
    │ └─────────────────────┴─────────────────┘                                                              │
    │ ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/extensions/adetailer/adetailer/traceback.py: │   │
    │ │ 139 in wrapper                                                                                   │   │
    │ │                                                                                                  │   │
    │ │   136 │   │   width = width - 4 if width > 4 else None                                           │   │
    │ │   137 │   │   console = Console(file=string, width=width)                                        │   │
    │ │   138 │   │   try:                                                                               │   │
    │ │ ❱ 139 │   │   │   return func(*args, **kwargs)                                                   │   │
    │ │   140 │   │   except Exception as e:                                                             │   │
    │ │   141 │   │   │   tables = [                                                                     │   │
    │ │   142 │   │   │   │   get_table(title, data)                                                     │   │
    │ │                                                                                                  │   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py:7 │   │
    │ │ 03 in postprocess_image                                                                          │   │
    │ │                                                                                                  │   │
    │ │   700 │   │   │   for n, args in enumerate(arg_list):                                            │   │
    │ │   701 │   │   │   │   if args.ad_model == "None":                                                │   │
    │ │   702 │   │   │   │   │   continue                                                               │   │
    │ │ ❱ 703 │   │   │   │   is_processed |= self._postprocess_image_inner(p, pp, args, n=n)            │   │
    │ │   704 │   │                                                                                      │   │
    │ │   705 │   │   if is_processed and not getattr(p, "_ad_skip_img2img", False):                     │   │
    │ │   706 │   │   │   self.save_image(                                                               │   │
    │ │                                                                                                  │   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py:6 │   │
    │ │ 66 in _postprocess_image_inner                                                                   │   │
    │ │                                                                                                  │   │
    │ │   663 │   │   │   p2.subseed = subseed + j                                                       │   │
    │ │   664 │   │   │                                                                                  │   │
    │ │   665 │   │   │   try:                                                                           │   │
    │ │ ❱ 666 │   │   │   │   processed = process_images(p2)                                             │   │
    │ │   667 │   │   │   except NansException as e:                                                     │   │
    │ │   668 │   │   │   │   msg = f"[-] ADetailer: 'NansException' occurred with {ordinal(n + 1)} se   │   │
    │ │   669 │   │   │   │   print(msg, file=sys.stderr)                                                │   │
    │ │                                                                                                  │   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/modules/processing.py:734 in process_images  │   │
    │ │                                                                                                  │   │
    │ │    731 │   │                                                                                     │   │
    │ │    732 │   │   sd_models.apply_token_merging(p.sd_model, p.get_token_merging_ratio())            │   │
    │ │    733 │   │                                                                                     │   │
    │ │ ❱  734 │   │   res = process_images_inner(p)                                                     │   │
    │ │    735 │                                                                                         │   │
    │ │    736 │   finally:                                                                              │   │
    │ │    737 │   │   sd_models.apply_token_merging(p.sd_model, 0)                                      │   │
    │ │                                                                                                  │   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/modules/processing.py:869 in                 │   │
    │ │ process_images_inner                                                                             │   │
    │ │                                                                                                  │   │
    │ │    866 │   │   │   │   shared.state.job = f"Batch {n+1} out of {p.n_iter}"                       │   │
    │ │    867 │   │   │                                                                                 │   │
    │ │    868 │   │   │   with devices.without_autocast() if devices.unet_needs_upcast else devices.au  │   │
    │ │ ❱  869 │   │   │   │   samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.u  │   │
    │ │    870 │   │   │                                                                                 │   │
    │ │    871 │   │   │   if getattr(samples_ddim, 'already_decoded', False):                           │   │
    │ │    872 │   │   │   │   x_samples_ddim = samples_ddim                                             │   │
    │ │                                                                                                  │   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/modules/processing.py:1530 in sample         │   │
    │ │                                                                                                  │   │
    │ │   1527 │   │   │   self.extra_generation_params["Noise multiplier"] = self.initial_noise_multip  │   │
    │ │   1528 │   │   │   x *= self.initial_noise_multiplier                                            │   │
    │ │   1529 │   │                                                                                     │   │
    │ │ ❱ 1530 │   │   samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, u  │   │
    │ │   1531 │   │                                                                                     │   │
    │ │   1532 │   │   if self.mask is not None:                                                         │   │
    │ │   1533 │   │   │   samples = samples * self.nmask + self.init_latent * self.mask                 │   │
    │ │                                                                                                  │   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py:188 in     │   │
    │ │ sample_img2img                                                                                   │   │
    │ │                                                                                                  │   │
    │ │   185 │   │   │   's_min_uncond': self.s_min_uncond                                              │   │
    │ │   186 │   │   }                                                                                  │   │
    │ │   187 │   │                                                                                      │   │
    │ │ ❱ 188 │   │   samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg,   │   │
    │ │   189 │   │                                                                                      │   │
    │ │   190 │   │   if self.model_wrap_cfg.padded_cond_uncond:                                         │   │
    │ │   191 │   │   │   p.extra_generation_params["Pad conds"] = True                                  │   │
    │ │                                                                                                  │   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_common.py:261 in         │   │
    │ │ launch_sampling                                                                                  │   │
    │ │                                                                                                  │   │
    │ │   258 │   │   state.sampling_step = 0                                                            │   │
    │ │   259 │   │                                                                                      │   │
    │ │   260 │   │   try:                                                                               │   │
    │ │ ❱ 261 │   │   │   return func()                                                                  │   │
    │ │   262 │   │   except RecursionError:                                                             │   │
    │ │   263 │   │   │   print(                                                                         │   │
    │ │   264 │   │   │   │   'Encountered RecursionError during sampling, returning last latent. '      │   │
    │ │                                                                                                  │   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py:188 in     │   │
    │ │ <lambda>                                                                                         │   │
    │ │                                                                                                  │   │
    │ │   185 │   │   │   's_min_uncond': self.s_min_uncond                                              │   │
    │ │   186 │   │   }                                                                                  │   │
    │ │   187 │   │                                                                                      │   │
    │ │ ❱ 188 │   │   samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg,   │   │
    │ │   189 │   │                                                                                      │   │
    │ │   190 │   │   if self.model_wrap_cfg.padded_cond_uncond:                                         │   │
    │ │   191 │   │   │   p.extra_generation_params["Pad conds"] = True                                  │   │
    │ │                                                                                                  │   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/util │   │
    │ │ s/_contextlib.py:115 in decorate_context                                                         │   │
    │ │                                                                                                  │   │
    │ │   112 │   @functools.wraps(func)                                                                 │   │
    │ │   113 │   def decorate_context(*args, **kwargs):                                                 │   │
    │ │   114 │   │   with ctx_factory():                                                                │   │
    │ │ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │   │
    │ │   116 │                                                                                          │   │
    │ │   117 │   return decorate_context                                                                │   │
    │ │   118                                                                                            │   │
    │ │                                                                                                  │   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/samplin │   │
    │ │ g.py:594 in sample_dpmpp_2m                                                                      │   │
    │ │                                                                                                  │   │
    │ │   591 │   old_denoised = None                                                                    │   │
    │ │   592 │                                                                                          │   │
    │ │   593 │   for i in trange(len(sigmas) - 1, disable=disable):                                     │   │
    │ │ ❱ 594 │   │   denoised = model(x, sigmas[i] * s_in, **extra_args)                                │   │
    │ │   595 │   │   if callback is not None:                                                           │   │
    │ │   596 │   │   │   callback({'x': x, 'i': i, 'sigma': sigmas[i], 'sigma_hat': sigmas[i], 'denoi   │   │
    │ │   597 │   │   t, t_next = t_fn(sigmas[i]), t_fn(sigmas[i + 1])                                   │   │
    │ │                                                                                                  │   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/m │   │
    │ │ odules/module.py:1501 in _call_impl                                                              │   │
    │ │                                                                                                  │   │
    │ │   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │   │
    │ │   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │   │
    │ │   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │   │
    │ │ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │   │
    │ │   1502 │   │   # Do not call functions when jit is used                                          │   │
    │ │   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │   │
    │ │   1504 │   │   backward_pre_hooks = []                                                           │   │
    │ │                                                                                                  │   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_cfg_denoiser.py:169 in   │   │
    │ │ forward                                                                                          │   │
    │ │                                                                                                  │   │
    │ │   166 │   │   │   │   cond_in = catenate_conds([tensor, uncond])                                 │   │
    │ │   167 │   │   │                                                                                  │   │
    │ │   168 │   │   │   if shared.opts.batch_cond_uncond:                                              │   │
    │ │ ❱ 169 │   │   │   │   x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict(cond_i   │   │
    │ │   170 │   │   │   else:                                                                          │   │
    │ │   171 │   │   │   │   x_out = torch.zeros_like(x_in)                                             │   │
    │ │   172 │   │   │   │   for batch_offset in range(0, x_out.shape[0], batch_size):                  │   │
    │ │                                                                                                  │   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/m │   │
    │ │ odules/module.py:1501 in _call_impl                                                              │   │
    │ │                                                                                                  │   │
    │ │   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │   │
    │ │   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │   │
    │ │   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │   │
    │ │ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │   │
    │ │   1502 │   │   # Do not call functions when jit is used                                          │   │
    │ │   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │   │
    │ │   1504 │   │   backward_pre_hooks = []                                                           │   │
    │ │                                                                                                  │   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/externa │   │
    │ │ l.py:112 in forward                                                                              │   │
    │ │                                                                                                  │   │
    │ │   109 │                                                                                          │   │
    │ │   110 │   def forward(self, input, sigma, **kwargs):                                             │   │
    │ │   111 │   │   c_out, c_in = [utils.append_dims(x, input.ndim) for x in self.get_scalings(sigma   │   │
    │ │ ❱ 112 │   │   eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)                 │   │
    │ │   113 │   │   return input + eps * c_out                                                         │   │
    │ │   114                                                                                            │   │
    │ │   115                                                                                            │   │
    │ │                                                                                                  │   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/externa │   │
    │ │ l.py:138 in get_eps                                                                              │   │
    │ │                                                                                                  │   │
    │ │   135 │   │   super().__init__(model, model.alphas_cumprod, quantize=quantize)                   │   │
    │ │   136 │                                                                                          │   │
    │ │   137 │   def get_eps(self, *args, **kwargs):                                                    │   │
    │ │ ❱ 138 │   │   return self.inner_model.apply_model(*args, **kwargs)                               │   │
    │ │   139                                                                                            │   │
    │ │   140                                                                                            │   │
    │ │   141 class DiscreteVDDPMDenoiser(DiscreteSchedule):                                             │   │
    │ │                                                                                                  │   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/modules/sd_hijack_utils.py:17 in <lambda>    │   │
    │ │                                                                                                  │   │
    │ │   14 │   │   │   for attr_name in func_path[i:-1]:                                               │   │
    │ │   15 │   │   │   │   resolved_obj = getattr(resolved_obj, attr_name)                             │   │
    │ │   16 │   │   │   orig_func = getattr(resolved_obj, func_path[-1])                                │   │
    │ │ ❱ 17 │   │   │   setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **k    │   │
    │ │   18 │   │   self.__init__(orig_func, sub_func, cond_func)                                       │   │
    │ │   19 │   │   return lambda *args, **kwargs: self(*args, **kwargs)                                │   │
    │ │   20 │   def __init__(self, orig_func, sub_func, cond_func):                                     │   │
    │ │                                                                                                  │   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/modules/sd_hijack_utils.py:28 in __call__    │   │
    │ │                                                                                                  │   │
    │ │   25 │   │   if not self.__cond_func or self.__cond_func(self.__orig_func, *args, **kwargs):     │   │
    │ │   26 │   │   │   return self.__sub_func(self.__orig_func, *args, **kwargs)                       │   │
    │ │   27 │   │   else:                                                                               │   │
    │ │ ❱ 28 │   │   │   return self.__orig_func(*args, **kwargs)                                        │   │
    │ │   29                                                                                             │   │
    │ │                                                                                                  │   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/l │   │
    │ │ dm/models/diffusion/ddpm.py:858 in apply_model                                                   │   │
    │ │                                                                                                  │   │
    │ │    855 │   │   │   key = 'c_concat' if self.model.conditioning_key == 'concat' else 'c_crossatt  │   │
    │ │    856 │   │   │   cond = {key: cond}                                                            │   │
    │ │    857 │   │                                                                                     │   │
    │ │ ❱  858 │   │   x_recon = self.model(x_noisy, t, **cond)                                          │   │
    │ │    859 │   │                                                                                     │   │
    │ │    860 │   │   if isinstance(x_recon, tuple) and not return_ids:                                 │   │
    │ │    861 │   │   │   return x_recon[0]                                                             │   │
    │ │                                                                                                  │   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/m │   │
    │ │ odules/module.py:1501 in _call_impl                                                              │   │
    │ │                                                                                                  │   │
    │ │   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │   │
    │ │   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │   │
    │ │   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │   │
    │ │ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │   │
    │ │   1502 │   │   # Do not call functions when jit is used                                          │   │
    │ │   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │   │
    │ │   1504 │   │   backward_pre_hooks = []                                                           │   │
    │ │                                                                                                  │   │
    │ │ /home/maria/stable-diffusion/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/l │   │
    │ │ dm/models/diffusion/ddpm.py:1337 in forward                                                      │   │
    │ │                                                                                                  │   │
    │ │   1334 │   │   │   else:                                                                         │   │
    │ │   1335 │   │   │   │   out = self.diffusion_model(x, t, context=cc)                              │   │
    │ │   1336 │   │   elif self.conditioning_key == 'hybrid':                                           │   │
    │ │ ❱ 1337 │   │   │   xc = torch.cat([x] + c_concat, dim=1)                                         │   │
    │ │   1338 │   │   │   cc = torch.cat(c_crossattn, 1)                                                │   │
    │ │   1339 │   │   │   out = self.diffusion_model(xc, t, context=cc)                                 │   │
    │ │   1340 │   │   elif self.conditioning_key == 'hybrid-adm':                                       │   │
    │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯   │
    │ RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 1 but got size 2 for    │
    │ tensor number 1 in the list.                                                                           │
    ╰────────────────────────────────────────────────────────────────────────────────────────────────────────╯


---
Total progress: 2it [01:04, 32.31s/it]
Total progress: 2it [01:04, 17.73s/it]
```

### List of installed extensions

![image](https://github.com/Bing-su/adetailer/assets/77745122/743229c7-0dfe-4c50-9ce9-f1144c94dcae)

**Comment by mariaWitch** [comment]
This appears to be an upstream issue. Closing for now.
