### ISSUE TITLE
[Bug]: Doesn't work on RunPod

### ISSUE THREAD

**Issue by Seryogerr** [Bing-su/adetailer#363]
### Describe the bug

Hello, help me with RunPod please :)
Extension doesn't work on RunPod by default 
I try to host a new pod and nothing change
I attach the log: host pod -> install AD -> try generate :(

I find in storage noticed missing files compared to my local version
I tried to add them manually, I started with the sd_webui folder, but for some reason RunPod refuses to create a folder named __pycache__, as well as accept .pyc files

Used RTX 3090 
version: [v1.6.0]  •  python: 3.10.12  •  torch: 2.0.1+cu118  •  xformers: 0.0.21  •  gradio: 3.41.2  •  checkpoint: [dd6c6f3f83]

### Screenshots

![RunPod AD](https://github.com/Bing-su/adetailer/assets/147452692/f8c7e477-d830-4d9e-8623-893539c0b955)
<img width="527" alt="local AD" src="https://github.com/Bing-su/adetailer/assets/147452692/95fe0a9f-7314-437a-8b2c-1371ccefcf10">

### Console logs, from start to end.

```Shell
2023-10-15T01:34:44.514288986+02:00

2023-10-15T01:34:44.514462851+02:00 ==========

2023-10-15T01:34:44.514484601+02:00 == CUDA ==

2023-10-15T01:34:44.514644266+02:00 ==========

2023-10-15T01:34:44.518772633+02:00

2023-10-15T01:34:44.518792874+02:00 CUDA Version 11.8.0

2023-10-15T01:34:44.520091607+02:00

2023-10-15T01:34:44.520099997+02:00 Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

2023-10-15T01:34:44.521369830+02:00

2023-10-15T01:34:44.521376930+02:00 This container image and its contents are governed by the NVIDIA Deep Learning Container License.

2023-10-15T01:34:44.521383141+02:00 By pulling and using the container, you accept the terms and conditions of this license:

2023-10-15T01:34:44.521386541+02:00 https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

2023-10-15T01:34:44.521389701+02:00

2023-10-15T01:34:44.521392481+02:00 A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

2023-10-15T01:34:44.537519399+02:00

2023-10-15T01:34:44.537841968+02:00 Starting Nginx service...

2023-10-15T01:34:44.555988058+02:00 * Starting nginx nginx

2023-10-15T01:34:44.559154660+02:00 ...done.

2023-10-15T01:34:44.559500139+02:00 Running pre-start script...

2023-10-15T01:34:44.561102861+02:00 **** syncing venv to workspace, please wait. This could take a while on first startup! ****

2023-10-15T01:35:03.536324555+02:00 **** syncing stable diffusion to workspace, please wait ****

2023-10-15T01:35:06.034119633+02:00 Started webui through relauncher script

2023-10-15T01:35:06.034886633+02:00 Pod Started

2023-10-15T01:35:06.034906923+02:00 Setting up SSH...

2023-10-15T01:35:06.057669344+02:00 * Starting OpenBSD Secure Shell server sshd

2023-10-15T01:35:06.061436962+02:00

2023-10-15T01:35:06.061453282+02:00 ################################################################

2023-10-15T01:35:06.061456902+02:00 Install script for stable-diffusion + Web UI

2023-10-15T01:35:06.061460102+02:00 Tested on Debian 11 (Bullseye)

2023-10-15T01:35:06.061463262+02:00 ################################################################

2023-10-15T01:35:06.063842834+02:00

2023-10-15T01:35:06.063865135+02:00 ################################################################

2023-10-15T01:35:06.065210460+02:00 Running on root user

2023-10-15T01:35:06.065221850+02:00 ################################################################

2023-10-15T01:35:06.066564155+02:00 ...done.

2023-10-15T01:35:06.067054648+02:00 Starting Jupyter Lab...

2023-10-15T01:35:06.067301394+02:00 Jupyter Lab started

2023-10-15T01:35:06.067314274+02:00 Exporting environment variables...

2023-10-15T01:35:06.067394177+02:00

2023-10-15T01:35:06.067398107+02:00 ################################################################

2023-10-15T01:35:06.067438858+02:00 Repo already cloned, using it as install directory

2023-10-15T01:35:06.067454328+02:00 ################################################################

2023-10-15T01:35:06.112320052+02:00

2023-10-15T01:35:06.112338552+02:00 ################################################################

2023-10-15T01:35:06.112342762+02:00 Create and activate python venv

2023-10-15T01:35:06.112346213+02:00 ################################################################

2023-10-15T01:35:06.113140073+02:00

2023-10-15T01:35:06.113153904+02:00 ################################################################

2023-10-15T01:35:06.113158634+02:00 Launching launch.py...

2023-10-15T01:35:06.113163404+02:00 ################################################################

2023-10-15T01:35:06.117006513+02:00 Using TCMalloc: libtcmalloc_minimal.so.4

2023-10-15T01:35:06.186465965+02:00 Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

2023-10-15T01:35:06.186486276+02:00 Version: v1.6.0

2023-10-15T01:35:06.186490486+02:00 Commit hash: 5ef669de080814067961f28357256e8fe27544f4

2023-10-15T01:35:08.029530418+02:00 Launching Web UI with arguments: -f --port 3000 --xformers --skip-install --listen --enable-insecure-extension-access

2023-10-15T01:35:14.388789100+02:00 2023-10-14 23:35:14,388 - ControlNet - INFO - ControlNet v1.1.313

2023-10-15T01:35:14.391720486+02:00 ControlNet preprocessor location: /workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads

2023-10-15T01:35:14.498798794+02:00 2023-10-14 23:35:14,498 - ControlNet - INFO - ControlNet v1.1.313

2023-10-15T01:35:15.073006989+02:00 Calculating sha256 for /workspace/stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_1.0.safetensors: *Deforum ControlNet support: enabled*

2023-10-15T01:35:15.676518186+02:00 Running on local URL: http://0.0.0.0:3000

2023-10-15T01:35:15.712480098+02:00

2023-10-15T01:35:15.712519909+02:00 To create a public link, set `share=True` in `launch()`.

2023-10-15T01:35:15.727974391+02:00 Startup time: 9.6s (prepare environment: 1.9s, import torch: 2.9s, import gradio: 1.1s, setup paths: 0.8s, initialize shared: 0.2s, other imports: 0.7s, load scripts: 0.9s, create ui: 0.9s, gradio launch: 0.1s).

2023-10-15T01:35:22.002222617+02:00 31e35c80fc4829d14f90153f4c74cd59c90b779f6afe05a74cd6120b893f7e5b

2023-10-15T01:35:22.002572836+02:00 Loading weights [31e35c80fc] from /workspace/stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_1.0.safetensors

2023-10-15T01:35:22.710003518+02:00 Creating model from config: /workspace/stable-diffusion-webui/repositories/generative-models/configs/inference/sd_xl_base.yaml

2023-10-15T01:35:23.317002665+02:00

Downloading (…)olve/main/vocab.json: 0%| | 0.00/961k [00:00<?, ?B/s]

Downloading (…)olve/main/vocab.json: 100%|██████████| 961k/961k [00:00<00:00, 6.03MB/s]

Downloading (…)olve/main/vocab.json: 100%|██████████| 961k/961k [00:00<00:00, 6.00MB/s]

2023-10-15T01:35:23.795160339+02:00

Downloading (…)olve/main/merges.txt: 0%| | 0.00/525k [00:00<?, ?B/s]

Downloading (…)olve/main/merges.txt: 100%|██████████| 525k/525k [00:00<00:00, 2.09MB/s]

Downloading (…)olve/main/merges.txt: 100%|██████████| 525k/525k [00:00<00:00, 2.08MB/s]

2023-10-15T01:35:24.015620408+02:00

Downloading (…)cial_tokens_map.json: 0%| | 0.00/389 [00:00<?, ?B/s]

Downloading (…)cial_tokens_map.json: 100%|██████████| 389/389 [00:00<00:00, 2.37MB/s]

2023-10-15T01:35:24.232245788+02:00

Downloading (…)okenizer_config.json: 0%| | 0.00/905 [00:00<?, ?B/s]

Downloading (…)okenizer_config.json: 100%|██████████| 905/905 [00:00<00:00, 5.71MB/s]

2023-10-15T01:35:24.504598263+02:00

Downloading (…)lve/main/config.json: 0%| | 0.00/4.52k [00:00<?, ?B/s]

Downloading (…)lve/main/config.json: 100%|██████████| 4.52k/4.52k [00:00<00:00, 22.2MB/s]

2023-10-15T01:35:26.650678337+02:00 Applying attention optimization: xformers... done.

2023-10-15T01:35:26.829297011+02:00 Model loaded in 12.1s (calculate hash: 7.3s, load weights from disk: 0.7s, create model: 2.2s, apply weights to model: 1.6s, calculate empty prompt: 0.1s).

2023-10-15T01:40:04.979021721+02:00

2023-10-15T01:40:04.979054302+02:00 ################################################################

2023-10-15T01:40:04.979059372+02:00 Launching launch.py...

2023-10-15T01:40:04.979063292+02:00 ################################################################

2023-10-15T01:40:05.040622609+02:00 Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

2023-10-15T01:40:05.040645279+02:00 Version: v1.6.0

2023-10-15T01:40:05.040651219+02:00 Commit hash: 5ef669de080814067961f28357256e8fe27544f4

2023-10-15T01:40:06.900311523+02:00 Launching Web UI with arguments: -f --port 3000 --xformers --skip-install --listen --enable-insecure-extension-access

2023-10-15T01:40:13.101409782+02:00

Downloading face_yolov8n.pt: 0%| | 0.00/6.21M [00:00<?, ?B/s]

Downloading face_yolov8n.pt: 100%|██████████| 6.21M/6.21M [00:00<00:00, 58.5MB/s]

Downloading face_yolov8n.pt: 100%|██████████| 6.21M/6.21M [00:00<00:00, 56.5MB/s]

2023-10-15T01:40:13.420344155+02:00

Downloading face_yolov8s.pt: 0%| | 0.00/22.5M [00:00<?, ?B/s]

Downloading face_yolov8s.pt: 93%|█████████▎| 21.0M/22.5M [00:00<00:00, 118MB/s]

Downloading face_yolov8s.pt: 100%|██████████| 22.5M/22.5M [00:00<00:00, 117MB/s]

2023-10-15T01:40:13.767976224+02:00

Downloading hand_yolov8n.pt: 0%| | 0.00/6.22M [00:00<?, ?B/s]

Downloading hand_yolov8n.pt: 100%|██████████| 6.22M/6.22M [00:00<00:00, 110MB/s]

2023-10-15T01:40:13.954363779+02:00

Downloading person_yolov8n-seg.pt: 0%| | 0.00/6.75M [00:00<?, ?B/s]

Downloading person_yolov8n-seg.pt: 100%|██████████| 6.75M/6.75M [00:00<00:00, 112MB/s]

2023-10-15T01:40:14.286866084+02:00

Downloading person_yolov8s-seg.pt: 0%| | 0.00/23.8M [00:00<?, ?B/s]

Downloading person_yolov8s-seg.pt: 88%|████████▊ | 21.0M/23.8M [00:00<00:00, 118MB/s]

Downloading person_yolov8s-seg.pt: 100%|██████████| 23.8M/23.8M [00:00<00:00, 117MB/s]

2023-10-15T01:40:14.292786208+02:00 [-] ADetailer initialized. version: 23.10.0, num models: 9

2023-10-15T01:40:14.872681132+02:00 2023-10-14 23:40:14,872 - ControlNet - INFO - ControlNet v1.1.313

2023-10-15T01:40:14.875582247+02:00 ControlNet preprocessor location: /workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads

2023-10-15T01:40:14.979729489+02:00 2023-10-14 23:40:14,979 - ControlNet - INFO - ControlNet v1.1.313

2023-10-15T01:40:15.196302427+02:00 Loading weights [31e35c80fc] from /workspace/stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_1.0.safetensors

2023-10-15T01:40:16.065263650+02:00 *Deforum ControlNet support: enabled*

2023-10-15T01:40:16.847341768+02:00 Running on local URL: http://0.0.0.0:3000

2023-10-15T01:40:16.927729144+02:00

2023-10-15T01:40:16.927745954+02:00 To create a public link, set `share=True` in `launch()`.

2023-10-15T01:40:16.941579123+02:00 Startup time: 11.9s (prepare environment: 1.9s, import torch: 2.8s, import gradio: 1.1s, setup paths: 0.8s, initialize shared: 0.2s, other imports: 0.8s, load scripts: 2.6s, create ui: 1.3s, gradio launch: 0.3s).

2023-10-15T01:40:17.096079681+02:00 Creating model from config: /workspace/stable-diffusion-webui/repositories/generative-models/configs/inference/sd_xl_base.yaml

2023-10-15T01:40:20.248534222+02:00 Applying attention optimization: xformers... done.

2023-10-15T01:40:20.430998426+02:00 Model loaded in 5.2s (load weights from disk: 1.9s, create model: 0.5s, apply weights to model: 2.5s, calculate empty prompt: 0.1s).

2023-10-15T01:44:24.897257612+02:00 Downloading VAEApprox model to: /workspace/stable-diffusion-webui/models/VAE-approx/vaeapprox-sdxl.pt

2023-10-15T01:44:25.519663928+02:00

0%| | 0.00/209k [00:00<?, ?B/s]

80%|████████ | 168k/209k [00:00<00:00, 1.68MB/s]

100%|██████████| 209k/209k [00:00<00:00, 1.92MB/s]

2023-10-15T01:44:26.103022952+02:00

2023-10-15T01:44:26.367479752+02:00

Total progress: 0%| | 0/20 [00:00<?, ?it/s]

2023-10-15T01:44:26.632336483+02:00

Total progress: 10%|█ | 2/20 [00:00<00:02, 7.57it/s]

2023-10-15T01:44:26.897637996+02:00

Total progress: 15%|█▌ | 3/20 [00:00<00:03, 5.33it/s]

2023-10-15T01:44:27.164752295+02:00

Total progress: 20%|██ | 4/20 [00:00<00:03, 4.62it/s]

2023-10-15T01:44:27.430029587+02:00

Total progress: 25%|██▌ | 5/20 [00:01<00:03, 4.27it/s]

2023-10-15T01:44:27.695318589+02:00

Total progress: 30%|███ | 6/20 [00:01<00:03, 4.09it/s]

2023-10-15T01:44:27.961122004+02:00

Total progress: 35%|███▌ | 7/20 [00:01<00:03, 3.98it/s]

2023-10-15T01:44:28.227713290+02:00

Total progress: 40%|████ | 8/20 [00:01<00:03, 3.91it/s]

2023-10-15T01:44:28.493835484+02:00

Total progress: 45%|████▌ | 9/20 [00:02<00:02, 3.86it/s]

2023-10-15T01:44:28.759294631+02:00

Total progress: 50%|█████ | 10/20 [00:02<00:02, 3.83it/s]

2023-10-15T01:44:29.025677151+02:00

Total progress: 55%|█████▌ | 11/20 [00:02<00:02, 3.81it/s]

2023-10-15T01:44:29.296296931+02:00

Total progress: 60%|██████ | 12/20 [00:02<00:02, 3.79it/s]

2023-10-15T01:44:29.565266289+02:00

Total progress: 65%|██████▌ | 13/20 [00:03<00:01, 3.76it/s]

2023-10-15T01:44:29.830677364+02:00

Total progress: 70%|███████ | 14/20 [00:03<00:01, 3.75it/s]

2023-10-15T01:44:30.097365613+02:00

Total progress: 75%|███████▌ | 15/20 [00:03<00:01, 3.75it/s]

2023-10-15T01:44:30.364474482+02:00

Total progress: 80%|████████ | 16/20 [00:03<00:01, 3.75it/s]

2023-10-15T01:44:30.630367580+02:00

Total progress: 85%|████████▌ | 17/20 [00:04<00:00, 3.75it/s]

2023-10-15T01:44:30.897758097+02:00

Total progress: 90%|█████████ | 18/20 [00:04<00:00, 3.75it/s]

2023-10-15T01:44:31.165830071+02:00

Total progress: 95%|█████████▌| 19/20 [00:04<00:00, 3.75it/s]

2023-10-15T01:44:31.166223311+02:00

0%| | 0/20 [00:00<?, ?it/s]

5%|▌ | 1/20 [00:00<00:09, 2.05it/s]

10%|█ | 2/20 [00:00<00:06, 2.80it/s]

15%|█▌ | 3/20 [00:01<00:05, 3.18it/s]

20%|██ | 4/20 [00:01<00:04, 3.39it/s]

25%|██▌ | 5/20 [00:01<00:04, 3.51it/s]

30%|███ | 6/20 [00:01<00:03, 3.59it/s]

35%|███▌ | 7/20 [00:02<00:03, 3.65it/s]

40%|████ | 8/20 [00:02<00:03, 3.68it/s]

45%|████▌ | 9/20 [00:02<00:02, 3.70it/s]

50%|█████ | 10/20 [00:02<00:02, 3.72it/s]

55%|█████▌ | 11/20 [00:03<00:02, 3.73it/s]

60%|██████ | 12/20 [00:03<00:02, 3.74it/s]

65%|██████▌ | 13/20 [00:03<00:01, 3.72it/s]

70%|███████ | 14/20 [00:03<00:01, 3.73it/s]

75%|███████▌ | 15/20 [00:04<00:01, 3.74it/s]

80%|████████ | 16/20 [00:04<00:01, 3.74it/s]

85%|████████▌ | 17/20 [00:04<00:00, 3.74it/s]

90%|█████████ | 18/20 [00:05<00:00, 3.75it/s]

95%|█████████▌| 19/20 [00:05<00:00, 3.75it/s]

100%|██████████| 20/20 [00:05<00:00, 3.74it/s]

100%|██████████| 20/20 [00:05<00:00, 3.60it/s]

2023-10-15T01:44:31.942776206+02:00 ==========================================================================================

2023-10-15T01:44:31.942805487+02:00 A tensor with all NaNs was produced in VAE.

2023-10-15T01:44:31.943221758+02:00 Web UI will now convert VAE into 32-bit float and retry.

2023-10-15T01:44:31.943232018+02:00 To disable this behavior, disable the 'Automatically revert VAE to 32-bit floats' setting.

2023-10-15T01:44:31.943235878+02:00 To always start with 32-bit VAE, use --no-half-vae commandline flag.

2023-10-15T01:44:31.943239408+02:00 ==========================================================================================

2023-10-15T01:44:32.664133370+02:00 *** Error running postprocess_image: /workspace/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py

2023-10-15T01:44:32.664227032+02:00 Traceback (most recent call last):

2023-10-15T01:44:32.664238563+02:00 File "/workspace/stable-diffusion-webui/modules/scripts.py", line 675, in postprocess_image

2023-10-15T01:44:32.664242703+02:00 script.postprocess_image(p, pp, *script_args)

2023-10-15T01:44:32.664245793+02:00 File "/workspace/stable-diffusion-webui/extensions/adetailer/adetailer/traceback.py", line 159, in wrapper

2023-10-15T01:44:32.664249193+02:00 raise error from None

2023-10-15T01:44:32.664252103+02:00 ModuleNotFoundError:

2023-10-15T01:44:32.664255053+02:00     ╭──────────────────────────────────────────────────────────────────────────╮
2023-10-15T01:44:32.664263333+02:00     │                               System info                                │
2023-10-15T01:44:32.664266583+02:00     │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
2023-10-15T01:44:32.664269423+02:00     │ ┃             ┃ Value                                                  ┃ │
2023-10-15T01:44:32.664272203+02:00     │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
2023-10-15T01:44:32.664274913+02:00     │ │    Platform │ Linux-5.15.0-67-generic-x86_64-with-glibc2.35          │ │
2023-10-15T01:44:32.664277694+02:00     │ │      Python │ 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]     │ │
2023-10-15T01:44:32.664280394+02:00     │ │     Version │ v1.6.0                                                 │ │
2023-10-15T01:44:32.664283054+02:00     │ │      Commit │ 5ef669de080814067961f28357256e8fe27544f4               │ │
2023-10-15T01:44:32.664303534+02:00     │ │ Commandline │ ['launch.py', '-f', '--port', '3000', '--xformers',    │ │
2023-10-15T01:44:32.664309404+02:00     │ │             │ '--skip-install', '--listen',                          │ │
2023-10-15T01:44:32.664312164+02:00     │ │             │ '--enable-insecure-extension-access']                  │ │
2023-10-15T01:44:32.664314844+02:00     │ │   Libraries │ {'torch': '2.0.1+cu118', 'torchvision':                │ │
2023-10-15T01:44:32.664317555+02:00     │ │             │ '0.15.2+cu118', 'ultralytics': 'Unknown', 'mediapipe': │ │
2023-10-15T01:44:32.664321465+02:00     │ │             │ '0.10.3'}                                              │ │
2023-10-15T01:44:32.664324275+02:00     │ └─────────────┴────────────────────────────────────────────────────────┘ │
2023-10-15T01:44:32.664327015+02:00     │                            Inputs                                        │
2023-10-15T01:44:32.664329745+02:00     │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓            │
2023-10-15T01:44:32.664334615+02:00     │ ┃                 ┃ Value                                   ┃            │
2023-10-15T01:44:32.664337385+02:00     │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩            │
2023-10-15T01:44:32.664340095+02:00     │ │          prompt │ a girl                                  │            │
2023-10-15T01:44:32.664342825+02:00     │ │ negative_prompt │                                         │            │
2023-10-15T01:44:32.664345545+02:00     │ │          n_iter │ 1                                       │            │
2023-10-15T01:44:32.664348515+02:00     │ │      batch_size │ 1                                       │            │
2023-10-15T01:44:32.664351385+02:00     │ │           width │ 1024                                    │            │
2023-10-15T01:44:32.664354046+02:00     │ │          height │ 1024                                    │            │
2023-10-15T01:44:32.664356726+02:00     │ │    sampler_name │ DPM++ 2M Karras                         │            │
2023-10-15T01:44:32.664359396+02:00     │ │       enable_hr │ False                                   │            │
2023-10-15T01:44:32.664362696+02:00     │ │     hr_upscaler │ Latent                                  │            │
2023-10-15T01:44:32.664365336+02:00     │ │      checkpoint │ sd_xl_base_1.0.safetensors [31e35c80fc] │            │
2023-10-15T01:44:32.664368036+02:00     │ │             vae │ Automatic                               │            │
2023-10-15T01:44:32.664370716+02:00     │ │            unet │ Automatic                               │            │
2023-10-15T01:44:32.664373846+02:00     │ └─────────────────┴─────────────────────────────────────────┘            │
2023-10-15T01:44:32.664376586+02:00     │                 ADetailer                                                │
2023-10-15T01:44:32.664379306+02:00     │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓                                │
2023-10-15T01:44:32.664383756+02:00     │ ┃                     ┃ Value           ┃                                │
2023-10-15T01:44:32.664386486+02:00     │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩                                │
2023-10-15T01:44:32.664389196+02:00     │ │             version │ 23.10.0         │                                │
2023-10-15T01:44:32.664391876+02:00     │ │            ad_model │ face_yolov8s.pt │                                │
2023-10-15T01:44:32.664398877+02:00     │ │           ad_prompt │                 │                                │
2023-10-15T01:44:32.664401757+02:00     │ │  ad_negative_prompt │                 │                                │
2023-10-15T01:44:32.664404397+02:00     │ │ ad_controlnet_model │ None            │                                │
2023-10-15T01:44:32.664407077+02:00     │ │              is_api │ False           │                                │
2023-10-15T01:44:32.664409797+02:00     │ └─────────────────────┴─────────────────┘                                │
2023-10-15T01:44:32.664412557+02:00     │ ╭───────────────── Traceback (most recent call last) ──────────────────╮ │
2023-10-15T01:44:32.664417227+02:00     │ │ /workspace/stable-diffusion-webui/extensions/adetailer/adetailer/tra │ │
2023-10-15T01:44:32.664419987+02:00     │ │ ceback.py:139 in wrapper                                             │ │
2023-10-15T01:44:32.664422677+02:00     │ │                                                                      │ │
2023-10-15T01:44:32.664425357+02:00     │ │   136 │   │   width = width - 4 if width > 4 else None               │ │
2023-10-15T01:44:32.664428047+02:00     │ │   137 │   │   console = Console(file=string, width=width)            │ │
2023-10-15T01:44:32.664431257+02:00     │ │   138 │   │   try:                                                   │ │
2023-10-15T01:44:32.664434108+02:00     │ │ ❱ 139 │   │   │   return func(*args, **kwargs)                       │ │
2023-10-15T01:44:32.664437138+02:00     │ │   140 │   │   except Exception as e:                                 │ │
2023-10-15T01:44:32.664439858+02:00     │ │   141 │   │   │   tables = [                                         │ │
2023-10-15T01:44:32.664442648+02:00     │ │   142 │   │   │   │   get_table(title, data)                         │ │
2023-10-15T01:44:32.664445318+02:00     │ │                                                                      │ │
2023-10-15T01:44:32.664448018+02:00     │ │ /workspace/stable-diffusion-webui/extensions/adetailer/scripts/!adet │ │
2023-10-15T01:44:32.664450838+02:00     │ │ ailer.py:703 in postprocess_image                                    │ │
2023-10-15T01:44:32.664453458+02:00     │ │                                                                      │ │
2023-10-15T01:44:32.664456138+02:00     │ │   700 │   │   │   for n, args in enumerate(arg_list):                │ │
2023-10-15T01:44:32.664458878+02:00     │ │   701 │   │   │   │   if args.ad_model == "None":                    │ │
2023-10-15T01:44:32.664461558+02:00     │ │   702 │   │   │   │   │   continue                                   │ │
2023-10-15T01:44:32.664464328+02:00     │ │ ❱ 703 │   │   │   │   is_processed |= self._postprocess_image_inner( │ │
2023-10-15T01:44:32.664466978+02:00     │ │   704 │   │                                                          │ │
2023-10-15T01:44:32.664469658+02:00     │ │   705 │   │   if is_processed and not getattr(p, "_ad_skip_img2img", │ │
2023-10-15T01:44:32.664472319+02:00     │ │   706 │   │   │   self.save_image(                                   │ │
2023-10-15T01:44:32.664474979+02:00     │ │                                                                      │ │
2023-10-15T01:44:32.664477859+02:00     │ │ /workspace/stable-diffusion-webui/extensions/adetailer/scripts/!adet │ │
2023-10-15T01:44:32.664480599+02:00     │ │ ailer.py:628 in _postprocess_image_inner                             │ │
2023-10-15T01:44:32.664483259+02:00     │ │                                                                      │ │
2023-10-15T01:44:32.664485969+02:00     │ │   625 │   │   │   kwargs["device"] = self.ultralytics_device         │ │
2023-10-15T01:44:32.664488639+02:00     │ │   626 │   │                                                          │ │
2023-10-15T01:44:32.664495329+02:00     │ │   627 │   │   with change_torch_load():                              │ │
2023-10-15T01:44:32.664498239+02:00     │ │ ❱ 628 │   │   │   pred = predictor(ad_model, pp.image, args.ad_confi │ │
2023-10-15T01:44:32.664500929+02:00     │ │   629 │   │                                                          │ │
2023-10-15T01:44:32.664503569+02:00     │ │   630 │   │   masks = self.pred_preprocessing(pred, args)            │ │
2023-10-15T01:44:32.664506249+02:00     │ │   631 │   │   shared.state.assign_current_image(pred.preview)        │ │
2023-10-15T01:44:32.664508890+02:00     │ │                                                                      │ │
2023-10-15T01:44:32.664512170+02:00     │ │ /workspace/stable-diffusion-webui/extensions/adetailer/adetailer/ult │ │
2023-10-15T01:44:32.664514860+02:00     │ │ ralytics.py:19 in ultralytics_predict                                │ │
2023-10-15T01:44:32.664517510+02:00     │ │                                                                      │ │
2023-10-15T01:44:32.664520140+02:00     │ │   16 │   confidence: float = 0.3,                                    │ │
2023-10-15T01:44:32.664522820+02:00     │ │   17 │   device: str = "",                                           │ │
2023-10-15T01:44:32.664525490+02:00     │ │   18 ) -> PredictOutput:                                             │ │
2023-10-15T01:44:32.664528130+02:00     │ │ ❱ 19 │   from ultralytics import YOLO                                │ │
2023-10-15T01:44:32.664530800+02:00     │ │   20 │                                                               │ │
2023-10-15T01:44:32.664534290+02:00     │ │   21 │   model = YOLO(model_path)                                    │ │
2023-10-15T01:44:32.664536960+02:00     │ │   22 │   pred = model(image, conf=confidence, device=device)         │ │
2023-10-15T01:44:32.664539670+02:00     │ ╰──────────────────────────────────────────────────────────────────────╯ │
2023-10-15T01:44:32.664542420+02:00     │ ModuleNotFoundError: No module named 'ultralytics'                       │
2023-10-15T01:44:32.664545200+02:00     ╰──────────────────────────────────────────────────────────────────────────╯
2023-10-15T01:44:32.664547971+02:00 
2023-10-15T01:44:32.664550561+02:00 
2023-10-15T01:44:32.664553161+02:00 ---
2023-10-15T01:44:33.213202004+02:00 
Total progress: 100%|██████████| 20/20 [00:05<00:00,  3.74it/s]
2023-10-15T01:44:33.213409309+02:00 
Total progress: 100%|██████████| 20/20 [00:07<00:00,  3.74it/s]
Total progress: 100%|██████████| 20/20 [00:07<00:00,  2.81it/s]
```

### List of installed extensions

ControlNet + Deforum are installing by default on RunPod + AfterDetailer v23.10.0

**Comment by Bing-su** [comment]
```sh
2023-10-15T01:44:32.664303534+02:00     │ │ Commandline │ ['launch.py', '-f', '--port', '3000', '--xformers',    │ │
2023-10-15T01:44:32.664309404+02:00     │ │             │ '--skip-install', '--listen',                          │ │
2023-10-15T01:44:32.664312164+02:00     │ │             │ '--enable-insecure-extension-access']                  │ │
```

Since runpod's template sets the `--skip-install` option, you'll need to turn it off or install `ultralytics` manually.

**Comment by Seryogerr** [comment]
> Since runpod's template sets the `--skip-install` option, you'll need to turn it off or install `ultralytics` manually.

THX, find arguments in workspace/stable-diffusion-webui/webui-user.sh   :P
Fix,restart and all work good 💯 
Thank you for the quick response for solving the problem
