### ISSUE TITLE
[Bug]: adetailer reports! adetailer.py (error)

### ISSUE THREAD

**Issue by sw854638335** [Bing-su/adetailer#395]
### Screenshots

![微信图片_20231102210204](https://github.com/Bing-su/adetailer/assets/25842601/e203e5de-68bb-47eb-9200-a731b051d4c2)

### Console logs, from start to end.

```Shell
WARNING  Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', or 'pose'.
YOLOv8n-seg summary (fused): 195 layers, 3258259 parameters, 0 gradients, 12.0 GFLOPs

*** Error running postprocess_image: D:\Program Files (x86)\sd-webui-aki-v4.4\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "D:\Program Files (x86)\sd-webui-aki-v4.4\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\Program Files (x86)\sd-webui-aki-v4.4\extensions\adetailer\adetailer\traceback.py", line 159, in wrapper
        raise error from None
    KeyError: '
┌─────────────────────────────────────────────────────────────────────────┐
│                               System info                               │
│ ┌─────────────┬───────────────────────────────────────────────────────┐ │
│ │             │ Value                                                 │ │
│ ├─────────────┼───────────────────────────────────────────────────────┤ │
│ │    Platform │ Windows-10-10.0.22621-SP0                             │ │
│ │      Python │ 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023,          │ │
│ │             │ 00:38:17) [MSC v.1929 64 bit (AMD64)]                 │ │
│ │     Version │ v1.6.0                                                │ │
│ │      Commit │ 5ef669de080814067961f28357256e8fe27544f4              │ │
│ │ Commandline │ [\'D:\\Program Files                                   │ │
│ │             │ (x86)\\sd-webui-aki-v4.4\\launch.py\', \'--medvram\',    │ │
│ │             │ \'--theme\', \'light\', \'--xformers\', \'--api\',            │ │
│ │             │ \'--autolaunch\']                                       │ │
│ │   Libraries │ {\'torch\': \'2.0.1+cu118\', \'torchvision\':               │ │
│ │             │ \'0.15.2+cu118\', \'ultralytics\': \'8.0.203\',             │ │
│ │             │ \'mediapipe\': \'0.10.7\'}                                │ │
│ └─────────────┴───────────────────────────────────────────────────────┘ │
│                                 Inputs                                  │
│ ┌─────────────────┬───────────────────────────────────────────────────┐ │
│ │                 │ Value                                             │ │
│ ├─────────────────┼───────────────────────────────────────────────────┤ │
│ │          prompt │ masterpiece,best quality,official art,extremely   │ │
│ │                 │ detailed CG unity 8k                              │ │
│ │                 │ wallpaper,photorealistic,photo studio,photo       │ │
│ │                 │ shoot,ultra detailed graphic tension,stunning     │ │
│ │                 │ colors,rendering,cinematic lighting               │ │
│ │                 │ effects,realism,00 renderer,super                 │ │
│ │                 │ realistic,((full_body_photos)),super vista,super  │ │
│ │                 │ wide Angle,HD,                                    │ │
│ │                 │ 1 girl,solo,full body,stand,exquisite             │ │
│ │                 │ makeup,perfect facial                             │ │
│ │                 │ features,earrings,gemstones,fair skin,white       │ │
│ │                 │ cheongsam, hair,bun                               │ │
│ │                 │ hair,Beauty,elegance,generosity,feminine          │ │
│ │                 │ charm,simple background,White background,Plump    │ │
│ │                 │ figure,                                           │ │
│ │                 │ <lora:real_青色旗袍_v1.0:0.1>,                    │ │
│ │ negative_prompt │ Negative prompt: nsfw,, , , lowres normal         │ │
│ │                 │ quality, [], [], skin sports, acnes, skin         │ │
│ │                 │ blemishes, age spot, , , , , , , , lowers, bad    │ │
│ │                 │ hands, missing fingers, extra digit, bad hands,   │ │
│ │                 │ missing fingers, [[]], hair covering              │ │
│ │                 │ eyebrows,bad-hands-5, EasyNegativeV2_V2.0,Stage   │ │
│ │                 │ lights,audience, crowd,portrait,Patterned         │ │
│ │                 │ cheongsam,                                        │ │
│ │          n_iter │ 1                                                 │ │
│ │      batch_size │ 1                                                 │ │
│ │           width │ 512                                               │ │
│ │          height │ 768                                               │ │
│ │    sampler_name │ Restart                                           │ │
│ │       enable_hr │ True                                              │ │
│ │     hr_upscaler │ 8x_NMKD-Superscale_150000_G_1                     │ │
│ │      checkpoint │ real_majicMIX realistic 麦橘写实_v7.safetensors   │ │
│ │                 │ [7c819b6d13]                                      │ │
│ │             vae │ None                                              │ │
│ │            unet │ Automatic                                         │ │
│ └─────────────────┴───────────────────────────────────────────────────┘ │
│                    ADetailer                                            │
│ ┌─────────────────────┬───────────────────────┐                         │
│ │                     │ Value                 │                         │
│ ├─────────────────────┼───────────────────────┤                         │
│ │             version │ 23.11.0               │                         │
│ │            ad_model │ person_yolov8n-seg.pt │                         │
│ │           ad_prompt │                       │                         │
│ │  ad_negative_prompt │                       │                         │
│ │ ad_controlnet_model │ None                  │                         │
│ │              is_api │ False                 │                         │
│ └─────────────────────┴───────────────────────┘                         │
│ ┌───────────────── Traceback (most recent call last) ─────────────────┐ │
│ │ D:\Program Files                                                    │ │
│ │ (x86)\sd-webui-aki-v4.4\extensions\adetailer\adetailer\traceback.py │ │
│ │ :139 in wrapper                                                     │ │
│ │                                                                     │ │
│ │   138 │   │   try:                                                  │ │
│ │ > 139 │   │   │   return func(*args, **kwargs)                      │ │
│ │   140 │   │   except Exception as e:                                │ │
│ │                                                                     │ │
│ │ D:\Program Files                                                    │ │
│ │ (x86)\sd-webui-aki-v4.4\extensions\adetailer\scripts\!adetailer.py: │ │
│ │ 745 in postprocess_image                                            │ │
│ │                                                                     │ │
│ │   744 │   │   │   │   │   continue                                  │ │
│ │ > 745 │   │   │   │   is_processed |= self._postprocess_image_inner │ │
│ │   746                                                               │ │
│ │                                                                     │ │
│ │ D:\Program Files                                                    │ │
│ │ (x86)\sd-webui-aki-v4.4\extensions\adetailer\scripts\!adetailer.py: │ │
│ │ 671 in _postprocess_image_inner                                     │ │
│ │                                                                     │ │
│ │   670 │   │   with change_torch_load():                             │ │
│ │ > 671 │   │   │   pred = predictor(ad_model, pp.image, args.ad_conf │ │
│ │   672                                                               │ │
│ │                                                                     │ │
│ │ D:\Program Files                                                    │ │
│ │ (x86)\sd-webui-aki-v4.4\extensions\adetailer\adetailer\ultralytics. │ │
│ │ py:22 in ultralytics_predict                                        │ │
│ │                                                                     │ │
│ │   21 │   model = YOLO(model_path)                                   │ │
│ │ > 22 │   pred = model(image, conf=confidence, device=device)        │ │
│ │   23                                                                │ │
│ │                                                                     │ │
│ │ D:\Program Files                                                    │ │
│ │ (x86)\sd-webui-aki-v4.4\python\lib\site-packages\ultralytics\engine │ │
│ │ \model.py:101 in __call__                                           │ │
│ │                                                                     │ │
│ │   100 │   │   """Calls the \'predict\' function with given arguments  │ │
│ │ > 101 │   │   return self.predict(source, stream, **kwargs)         │ │
│ │   102                                                               │ │
│ │                                                                     │ │
│ │ D:\Program Files                                                    │ │
│ │ (x86)\sd-webui-aki-v4.4\python\lib\site-packages\ultralytics\engine │ │
│ │ \model.py:242 in predict                                            │ │
│ │                                                                     │ │
│ │   241 │   │   │   self.predictor.set_prompts(prompts)               │ │
│ │ > 242 │   │   return self.predictor.predict_cli(source=source) if i │ │
│ │   243                                                               │ │
│ │                                                                     │ │
│ │ D:\Program Files                                                    │ │
│ │ (x86)\sd-webui-aki-v4.4\python\lib\site-packages\ultralytics\engine │ │
│ │ \predictor.py:196 in __call__                                       │ │
│ │                                                                     │ │
│ │   195 │   │   else:                                                 │ │
│ │ > 196 │   │   │   return list(self.stream_inference(source, model,  │ │
│ │   197                                                               │ │
│ │                                                                     │ │
│ │ D:\Program Files                                                    │ │
│ │ (x86)\sd-webui-aki-v4.4\python\lib\site-packages\torch\utils\_conte │ │
│ │ xtlib.py:35 in generator_context                                    │ │
│ │                                                                     │ │
│ │    34 │   │   │   with ctx_factory():                               │ │
│ │ >  35 │   │   │   │   response = gen.send(None)                     │ │
│ │    36                                                               │ │
│ │                                                                     │ │
│ │ D:\Program Files                                                    │ │
│ │ (x86)\sd-webui-aki-v4.4\python\lib\site-packages\ultralytics\engine │ │
│ │ \predictor.py:278 in stream_inference                               │ │
│ │                                                                     │ │
│ │   277 │   │   │   │   if self.args.verbose or self.args.save or sel │ │
│ │ > 278 │   │   │   │   │   s += self.write_results(i, self.results,  │ │
│ │   279 │   │   │   │   if self.args.save or self.args.save_txt:      │ │
│ │                                                                     │ │
│ │ D:\Program Files                                                    │ │
│ │ (x86)\sd-webui-aki-v4.4\python\lib\site-packages\ultralytics\engine │ │
│ │ \predictor.py:166 in write_results                                  │ │
│ │                                                                     │ │
│ │   165 │   │   result = results[idx]                                 │ │
│ │ > 166 │   │   log_string += result.verbose()                        │ │
│ │   167                                                               │ │
│ │                                                                     │ │
│ │ D:\Program Files                                                    │ │
│ │ (x86)\sd-webui-aki-v4.4\python\lib\site-packages\ultralytics\engine │ │
│ │ \results.py:275 in verbose                                          │ │
│ │                                                                     │ │
│ │   274 │   │   │   │   n = (boxes.cls == c).sum()  # detections per  │ │
│ │ > 275 │   │   │   │   log_string += f"{n} {self.names[int(c)]}{\'s\'  │ │
│ │   276 │   │   return log_string                                     │ │
│ └─────────────────────────────────────────────────────────────────────┘ │
│ KeyError: 10                                                            │
└─────────────────────────────────────────────────────────────────────────┘
'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
```

**Comment by Bing-su** [comment]
https://github.com/Bing-su/adetailer/issues/354

It's probably a problem with the model file.
