### ISSUE TITLE
[Bug]: Unable to locate ControlNet path

### ISSUE THREAD

**Issue by cjj1977** [Bing-su/adetailer#404]
### Describe the bug

I see the following error when I enable a ControlNet model in ADetailer:
```
File "S:\StableDiffusion\data\extensions\adetailer\controlnet_ext\controlnet_ext.py", line 56, in init_controlnet
  self.external_cn = importlib.import_module(import_path, "external_code")
...
ModuleNotFoundError: No module named 'extensions.sd-webui-controlnet'
```

Debugging this, the **import_path** variable is: `extensions.sd-webui-controlnet.scripts.external_code`

----

I suspect the problem is that I have my extensions installed in a separate path to the main **stable-diffusion-webui** folder. I use the `--data-dir` command line switch which changes the root path for extensions as well as the models, etc.

My guess is that this is caused by this line, which assumes that the cn_base_path will be relative to the **stable-diffusion-webui** folder?
```
cn_base_path = ".".join(controlnet_path.parts[-2:])
```

To test this I (temporarily) created a junction point that maps the **extensions** folder under the **stable-diffusion-webui** root to my external location and the ControlNet error stopped.

### Console logs, from start to end.

```Shell
venv "S:\StableDiffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.5.0-1030-g6d73ea4b
Commit hash: 6d73ea4b051e8d09db2c63db9a128466e3bbde1f
Checking ReActor requirements... Ok
Launching Web UI with arguments: --data-dir=S:\StableDiffusion\data --ckpt-dir=S:\StableDiffusion\data\models\Checkpoints --vae-dir=S:\StableDiffusion\data\models\VAE --enable-insecure-extension-access --listen --no-half-vae --theme=dark --xformers

...

[-] ADetailer initialized. version: 23.11.0, num models: 11
2023-11-08 20:09:12,002 - ControlNet - INFO - ControlNet v1.1.415
ControlNet preprocessor location: S:\StableDiffusion\data\extensions\sd-webui-controlnet\annotator\downloads
2023-11-08 20:09:12,828 - ControlNet - INFO - ControlNet v1.1.415
20:09:16 - ReActor - STATUS - Running v0.4.3
Loading weights [15012c538f] from S:\StableDiffusion\data\models\Checkpoints\realisticVisionV51_v51VAE.safetensors
Creating model from config: S:\StableDiffusion\stable-diffusion-webui\configs\v1-inference.yaml
Running on local URL:  http://0.0.0.0:7860

[-] ADetailer: ControlNetExt init failed:
Traceback (most recent call last):
  File "S:\StableDiffusion\data\extensions\adetailer\scripts\!adetailer.py", line 170, in init_controlnet_ext
    self.controlnet_ext.init_controlnet()
  File "S:\StableDiffusion\data\extensions\adetailer\controlnet_ext\controlnet_ext.py", line 56, in init_controlnet
    self.external_cn = importlib.import_module(import_path, "external_code")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name, package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'extensions.sd-webui-controlnet'
```

**Comment by Bing-su** [comment]
I was aware of this issue, but I wasn't very good at handling paths, so I didn't fix it, sorry.

**Comment by cjj1977** [comment]
I might try to fix this myself and raise a PR...
