### ISSUE TITLE
[Bug]: Controlnet stops face detection

### ISSUE THREAD

**Issue by roycho87** [Bing-su/adetailer#417]
### Describe the bug

When using img2img adetailer, the extension cannot detect faces if you use any controlnet other than "none".

It does not matter what "Detection model confidence threshold" you use.

### Console logs, from start to end.

```Shell
*** Error running postprocess_image: C:\StableDiffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 575, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\StableDiffusion\stable-diffusion-webui\extensions\adetailer\adetailer\traceback.py", line 159, in wrapper
        raise error from None
    RuntimeError:
    ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
    │                                                   System info                                                    │
    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃             ┃ Value                                                                                          ┃ │
    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │    Platform │ Windows-10-10.0.22621-SP0                                                                      │ │
    │ │      Python │ 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]               │ │
    │ │     Version │ v1.5.1                                                                                         │ │
    │ │      Commit │ 68f336bd994bed5442ad95bad6b6ad5564a5409a                                                       │ │
    │ │ Commandline │ ['launch.py', '--xformers', '--api', '--autolaunch', '--theme', 'dark', '--disable-nan-check', │ │
    │ │             │ '--no-half', '--ckpt-dir', 'D:\\Work\\AIWork\\Saving\\models\\SDModels']                       │ │
    │ │   Libraries │ {'torch': '2.0.1+cu118', 'torchvision': '0.15.2+cu118', 'ultralytics': '8.0.211', 'mediapipe': │ │
    │ │             │ '0.10.8'}                                                                                      │ │
    │ └─────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘ │
    │                                                      Inputs                                                      │
    │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃                 ┃ Value                                                                                      ┃ │
    │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │          prompt │ 1girl, solo, a sexy (melk0r woman) wearing a ((long black skirt)), bimbo succubus, sexy    │ │
    │ │                 │ demon, (((midriff, bikini top))), long black hair, red skin, red eyes, black collar, black │ │
    │ │                 │ choker, huge ass, huge tits, thin waist, full lips, plump lips, simple background, high    │ │
    │ │                 │ detail, best quality                                                                       │ │
    │ │ negative_prompt │ bangs, (underboob, short dress, short skirt, red bikini, red skirt, white bikini), chat    │ │
    │ │                 │ bubbles, speech bubbles, cell phone, nipples, naked, nude, topless, ugly, tiling, poorly   │ │
    │ │                 │ drawn hands, poorly drawn feet, poorly drawn face, out of frame, extra limbs, disfigured,  │ │
    │ │                 │ deformed, body out of frame, bad anatomy, watermark, signature, cut off, low contrast,     │ │
    │ │                 │ underexposed, overexposed, bad art, beginner, amateur, distorted face                      │ │
    │ │          n_iter │ 1                                                                                          │ │
    │ │      batch_size │ 1                                                                                          │ │
    │ │           width │ 576                                                                                        │ │
    │ │          height │ 1024                                                                                       │ │
    │ │    sampler_name │ Euler a                                                                                    │ │
    │ │       enable_hr │ False                                                                                      │ │
    │ │     hr_upscaler │                                                                                            │ │
    │ │      checkpoint │ melkor_solo\melkor_solo_24400.safetensors [7750e811b6]                                     │ │
    │ │             vae │ Automatic                                                                                  │ │
    │ │            unet │ Automatic                                                                                  │ │
    │ └─────────────────┴────────────────────────────────────────────────────────────────────────────────────────────┘ │
    │                                                    ADetailer                                                     │
    │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃                     ┃ Value                                                                                  ┃ │
    │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │             version │ 23.11.0                                                                                │ │
    │ │            ad_model │ face_yolov8n.pt                                                                        │ │
    │ │           ad_prompt │ 1girl, solo, a sexy (melk0r woman) wearing a ((long black skirt)), bimbo succubus,     │ │
    │ │                     │ sexy demon, (((midriff, bikini top))), long black hair, red skin, red eyes, black      │ │
    │ │                     │ collar, black choker, huge ass, huge tits, thin waist, full lips, plump lips, simple   │ │
    │ │                     │ background, high detail, best quality                                                  │ │
    │ │  ad_negative_prompt │ chat bubbles, speech bubbles, cell phone, nipples, naked, nude, topless, ugly, tiling, │ │
    │ │                     │ poorly drawn hands, poorly drawn feet, poorly drawn face, out of frame, extra limbs,   │ │
    │ │                     │ disfigured, deformed, body out of frame, bad anatomy, watermark, signature, cut off,   │ │
    │ │                     │ low contrast, underexposed, overexposed, bad art, beginner, amateur, distorted face    │ │
    │ │ ad_controlnet_model │ control_v11p_sd15_openpose                                                             │ │
    │ │              is_api │ False                                                                                  │ │
    │ └─────────────────────┴────────────────────────────────────────────────────────────────────────────────────────┘ │
    │ ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮             │
    │ │ C:\StableDiffusion\stable-diffusion-webui\extensions\adetailer\controlnet_ext\controlnet_ext.py: │             │
    │ │ 94 in update_scripts_args                                                                        │             │
    │ │                                                                                                  │             │
    │ │    93 │   │   try:                                                                               │             │
    │ │ ❱  94 │   │   │   self.external_cn.update_cn_script_in_processing(p, cn_units)                   │             │
    │ │    95 │   │   except AttributeError as e:                                                        │             │
    │ │                                                                                                  │             │
    │ │ C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\internal_controlnet\ext │             │
    │ │ ernal_code.py:327 in update_cn_script_in_processing                                              │             │
    │ │                                                                                                  │             │
    │ │   326 │   """                                                                                    │             │
    │ │ ❱ 327 │   p.script_args = update_cn_script(p.scripts, p.script_args_value, cn_units)             │             │
    │ │   328                                                                                            │             │
    │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯             │
    │ AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'script_args_value'                   │
    │                                                                                                                  │
    │ The above exception was the direct cause of the following exception:                                             │
    │                                                                                                                  │
    │ ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮             │
    │ │ C:\StableDiffusion\stable-diffusion-webui\extensions\adetailer\adetailer\traceback.py:139 in     │             │
    │ │ wrapper                                                                                          │             │
    │ │                                                                                                  │             │
    │ │   138 │   │   try:                                                                               │             │
    │ │ ❱ 139 │   │   │   return func(*args, **kwargs)                                                   │             │
    │ │   140 │   │   except Exception as e:                                                             │             │
    │ │                                                                                                  │             │
    │ │ C:\StableDiffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py:745 in      │             │
    │ │ postprocess_image                                                                                │             │
    │ │                                                                                                  │             │
    │ │   744 │   │   │   │   │   continue                                                               │             │
    │ │ ❱ 745 │   │   │   │   is_processed |= self._postprocess_image_inner(p, pp, args, n=n)            │             │
    │ │   746                                                                                            │             │
    │ │                                                                                                  │             │
    │ │ C:\StableDiffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py:655 in      │             │
    │ │ _postprocess_image_inner                                                                         │             │
    │ │                                                                                                  │             │
    │ │   654 │   │   pp.image = self.get_i2i_init_image(p, pp)                                          │             │
    │ │ ❱ 655 │   │   i2i = self.get_i2i_p(p, args, pp.image)                                            │             │
    │ │   656 │   │   seed, subseed = self.get_seed(p)                                                   │             │
    │ │                                                                                                  │             │
    │ │ C:\StableDiffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py:519 in      │             │
    │ │ get_i2i_p                                                                                        │             │
    │ │                                                                                                  │             │
    │ │   518 │   │   if args.ad_controlnet_model != "None":                                             │             │
    │ │ ❱ 519 │   │   │   self.update_controlnet_args(i2i, args)                                         │             │
    │ │   520 │   │   else:                                                                              │             │
    │ │                                                                                                  │             │
    │ │ C:\StableDiffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py:187 in      │             │
    │ │ update_controlnet_args                                                                           │             │
    │ │                                                                                                  │             │
    │ │   186 │   │   ):                                                                                 │             │
    │ │ ❱ 187 │   │   │   self.controlnet_ext.update_scripts_args(                                       │             │
    │ │   188 │   │   │   │   p,                                                                         │             │
    │ │                                                                                                  │             │
    │ │ C:\StableDiffusion\stable-diffusion-webui\extensions\adetailer\controlnet_ext\controlnet_ext.py: │             │
    │ │ 99 in update_scripts_args                                                                        │             │
    │ │                                                                                                  │             │
    │ │    98 │   │   │   msg = "[-] Adetailer: ControlNet option not available in WEBUI version lower   │             │
    │ │ ❱  99 │   │   │   raise RuntimeError(msg) from e                                                 │             │
    │ │   100                                                                                            │             │
    │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯             │
    │ RuntimeError: [-] Adetailer: ControlNet option not available in WEBUI version lower than 1.6.0 due to updates in │
    │ ControlNet                                                                                                       │
    ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 50/50 [01:27<00:00,  1.74s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 50/50 [01:27<00:00,  1.77s/it]
```

**Comment by Bing-su** [comment]
```
RuntimeError: [-] Adetailer: ControlNet option not available in WEBUI version lower than 1.6.0 due to updates in ControlNet
```

Due to changes in ControlNet, webui version 1.6.0 is required.
