### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by haythamodeh** [Bing-su/adetailer#419]
### Describe the bug

Im getting this error when loading adetailer:
Error loading script: !adetailer.py
Traceback (most recent call last):
File "/Users/-----/Desktop/Stable Diffusion Web UI.app/Contents/Resources/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "/Users/-----/Desktop/Stable Diffusion Web UI.app/Contents/Resources/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
module_spec.loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in _call_with_frames_removed
File "/Users/-----/Documents/Stable Diffusion Web UI/extensions/adetailer/scripts/!adetailer.py", line 17, in
from rich import print
ModuleNotFoundError: No module named 'rich'

webui still runs, but adetailer doesn't show up in the extension tabs.
I tried installing rich with pip, still didn't work, I also tried updating requirements.txt and requirements_versions.txt.
i tried deleting venv folder, but got stuck with some issues so I restored the venv back, I'm not sure why this problem is happening. any help would be appreciated. thanks

### Console logs, from start to end.

```Shell
Python 3.10.13 (main, Sep  4 2023, 20:22:24) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Version: 20230919_experimental
Commit hash: db9cdd8fd96e424dc53a4fe16ef1095595d10725
ReActor preheating... Device: CPU
Launching Web UI with arguments: --data-dir /Users/----/Documents/Stable Diffusion Web UI --electron --electron-path /Users/----/Desktop/Stable Diffusion Web UI.app/Contents/MacOS/Electron --electron-quit-on-exit --skip-torch-cuda-test --skip-install --no-half-vae --upcast-sampling --precision full
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
*** Error loading script: !adetailer.py
    Traceback (most recent call last):
      File "/Users/----/Desktop/Stable Diffusion Web UI.app/Contents/Resources/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/----/Desktop/Stable Diffusion Web UI.app/Contents/Resources/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/----/Documents/Stable Diffusion Web UI/extensions/adetailer/scripts/!adetailer.py", line 17, in <module>
        from rich import print
    ModuleNotFoundError: No module named 'rich'

---
```

**Comment by haythamodeh** [comment]
i got it to work by activating my venv and pip installing rich
