### ISSUE TITLE
[Bug]:adetailer does not appear on the management screen even after installation インストールしても管理画面にadetailer が現れません

### ISSUE THREAD

**Issue by tktktktjp** [Bing-su/adetailer#422]
### Describe the bug
I installed it, but adetailer does not appear in the admin panel.
It is in the extensions section.
but it is not in the control panel.

How can I get it to appear in the control panel?
インストールしても管理画面にadetailer が現れません
エクステンションのところにはあるのですが
操作画面にはないです。

どうしたら操作画面に現れるのでしょうか？

![b6e05a49294e92ccb8fb9f7d6c744647](https://github.com/Bing-su/adetailer/assets/92702283/9dbea364-9df0-4739-aab0-41c34bac7788)
![472dd1cc03a3575c49642a441de3decb](https://github.com/Bing-su/adetailer/assets/92702283/9e1dc88d-e4b7-4015-b2bc-4f150fd3b18f)

### Screenshots

![472dd1cc03a3575c49642a441de3decb](https://github.com/Bing-su/adetailer/assets/92702283/a0c1d5dd-3a5d-46c7-aeb8-03d43e9d39d2)
![b6e05a49294e92ccb8fb9f7d6c744647](https://github.com/Bing-su/adetailer/assets/92702283/0c5267d3-823a-422d-a74d-3c9fd828ed2e)

### Console logs, from start to end.

```Shell
*** Error loading script: !adetailer.py
    Traceback (most recent call last):
      File "C:\Users\info\stable diffusion20231121\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\info\stable diffusion20231121\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\info\stable diffusion20231121\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 22, in <module>
        from adetailer import (
      File "C:\Users\info\stable diffusion20231121\stable-diffusion-webui\extensions\adetailer\adetailer\__init__.py", line 2, in <module>
        from .args import ALL_ARGS, ADetailerArgs
      File "C:\Users\info\stable diffusion20231121\stable-diffusion-webui\extensions\adetailer\adetailer\args.py", line 39, in <module>
        class ADetailerArgs(BaseModel, extra=Extra.forbid):
      File "pydantic\main.py", line 178, in pydantic.main.ModelMetaclass.__new__
      File "pydantic\typing.py", line 396, in pydantic.typing.resolve_annotations
    TypeError: ForwardRef.__init__() got an unexpected keyword argument 'is_class'

---
Loading weights [6ce0161689] from C:\Users\info\stable diffusion20231121\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 6.8s (prepare environment: 1.7s, import torch: 2.3s, import gradio: 0.6s, setup paths: 0.6s, initialize shared: 0.2s, other imports: 0.4s, load scripts: 0.5s, create ui: 0.4s, gradio launch: 0.1s).
Creating model from config: C:\Users\info\stable diffusion20231121\stable-diffusion-webui\configs\v1-inference.yaml
Applying attention optimization: Doggettx... done.
Model loaded in 3.6s (load weights from disk: 0.5s, create model: 0.2s, apply weights to model: 2.6s, calculate empty prompt: 0.1s).
```

**Comment by Bing-su** [comment]
https://github.com/pydantic/pydantic/discussions/6244

This appears to be an issue with specific Python versions only. Try using Python 3.10.11 or later.

**Comment by tktktktjp** [comment]
my pc python version is 3.10.11 .

C:\Users\info>python --version
Python 3.10.6

**Comment by tktktktjp** [comment]
thank you this problem is solution that it upgread python vesion
