### ISSUE TITLE
[Bug]: No module named 'rich' on MacOS (extension doesn't load its depedencies)

### ISSUE THREAD

**Issue by Infiexe** [Bing-su/adetailer#428]
### Describe the bug

Edit: apparently ADetailer doesn't install any of its depedencies in this environment

Edit 2: Resolved by running `./venv/bin/python -m pip install rich`, `./venv/bin/python -m pip install wheel`, `./venv/bin/python -m pip install mediapipe` and `./venv/bin/python -m pip install ultralytics` in the webUI main directory. I guess it's a webUI problem then? [Reported here](https://github.com/brkirch/stable-diffusion-webui/issues/22).

I'm getting the no module named 'rich' error. Running `brew install rich` installs the module correctly, but it doesn't change this error message. I'm using the [experimental MacOS branch](https://github.com/brkirch/stable-diffusion-webui/releases).

### Console logs, from start to end.

```Shell
Last login: Tue Nov 28 11:14:27 on ttys000
cd '/Users/user1/stable-diffusion/stable-diffusion-webui-experimental';./webui.sh;exit
user1@infibook-air ~ % cd '/Users/user1/stable-diffusion/stable-diffusion-webui-experimental';./webui.sh;exit

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on user1 user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.13 (main, Sep  4 2023, 20:22:24) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Version: 20230919_experimental
Commit hash: db9cdd8fd96e424dc53a4fe16ef1095595d10725
ReActor preheating... Device: CPU
Launching Web UI with arguments: --skip-torch-cuda-test --skip-install --no-half-vae --upcast-sampling --precision full
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
*** Error loading script: !adetailer.py
    Traceback (most recent call last):
      File "/Users/user1/stable-diffusion/stable-diffusion-webui-experimental/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/user1/stable-diffusion/stable-diffusion-webui-experimental/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/user1/stable-diffusion/stable-diffusion-webui-experimental/extensions/adetailer/scripts/!adetailer.py", line 18, in <module>
        from rich import print
    ModuleNotFoundError: No module named 'rich'

---
2023-11-28 11:14:33,503 - ControlNet - INFO - ControlNet v1.1.410
ControlNet preprocessor location: /Users/user1/stable-diffusion/stable-diffusion-webui-experimental/extensions/sd-webui-controlnet/annotator/downloads
2023-11-28 11:14:33,562 - ControlNet - INFO - ControlNet v1.1.410
11:14:33 - ReActor - STATUS - Running v0.5.1-b4
Loading weights [f9fe08f411] from /Users/user1/stable-diffusion/stable-diffusion-webui-experimental/models/Stable-diffusion/obsidianmixv3_.safetensors
Creating model from config: /Users/user1/stable-diffusion/stable-diffusion-webui-experimental/configs/v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 6.6s (prepare environment: 1.6s, import torch: 1.8s, import gradio: 0.6s, setup paths: 0.5s, other imports: 0.5s, load scripts: 0.8s, create ui: 0.4s, gradio launch: 0.2s).
Loading VAE weights specified in settings: /Users/user1/stable-diffusion/stable-diffusion-webui-experimental/models/VAE/blessed2_fp16.pt
Applying attention optimization: sub-quadratic... done.
Model loaded in 7.3s (load weights from disk: 0.4s, create model: 1.7s, apply weights to model: 4.1s, apply half(): 0.4s, load VAE: 0.3s, calculate empty prompt: 0.2s).
```

### List of installed extensions

ReActor
ControlNet
Infinite Image Browser

**Comment by Bing-su** [comment]
당신이 --skip-install을 인자로 넘겼고, 설치기는 정직하게 설치를 건너뛰었을 뿐입니다. 이건 버그가 아닙니다.
