### ISSUE TITLE
After update may/12, "images dont match"

### ISSUE THREAD

**Issue by rehvka** [Bing-su/adetailer#48]
Error running postprocess_batch: F:\AI\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py00:00<?, ?it/s]
Traceback (most recent call last):
  File "F:\AI\stable-diffusion-webui\modules\scripts.py", line 463, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "F:\AI\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 615, in postprocess_image
    is_processed |= self._postprocess_image(p, pp, args, n=n)
  File "F:\AI\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 586, in _postprocess_image
    processed = process_images(p2)
  File "F:\AI\stable-diffusion-webui\modules\processing.py", line 526, in process_images
    res = process_images_inner(p)
  File "F:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "F:\AI\stable-diffusion-webui\modules\processing.py", line 615, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "F:\AI\stable-diffusion-webui\modules\processing.py", line 1065, in init
    image_masked.paste(image.convert("RGBA").convert("RGBa"), mask=ImageOps.invert(self.mask_for_overlay.convert('L')))
  File "F:\AI\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 1731, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match

any ideas?

**Comment by rehvka** [comment]
nvm, Im dumb, I just had to update the extension :^)
