### ISSUE TITLE
[Bug]: Hand Fix Bug, controlnet hand refiner error

### ISSUE THREAD

**Issue by AhBumm** [Bing-su/adetailer#484]
### Describe the bug

Can't use controlnet hand refiner to fix hand.

### Screenshots

![screenshot-20240122-133144](https://github.com/Bing-su/adetailer/assets/103174943/b2e3ee9e-ff86-4020-b159-f2e0c41bb293)

### Console logs, from start to end.

```Shell
0: 640x640 1 hand, 3.0ms
Speed: 1.0ms preprocess, 3.0ms inference, 2.3ms postprocess per image at shape (1, 3, 640, 640)
2024-01-22 12:29:11,716 - ControlNet - INFO - unit_separate = False, style_align = False
2024-01-22 12:29:11,970 - ControlNet - WARNING - [depth_hand_refiner.processor_res] Invalid value(-1), using default value 512.
2024-01-22 12:29:11,971 - ControlNet - INFO - Loading model: sai_xl_depth_256lora [73ad23d1]
2024-01-22 12:29:12,078 - ControlNet - INFO - Loaded state_dict from [E:\stable-diffusion-webui\extensions\sd-webui-controlnet\models\sd_control_collection\sai_xl_depth_256lora.safetensors]
2024-01-22 12:29:12,078 - ControlNet - INFO - Using ControlNet lora (SDXL)
2024-01-22 12:29:12,108 - ControlNet - INFO - ControlNet model sai_xl_depth_256lora [73ad23d1] loaded.
2024-01-22 12:29:12,162 - ControlNet - INFO - Loading preprocessor: depth_hand_refiner
2024-01-22 12:29:12,163 - ControlNet - INFO - preprocessor resolution = 1024
set os.environ[OMP_NUM_THREADS] to 4
E:\stable-diffusion-webui\venv\lib\site-packages\scipy\sparse\_index.py:100: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_intXint(row, col, x.flat[0])
=> loading pretrained model E:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\hand_refiner\hr16/ControlNet-HandRefiner-pruned\hrnetv2_w64_imagenet_pretrained.pth
*** Error running process: E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "E:\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1084, in process
        self.controlnet_hack(p)
      File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1069, in controlnet_hack
        self.controlnet_main_entry(p)
      File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 891, in controlnet_main_entry
        detected_map, is_image = preprocessor(
      File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 76, in decorated_func
        return cached_func(*args, **kwargs)
      File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 64, in cached_func
        return func(*args, **kwargs)
      File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 733, in run_model
        self.load_model()
      File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 719, in load_model
        self.model = MeshGraphormerDetector.from_pretrained(
      File "E:\stable-diffusion-webui\venv\lib\site-packages\hand_refiner\__init__.py", line 17, in from_pretrained
        pipeline = MeshGraphormerMediapipe(args)
      File "E:\stable-diffusion-webui\venv\lib\site-packages\hand_refiner\pipeline.py", line 198, in __init__
        self.detector = vision.HandLandmarker.create_from_options(options)
      File "E:\stable-diffusion-webui\venv\lib\site-packages\mediapipe\tasks\python\vision\hand_landmarker.py", line 364, in create_from_options
        return cls(
      File "E:\stable-diffusion-webui\venv\lib\site-packages\mediapipe\tasks\python\vision\core\base_vision_task_api.py", line 70, in __init__
        self._runner = _TaskRunner.create(graph_config, packet_callback)
    RuntimeError: Unable to open file at E:\stable-diffusion-webui\venv\lib\site-packages/E:\stable-diffusion-webui\venv\lib\site-packages\hand_refiner\hand_landmarker.task, errno=22

---
100%|██████████████████████████████████████████████████| 7/7 [00:01<00:00,  6.57it/s]
Total progress: 100%|████████████████████████████████| 31/31 [00:21<00:00,  1.44it/s]
100%|████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.19it/s]
```

**Comment by AhBumm** [comment]
![screenshot-20240122-133337](https://github.com/Bing-su/adetailer/assets/103174943/a0134046-2181-4fa3-8896-e1081ac045fb)
