### ISSUE TITLE
[Bug]: hand_refiner

### ISSUE THREAD

**Issue by thejohnd0e** [Bing-su/adetailer#496]
### Console logs, from start to end.

```Shell
0: 640x448 1 hand, 7.5ms
Speed: 2.6ms preprocess, 7.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 448)
2024-02-06 19:54:31,415 - ControlNet - INFO - unit_separate = False, style_align = False
2024-02-06 19:54:31,415 - ControlNet - WARNING - [depth_hand_refiner.processor_res] Invalid value(-1), using default value 512.
2024-02-06 19:54:31,416 - ControlNet - INFO - Loading model from cache: control_sd15_depth_hand_fp16 [09456e54]
2024-02-06 19:54:31,447 - ControlNet - INFO - Using preprocessor: depth_hand_refiner
2024-02-06 19:54:31,447 - ControlNet - INFO - preprocessor resolution = 512
set os.environ[OMP_NUM_THREADS] to 4
=> loading pretrained model D:\SD\extensions\sd-webui-controlnet\annotator\downloads\hand_refiner\hr16/ControlNet-HandRefiner-pruned\hrnetv2_w64_imagenet_pretrained.pth
*** Error running process: D:\stable-diffusion-main\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-main\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "D:\stable-diffusion-main\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1143, in process
        self.controlnet_hack(p)
      File "D:\stable-diffusion-main\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1128, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\stable-diffusion-main\extensions\sd-webui-controlnet\scripts\controlnet.py", line 969, in controlnet_main_entry
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in input_images]))
      File "D:\stable-diffusion-main\extensions\sd-webui-controlnet\scripts\controlnet.py", line 969, in <listcomp>
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in input_images]))
      File "D:\stable-diffusion-main\extensions\sd-webui-controlnet\scripts\controlnet.py", line 936, in preprocess_input_image
        detected_map, is_image = self.preprocessor[unit.module](
      File "D:\stable-diffusion-main\extensions\sd-webui-controlnet\scripts\utils.py", line 80, in decorated_func
        return cached_func(*args, **kwargs)
      File "D:\stable-diffusion-main\extensions\sd-webui-controlnet\scripts\utils.py", line 64, in cached_func
        return func(*args, **kwargs)
      File "D:\stable-diffusion-main\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "D:\stable-diffusion-main\extensions\sd-webui-controlnet\scripts\processor.py", line 859, in run_model
        self.load_model()
      File "D:\stable-diffusion-main\extensions\sd-webui-controlnet\scripts\processor.py", line 845, in load_model
        self.model = MeshGraphormerDetector.from_pretrained(
      File "D:\stable-diffusion-main\venv\lib\site-packages\hand_refiner\__init__.py", line 17, in from_pretrained
        pipeline = MeshGraphormerMediapipe(args)
      File "D:\stable-diffusion-main\venv\lib\site-packages\hand_refiner\pipeline.py", line 198, in __init__
        self.detector = vision.HandLandmarker.create_from_options(options)
      File "D:\stable-diffusion-main\venv\lib\site-packages\mediapipe\tasks\python\vision\hand_landmarker.py", line 364, in create_from_options
        return cls(
      File "D:\stable-diffusion-main\venv\lib\site-packages\mediapipe\tasks\python\vision\core\base_vision_task_api.py", line 70, in __init__
        self._runner = _TaskRunner.create(graph_config, packet_callback)
    RuntimeError: Unable to open file at D:\stable-diffusion-main\venv\lib\site-packages/D:\stable-diffusion-main\venv\lib\site-packages\hand_refiner\hand_landmarker.task, errno=22
```

### List of installed extensions

![Screenshot - 2024-02-06 18 55 51](https://github.com/Bing-su/adetailer/assets/115493464/988ceb49-0380-4657-bde6-43ce321a2d84)
![Screenshot - 2024-02-06 18 55 20](https://github.com/Bing-su/adetailer/assets/115493464/02cd69eb-ad67-457a-99fa-06836dda2eaa)

**Comment by Bing-su** [comment]
This seems to be a bug in mediapipe.
https://github.com/google/mediapipe/issues/4983
