### ISSUE TITLE
question about inpaint only masked

### ISSUE THREAD

**Issue by Apyr101** [Bing-su/adetailer#5]
with ddetailer I could send image to inpaint, and press only masked and set width/height to 768/768 for example, and it would inpaint the faces at that resolution, when doing the same with adetailer I get an error, is there a different way to do it with adetailer that I'm missing?

```
Arguments: ('task(2rp4l4pchnhlx65)', 2, 'absurdres, highres, best quality, 1girl, ', '(worst quality:2), (low quality:2), (normal quality:2), lowres, jpeg artifacts, signature, watermark, username, blurry, artist name, text, error', [], <PIL.Image.Image image mode=RGBA size=1024x1536 at 0x1ADA5407BB0>, None, {'image': <PIL.Image.Image image mode=RGBA size=1024x1536 at 0x1ADA54074F0>, 'mask': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=1024x1536 at 0x1ADA54075B0>}, None, None, None, None, 20, 15, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.5, -1.0, -1.0, 0, 0, 0, False, 0, 1536, 1024, 1, 0, 1, 32, 0, '', '', '', [], 0, True, 'None', '', '', 30, 32, 0, 0, 4, 0.4, True, 0, True, 528, 1024, 7, 'control_v11p_sd15_inpaint [ebff9138]', 1, False, 'MultiDiffusion', False, 10, 10, 1, 64, False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, False, True, True, False, 3072, 192, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', False, 7, 100, 'Constant', 0, 'Constant', 0, 4, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <controlnet.py.UiControlNetUnit object at 0x000001AC28652980>, 'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUTS:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5', True, 0, 'values', '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1', 'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False, 'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:0\n\nXYZ:::1', False, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, False, 50) {}
Traceback (most recent call last):
  File "C:\Users\apyr\Documents\auto1111\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\apyr\Documents\auto1111\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\apyr\Documents\auto1111\stable-diffusion-webui\modules\img2img.py", line 181, in img2img
    processed = process_images(p)
  File "C:\Users\apyr\Documents\auto1111\stable-diffusion-webui\modules\processing.py", line 515, in process_images
    res = process_images_inner(p)
  File "C:\Users\apyr\Documents\auto1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "C:\Users\apyr\Documents\auto1111\stable-diffusion-webui\modules\processing.py", line 604, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "C:\Users\apyr\Documents\auto1111\stable-diffusion-webui\modules\processing.py", line 1014, in init
    mask = mask.crop(crop_region)
  File "C:\Users\apyr\Documents\auto1111\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 1228, in crop
    raise ValueError(msg)
ValueError: Coordinate 'right' is less than 'left'
```

**Comment by Bing-su** [comment]
The ddetailer does nothing in img2img and goes straight to face detection. In contrast, adetailer goes through the whole process.

This error occurs when you don't specify any masks in inpaint. ddetailer skips everything, so you won't get this error.

If you want similar behaviour in adetailer, you can use adetailer with the denoising strength set to 0 in the image to image tab (not the inpaint tab).

Also, if you set the model to 'None', adetailer will do nothing.

**Comment by Apyr101** [comment]
> The ddetailer does nothing in img2img and goes straight to face detection. In contrast, adetailer goes through the whole process.
> 
> This error occurs when you don't specify any masks in inpaint. ddetailer skips everything, so you won't get this error.
> 
> If you want similar behaviour in adetailer, you can use adetailer with the denoising strength set to 0 in the image to image tab (not the inpaint tab). If you want a specific resolution, use the `use inpaint width/height` option.
> 
> Also, if you set the model to 'None', adetailer will do nothing.

Thanks for your answer, the problem with doing that in the img2img tab with very large images is that you run out of vram unlike with the inpaint only masked option in the inpaint tab.

I found a workaround which is to manually mask the faces in the inpaint tab, then adetailer picks it up and inpaints the faces, it would be nice if this could be automated somehow similar to ddetailer. 

**image size: 3072x2048**
**Time taken: 32.92s Torch active/reserved: 10109/12142 MiB, Sys VRAM: 14522/24576 MiB (59.09%)**
![image](https://user-images.githubusercontent.com/115668490/235993665-1cc1b676-acda-47c3-98b1-73433f81435c.png)
![image](https://user-images.githubusercontent.com/115668490/235993813-0a3209cc-6637-4e70-9024-3921fcd3c9af.png)
![image](https://user-images.githubusercontent.com/115668490/235993880-664bf3f5-1682-4338-8eae-40b4f7b9fbd2.png)
