### ISSUE TITLE
[Bug]: dev分支 commit:a7e6777 启动报错

### ISSUE THREAD

**Issue by Array-Cats** [Bing-su/adetailer#520]
### Describe the bug

A1111版SDwebui，具体信息见Console logs，启动后UI界面没有adetailer相关选项

### Console logs, from start to end.

```Shell
...
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
*** Error loading script: !adetailer.py
    Traceback (most recent call last):
      File "W:\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "W:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "W:\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 38, in <module>
        from adetailer.ui import WebuiInfo, adui, ordinal, suffix
      File "W:\stable-diffusion-webui\extensions\adetailer\adetailer\ui.py", line 12, in <module>
        from controlnet_ext import controlnet_exists, controlnet_forge, get_cn_models
    ImportError: cannot import name 'controlnet_forge' from 'controlnet_ext' (W:\stable-diffusion-webui\extensions\adetailer\controlnet_ext\__init__.py)

---
dirname:  W:\stable-diffusion-webui\localizations
...
```

**Comment by sirjc554** [comment]
Same issue here as well

Error loading script: !adetailer.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "D:\stable-diffusion-webui\venv\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8n.pt
