### ISSUE TITLE
Unable to use ip-adapter_face_id_plus through API

### ISSUE THREAD

**Issue by xiaofantongxuehui** [Bing-su/adetailer#543]
### Question

**parameter information**

```json
{
	"prompt": "<lora:ip-adapter-faceid-plusv2_sd15_lora:1>,upply body",
	"negative_prompt": "EasyNegative,badhandv4,ng_deepnegative_v1_75t,16-token-negative-deliberate-neg,bad_prompt_version2-neg,",
	"steps": 20,
	"cfg_scale": 7,
	"width": 512,
     "height": 768,
	"alwayson_scripts": {
		"controlnet": {
			"args": [
				{
                    "module": "",
                    "model": "ip-adapter-faceid-plusv2_sd15",
					"image": "Replace this with a base64 live portrait image"
				}
			]
		} ,    
		"ADetailer": {
      		"args": [
       			  { 
        		    "ad_model": "face_yolov8n.pt",
        		    "ad_controlnet_model": "Passthrough"
        		  }
      ]
    }
	}
}
```
**Console log information**
```    Traceback (most recent call last):
      File "modules/scripts.py", line 619, in process
        script.process(p, *script_args)
      File "extensions/sd-webui-controlnet/scripts/controlnet.py", line 1283, in process
        self.controlnet_hack(p)
      File "extensions/sd-webui-controlnet/scripts/controlnet.py", line 1268, in controlnet_hack
        self.controlnet_main_entry(p)
      File "extensions/sd-webui-controlnet/scripts/controlnet.py", line 1036, in controlnet_main_entry
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "extensions/sd-webui-controlnet/scripts/controlnet.py", line 1036, in <listcomp>
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "extensions/sd-webui-controlnet/scripts/controlnet.py", line 988, in preprocess_input_image
        detected_map, is_image = self.preprocessor[unit.module](
      File "extensions/sd-webui-controlnet/scripts/utils.py", line 80, in decorated_func
        return cached_func(*args, **kwargs)
      File "extensions/sd-webui-controlnet/scripts/utils.py", line 64, in cached_func
        return func(*args, **kwargs)
      File "extensions/sd-webui-controlnet/scripts/global_state.py", line 37, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "extensions/sd-webui-controlnet/scripts/processor.py", line 834, in face_id_plus
        face_embed, _ = g_insight_face_model.run_model(img)
      File "extensions/sd-webui-controlnet/scripts/processor.py", line 756, in run_model
        raise Exception("Insightface: No face found in image.")
    Exception: Insightface: No face found in image.```
**The uploaded image was inexplicably processed**
![QQ截图20240317000404](https://github.com/Bing-su/adetailer/assets/163082981/c8499346-125c-42e6-be5e-18ce1be4de00)
![2input_image](https://github.com/Bing-su/adetailer/assets/163082981/f644190a-902f-4cd2-95c8-566e4a1312ba)
![6processor py未查到人脸](https://github.com/Bing-su/adetailer/assets/163082981/83856b3c-1b22-4bdd-9e5c-4e80b3ef7083)

**Comment by xiaofantongxuehui** [comment]
{
                    "module": "ip-adapter_face_id_plus",
                    "model": "ip-adapter-faceid-plusv2_sd15",
					"image": "Replace this with a base64 live portrait image"
				}

**Comment by LiJT** [comment]
![image](https://github.com/Bing-su/adetailer/assets/11270197/d1c21892-e477-4fa2-93ad-d5fd2bb74a3d)
Confirm I have about the same issue. It appears a black box to me when i pair with Ipadaptor faceid model..... Adetailer should work after the image is generated, but they only work once and only black box image from now on, I have to unload and reload the model to turn normal
