### ISSUE TITLE
[Bug]: Adetailer Tab gone

### ISSUE THREAD

**Issue by aiuserstevy** [Bing-su/adetailer#549]
### Describe the bug

Hi !
Im mainly using Stabile Diffusion via Vast.Ai. Yesterday all was working perfectly fine.Today the Adetailer Tab is gone when setting up new instances. Tried multiple instances and same issue with all of them.

Heres what the log says:
*** Error loading script: !adetailer.py
    Traceback (most recent call last):
      File "/workspace/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "", line 883, in exec_module
      File "", line 241, in _call_with_frames_removed
      File "/workspace/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 50, in 
        from modules.processing import (
    ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (/workspace/stable-diffusion-webui/modules/processing.py)

Any idea how to solve that?

### Console logs, from start to end.

```Shell
Startup time: 15.3s (launcher: 3.4s, import torch: 4.0s, import gradio: 2.0s, setup paths: 1.4s, other imports: 1.2s, setup codeformer: 0.1s, load scripts: 1.7s, create ui: 1.1s, gradio launch: 0.2s).
31e35c80fc4829d14f90153f4c74cd59c90b779f6afe05a74cd6120b893f7e5b
Loading weights [31e35c80fc] from /workspace/stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_1.0.safetensors
Creating model from config: /workspace/stable-diffusion-webui/repositories/generative-models/configs/inference/sd_xl_base.yaml

Downloading vocab.json:   0%|          | 0.00/961k [00:00 , ?B/s]
Downloading vocab.json: 100%|██████████| 961k/961k [00:00<00:00, 7.15MB/s]
Downloading vocab.json: 100%|██████████| 961k/961k [00:00<00:00, 7.07MB/s]

Downloading merges.txt:   0%|          | 0.00/525k [00:00 , ?B/s]
Downloading merges.txt: 100%|██████████| 525k/525k [00:00<00:00, 5.52MB/s]

Downloading (…)cial_tokens_map.json:   0%|          | 0.00/389 [00:00 , ?B/s]
Downloading (…)cial_tokens_map.json: 100%|██████████| 389/389 [00:00<00:00, 1.28MB/s]

Downloading tokenizer_config.json:   0%|          | 0.00/905 [00:00 , ?B/s]
Downloading tokenizer_config.json: 100%|██████████| 905/905 [00:00<00:00, 3.38MB/s]

Downloading config.json:   0%|          | 0.00/4.52k [00:00 , ?B/s]
Downloading config.json: 100%|██████████| 4.52k/4.52k [00:00<00:00, 11.4MB/s]
*** Error loading script: !adetailer.py
    Traceback (most recent call last):
      File "/workspace/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "", line 883, in exec_module
      File "", line 241, in _call_with_frames_removed
      File "/workspace/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 50, in 
        from modules.processing import (
    ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (/workspace/stable-diffusion-webui/modules/processing.py)

---
Applying attention optimization: xformers... done.
Model loaded in 56.8s (calculate hash: 22.3s, load weights from disk: 1.2s, create model: 2.2s, apply weights to model: 13.1s, apply half(): 14.6s, move model to device: 3.0s, calculate empty prompt: 0.3s).

Restarting UI...
Closing server running on port: 3000
2024-03-22 08:27:39,621 - ControlNet - [0;32mINFO[0m - ControlNet v1.1.238
[W 2024-03-22 08:27:58.132 ServerApp] SSL Error on 7 ('175.100.48.252', 24272): [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1007)
Fri Mar 22 08:28:40 UTC 2024
Collecting bash_kernel
  Using cached bash_kernel-0.9.3-py2.py3-none-any.whl (617 kB)
Requirement already satisfied: ipykernel in ./venv/lib/python3.10/site-packages (from bash_kernel) (6.25.1)
Requirement already satisfied: pexpect>=4.0 in ./venv/lib/python3.10/site-packages (from bash_kernel) (4.8.0)
Requirement already satisfied: ptyprocess>=0.5 in ./venv/lib/python3.10/site-packages (from pexpect>=4.0->bash_kernel) (0.7.0)
Requirement already satisfied: packaging in ./venv/lib/python3.10/site-packages (from ipykernel->bash_kernel) (23.1)
Requirement already satisfied: jupyter-client>=6.1.12 in ./venv/lib/python3.10/site-packages (from ipykernel->bash_kernel) (8.3.0)
Requirement already satisfied: comm>=0.1.1 in ./venv/lib/python3.10/site-packages (from ipykernel->bash_kernel) (0.1.4)
Requirement already satisfied: pyzmq>=20 in ./venv/lib/python3.10/site-packages (from ipykernel->bash_kernel) (25.1.1)
Requirement already satisfied: tornado>=6.1 in ./venv/lib/python3.10/site-packages (from ipykernel->bash_kernel) (6.3.3)
Requirement already satisfied: nest-asyncio in ./venv/lib/python3.10/site-packages (from ipykernel->bash_kernel) (1.5.7)
Requirement already satisfied: traitlets>=5.4.0 in ./venv/lib/python3.10/site-packages (from ipykernel->bash_kernel) (5.9.0)
Requirement already satisfied: psutil in ./venv/lib/python3.10/site-packages (from ipykernel->bash_kernel) (5.9.5)
Requirement already satisfied: matplotlib-inline>=0.1 in ./venv/lib/python3.10/site-packages (from ipykernel->bash_kernel) (0.1.6)
Requirement already satisfied: debugpy>=1.6.5 in ./venv/lib/python3.10/site-packages (from ipykernel->bash_kernel) (1.6.7.post1)
Requirement already satisfied: ipython>=7.23.1 in ./venv/lib/python3.10/site-packages (from ipykernel->bash_kernel) (8.14.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in ./venv/lib/python3.10/site-packages (from ipykernel->bash_kernel) (5.3.1)
Requirement already satisfied: decorator in ./venv/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel->bash_kernel) (5.1.1)
Requirement already satisfied: pickleshare in ./venv/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel->bash_kernel) (0.7.5)
Requirement already satisfied: stack-data in ./venv/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel->bash_kernel) (0.6.2)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in ./venv/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel->bash_kernel) (3.0.39)
Requirement already satisfied: pygments>=2.4.0 in ./venv/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel->bash_kernel) (2.16.1)
Requirement already satisfied: jedi>=0.16 in ./venv/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel->bash_kernel) (0.19.0)
Requirement already satisfied: backcall in ./venv/lib/python3.10/site-packages (from ipython>=7.23.1->ipykernel->bash_kernel) (0.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.10/site-packages (from jupyter-client>=6.1.12->ipykernel->bash_kernel) (2.8.2)
Requirement already satisfied: platformdirs>=2.5 in ./venv/lib/python3.10/site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->bash_kernel) (3.10.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in ./venv/lib/python3.10/site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->bash_kernel) (0.8.3)
Requirement already satisfied: wcwidth in ./venv/lib/python3.10/site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=7.23.1->ipykernel->bash_kernel) (0.2.6)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->ipykernel->bash_kernel) (1.16.0)
Requirement already satisfied: asttokens>=2.1.0 in ./venv/lib/python3.10/site-packages (from stack-data->ipython>=7.23.1->ipykernel->bash_kernel) (2.2.1)
Requirement already satisfied: pure-eval in ./venv/lib/python3.10/site-packages (from stack-data->ipython>=7.23.1->ipykernel->bash_kernel) (0.2.2)
Requirement already satisfied: executing>=1.2.0 in ./venv/lib/python3.10/site-packages (from stack-data->ipython>=7.23.1->ipykernel->bash_kernel) (1.2.0)
Installing collected packages: bash_kernel
Successfully installed bash_kernel-0.9.3
Installing IPython kernel spec
Fri Mar 22 08:28:45 UTC 2024
.........+...+.....+....+.....+.+......+......+..+...+............+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+........+......+.+......+..+.+..+.............+.....+......+.........+................+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.....+............+...+...+........................+...........+.......+....................+.+..+....+...+..+.............+............+...+..+.+..............+.+........+......+.............+..+.+...+.................+.........+....+............+..+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
..+........+.......+........+.......+...+...+...............+..+.+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+.+...+...+..+..........+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+........+......+.+............+..+.+............+..+................+.........+...+..+...+.+..+...+.........+.+.....+.+........+.............+.....+...............+....+...+..+.+.....+.........+....+..+...............+...+....+...+..+......+.+.....+.+.................+.+............+..+......+.+.....+......+...+......+....+.........+.....+.............+.....+...+....+..+...+.+........................+...+..+......+....+...........+......+....+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2627  100  1614  100  1013   4889   3069 --:--:-- --:--:-- --:--:--  7960
[I 2024-03-22 08:28:47.446 ServerApp] jupyter_archive | extension was successfully linked.
[I 2024-03-22 08:28:47.447 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-03-22 08:28:47.452 ServerApp] jupyter_server_terminals | extension was successfully linked.
[W 2024-03-22 08:28:47.454 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-03-22 08:28:47.454 LabApp] 'allow_remote_access' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-03-22 08:28:47.454 LabApp] 'allow_origin' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-03-22 08:28:47.454 LabApp] 'certfile' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-03-22 08:28:47.454 LabApp] 'keyfile' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-03-22 08:28:47.458 ServerApp] ServerApp.token config is deprecated in 2.0. Use IdentityProvider.token.
[I 2024-03-22 08:28:47.459 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-03-22 08:28:47.464 ServerApp] notebook | extension was successfully linked.
[I 2024-03-22 08:28:47.738 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-03-22 08:28:47.757 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-03-22 08:28:47.758 ServerApp] jupyter_archive | extension was successfully loaded.
[I 2024-03-22 08:28:47.760 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-03-22 08:28:47.761 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-03-22 08:28:47.763 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.10/dist-packages/jupyterlab
[I 2024-03-22 08:28:47.763 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 2024-03-22 08:28:47.764 LabApp] Extension Manager is 'pypi'.
[I 2024-03-22 08:28:47.852 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-03-22 08:28:47.856 ServerApp] notebook | extension was successfully loaded.
[I 2024-03-22 08:28:47.856 ServerApp] Serving notebooks from local directory: /
[I 2024-03-22 08:28:47.856 ServerApp] Jupyter Server 2.13.0 is running at:
[I 2024-03-22 08:28:47.856 ServerApp] https://eb0eea496459:8080/tree?token=...
[I 2024-03-22 08:28:47.856 ServerApp]     https://127.0.0.1:8080/tree?token=...
[I 2024-03-22 08:28:47.857 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2024-03-22 08:28:47.862 ServerApp] No web browser found: Error('could not locate runnable browser').
[I 2024-03-22 08:28:47.900 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
```

**Comment by aiuserstevy** [comment]
Here another Log , of another instance, same issue. 

Using TCMalloc: libtcmalloc_minimal.so.4
*** Error loading script: !adetailer.py
    Traceback (most recent call last):
      File "/workspace/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "", line 883, in exec_module
      File "", line 241, in _call_with_frames_removed
      File "/workspace/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 50, in 
        from modules.processing import (
    ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (/workspace/stable-diffusion-webui/modules/processing.py)

---
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Version: v1.5.1
Commit hash: 68f336bd994bed5442ad95bad6b6ad5564a5409a



Launching Web UI with arguments: -f --port 3000 --xformers --skip-install --listen --enable-insecure-extension-access
2024-03-22 09:22:25,340 - ControlNet - [0;32mINFO[0m - ControlNet v1.1.238
ControlNet preprocessor location: /workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2024-03-22 09:22:25,443 - ControlNet - [0;32mINFO[0m - ControlNet v1.1.238
Loading weights [31e35c80fc] from /workspace/stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_1.0.safetensors
[0;32m*Deforum ControlNet support: enabled*[0m
[I 2024-03-22 09:22:52.451 ServerApp] 302 GET /?token=[secret] (@44.201.220.11) 0.80ms
[I 2024-03-22 09:22:52.515 ServerApp] 302 GET /?token=[secret] (@44.202.214.171) 1.16ms

**Comment by Bing-su** [comment]
I used a feature that appeared in webui 1.6.0 to fix something. I'll note that the minimum supported version is 1.6.0.
