### ISSUE TITLE
Error loading script: !adetailer.py with  

### ISSUE THREAD

**Issue by Confuzu** [Bing-su/adetailer#55]
`Error loading script: !adetailer.py
Traceback (most recent call last):
  File "/home/*/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/home/*/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/j*/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 17, in <module>
    from adetailer import (
  File "/home/*/stable-diffusion-webui/extensions/adetailer/adetailer/__init__.py", line 2, in <module>
    from .args import AD_ENABLE, ALL_ARGS, ADetailerArgs, enable_check
  File "/home/*/stable-diffusion-webui/extensions/adetailer/adetailer/args.py", line 23, in <module>
    class ArgsList(UserList):
  File "/home/*/stable-diffusion-webui/extensions/adetailer/adetailer/args.py", line 25, in ArgsList
    def attrs(self) -> tuple[str]:
TypeError: 'type' object is not subscriptable
`
i have the latest AUTOMATIC1111/stable-diffusion-webui 
The  latest adetailer  a0cd6f1d (Sat May 13 06:23:56 2023)  
Linux Mint OS

**Comment by Bing-su** [comment]
Maybe it's time to let python 3.8 go... Fixed. thanks.
