### ISSUE TITLE
[Bug]: 해상도가 16의 배수가 아닐 때 opencv 에러 발생

### ISSUE THREAD

**Issue by kalle07** [Bing-su/adetailer#560]
### Describe the bug

if i put the picture in img2img in tab img2img all fine

but if i put the picture in tab inpaint and draw a mask
resolution error! (682x1024)
if i ONLY change the resolution (680x1024) all runging fine

(i know that different extensions have problems with resolutions that not divisible by 16 or 64)

### Console logs, from start to end.

```Shell
100%|██████████████████████████████████████████████████████████████████████████████████| 17/17 [00:07<00:00,  2.32it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 31/31 [00:23<00:00,  1.33it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 31/31 [00:10<00:00,  2.95it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 31/31 [00:10<00:00,  2.96it/s]
0: 640x448 1 face, 0.0ms
Speed: 0.0ms preprocess, 0.0ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 448)
*** Error running postprocess_image: D:\stable-diffusion\webui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "D:\stable-diffusion\webui\modules\scripts.py", line 856, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\stable-diffusion\webui\extensions\adetailer\adetailer\traceback.py", line 159, in wrapper
        raise error from None
    cv2.error:
    ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
    │                                                   System info                                                    │
    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃             ┃ Value                                                                                          ┃ │
    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │    Platform │ Windows-10-10.0.19045-SP0                                                                      │ │
    │ │      Python │ 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]               │ │
    │ │     Version │ v1.8.0                                                                                         │ │
    │ │      Commit │ bef51aed032c0aaa5cfd80445bc4cf0d85b408b5                                                       │ │
    │ │ Commandline │ ['launch.py']                                                                                  │ │
    │ │   Libraries │ {'torch': '2.0.1+cu118', 'torchvision': '0.15.2+cu118', 'ultralytics': '8.1.31', 'mediapipe':  │ │
    │ │             │ '0.10.9'}                                                                                      │ │
    │ └─────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘ │
    │                                                      Inputs                                                      │
    │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃                 ┃ Value                                                                                      ┃ │
    │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │          prompt │ vero07 looking at viewer <lora:vero07_015_cosineR3_iter2_                                  │ │
    │ │                 │ 0000008all_my1_adafactor_epoches8_64_32_03_scale1_add5images:1>                            │ │
    │ │ negative_prompt │                                                                                            │ │
    │ │          n_iter │ 1                                                                                          │ │
    │ │      batch_size │ 1                                                                                          │ │
    │ │           width │ 683                                                                                        │ │
    │ │          height │ 1024                                                                                       │ │
    │ │    sampler_name │ DPM++ 3M SDE Karras                                                                        │ │
    │ │       enable_hr │ False                                                                                      │ │
    │ │     hr_upscaler │                                                                                            │ │
    │ │      checkpoint │ inpaint\SDXL_inpaint_myown7of9_v1.safetensors [8c38194633]                                 │ │
    │ │             vae │ None                                                                                       │ │
    │ │            unet │ None                                                                                       │ │
    │ └─────────────────┴────────────────────────────────────────────────────────────────────────────────────────────┘ │
    │                                                    ADetailer                                                     │
    │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃                     ┃ Value                                                                                  ┃ │
    │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │             version │ 24.3.2                                                                                 │ │
    │ │            ad_model │ face_yolov8n.pt                                                                        │ │
    │ │           ad_prompt │ young girl named vero07 looking at viewer  <lora:vero07_015_cosineR3_iter2_            │ │
    │ │                     │ 0000008all_my1_adafactor_epoches8_64_32_03_scale1_add5images:1>                        │ │
    │ │  ad_negative_prompt │                                                                                        │ │
    │ │ ad_controlnet_model │ None                                                                                   │ │
    │ │              is_api │ False                                                                                  │ │
    │ └─────────────────────┴────────────────────────────────────────────────────────────────────────────────────────┘ │
    │ ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮             │
    │ │ D:\stable-diffusion\webui\extensions\adetailer\adetailer\traceback.py:139 in wrapper             │             │
    │ │                                                                                                  │             │
    │ │   138 │   │   try:                                                                               │             │
    │ │ ❱ 139 │   │   │   return func(*args, **kwargs)                                                   │             │
    │ │   140 │   │   except Exception as e:                                                             │             │
    │ │                                                                                                  │             │
    │ │ D:\stable-diffusion\webui\extensions\adetailer\scripts\!adetailer.py:814 in postprocess_image    │             │
    │ │                                                                                                  │             │
    │ │    813 │   │   │   │   │   continue                                                              │             │
    │ │ ❱  814 │   │   │   │   is_processed |= self._postprocess_image_inner(p, pp, args, n=n)           │             │
    │ │    815                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ D:\stable-diffusion\webui\extensions\adetailer\scripts\!adetailer.py:739 in                      │             │
    │ │ _postprocess_image_inner                                                                         │             │
    │ │                                                                                                  │             │
    │ │    738 │   │                                                                                     │             │
    │ │ ❱  739 │   │   masks = self.pred_preprocessing(p, pred, args)                                    │             │
    │ │    740 │   │   shared.state.assign_current_image(pred.preview)                                   │             │
    │ │                                                                                                  │             │
    │ │ D:\stable-diffusion\webui\extensions\adetailer\scripts\!adetailer.py:593 in pred_preprocessing   │             │
    │ │                                                                                                  │             │
    │ │    592 │   │   │   image_mask = self.get_image_mask(p)                                           │             │
    │ │ ❱  593 │   │   │   masks = self.inpaint_mask_filter(image_mask, masks)                           │             │
    │ │    594 │   │   return masks                                                                      │             │
    │ │                                                                                                  │             │
    │ │ D:\stable-diffusion\webui\extensions\adetailer\scripts\!adetailer.py:656 in inpaint_mask_filter  │             │
    │ │                                                                                                  │             │
    │ │    655 │   ) -> list[Image.Image]:                                                               │             │
    │ │ ❱  656 │   │   return [mask for mask in ad_mask if has_intersection(img2img_mask, mask)]         │             │
    │ │    657                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ D:\stable-diffusion\webui\extensions\adetailer\scripts\!adetailer.py:656 in <listcomp>           │             │
    │ │                                                                                                  │             │
    │ │    655 │   ) -> list[Image.Image]:                                                               │             │
    │ │ ❱  656 │   │   return [mask for mask in ad_mask if has_intersection(img2img_mask, mask)]         │             │
    │ │    657                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ D:\stable-diffusion\webui\extensions\adetailer\adetailer\mask.py:96 in has_intersection          │             │
    │ │                                                                                                  │             │
    │ │    95 │   arr2 = np.array(ensure_pil_image(im2, "L"))                                            │             │
    │ │ ❱  96 │   return not is_all_black(cv2.bitwise_and(arr1, arr2))                                   │             │
    │ │    97                                                                                            │             │
    │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯             │
    │ error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\arithm.cpp:214: error: (-209:Sizes │
    │ of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and  │
    │ type), nor 'array op scalar', nor 'scalar op array' in function 'cv::binary_op'                                  │
    │                                                                                                                  │
    ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 31/31 [00:11<00:00,  2.66it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 31/31 [00:11<00:00,  2.96it/s]
```

**Comment by Bing-su** [comment]
제보에 감사합니다. 해당 문제를 고친 버전을 업로드했습니다.
