### ISSUE TITLE
[Bug]: SDWebui 1.9中AD插件与高清修复功能共同启用时报错

### ISSUE THREAD

**Issue by trojan-uma** [Bing-su/adetailer#576]
### Describe the bug

SDWebui 1.9版本中，同时开启高清修复和AD插件时会出现Console logs中的错误，关闭其中任意一项就不会报错

### Steps to reproduce

输入参数，勾选高清修复/AD，点击生成图片

### Console logs, from start to end.

```Shell
Python 3.10.14+ (heads/3.10:812245ecce, Mar 30 2024, 12:10:58) [MSC v.1939 64 bit (AMD64)]
Version: v1.9.0
Commit hash: adadb4e3c7382bf3e4f7519126cd6c70f4f8557b
Launching Web UI with arguments: --medvram-sdxl --theme dark --port 65500 --xformers --xformers-flash-attention --opt-channelslast --api
CHv1.8.4: Get Custom Model Folder
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.4.1-dev.0, num models: 21
dirname:  W:\stable-diffusion-webui\localizations
localizations:  {'I18N_sd-webui-zh_CN': 'W:\\stable-diffusion-webui\\localizations\\I18N_sd-webui-zh_CN.json', '简体中文语言包_RunawayOrange': 'W:\\stable-diffusion-webui\\extensions\\SD-WebUI-Localization_ZH_CN\\localizations\\简体中文语言包_RunawayOrange.json'}
ControlNet preprocessor location: W:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-04-13 15:43:05,636 - ControlNet - INFO - ControlNet v1.1.443
2024-04-13 15:43:05,838 - ControlNet - INFO - ControlNet v1.1.443
sd-webui-prompt-all-in-one background API service started successfully.
[DanTagGen]-INFO: Llama-cpp-python/gguf model loaded
Loading weights [43177f6d1c] from W:\stable-diffusion-webui\models\Stable-diffusion\C\2D\laridaeV1_chlidonias.safetensors
CHv1.8.4: Set Proxy: http://127.0.0.1:8084
Creating model from config: W:\stable-diffusion-webui\configs\v1-inference.yaml
2024-04-13 15:43:08,764 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:65500
Loading VAE weights specified in settings: W:\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: xformers... done.

To create a public link, set `share=True` in `launch()`.
🤯 LobeTheme: Initializing...
Model loaded in 10.0s (load weights from disk: 0.1s, create model: 0.4s, apply weights to model: 2.5s, apply dtype to VAE: 0.1s, load VAE: 0.7s, load textual inversion embeddings: 1.2s, calculate empty prompt: 4.8s).
[sd-webui-prompt-all-in-one] Loading model facebook/mbart-large-50-many-to-many-mmt from W:\stable-diffusion-webui\extensions\sd-webui-prompt-all-in-one\models...
[sd-webui-prompt-all-in-one] Model facebook/mbart-large-50-many-to-many-mmt loaded.
Startup time: 54.7s (prepare environment: 8.0s, import torch: 4.6s, import gradio: 0.9s, setup paths: 3.3s, initialize shared: 0.4s, other imports: 0.5s, load scripts: 9.1s, create ui: 1.9s, gradio launch: 3.9s, add APIs: 1.3s, app_started_callback: 20.8s).
LoRA Block weight (lora): still_in_love_V1.2: (Te:0.8,Unet:0.8) x [1.0, 0, 1.0, 1.0, 0, 1.0, 1.0, 0, 0.0, 0.0, 0, 0, 0, 0.0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0]
[['diffusion_model_out_2'], ['diffusion_model_time_embed_0'], ['diffusion_model_time_embed_2']]
LoRA Block weight (lora): still_in_love_V1.2: (Te:0.8,Unet:0.8) x [1.0, 0, 1.0, 1.0, 0, 1.0, 1.0, 0, 0.0, 0.0, 0, 0, 0, 0.0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0]
[['diffusion_model_out_2'], ['diffusion_model_time_embed_0'], ['diffusion_model_time_embed_2']]

0: 640x448 2 hands, 62.6ms
Speed: 2.1ms preprocess, 62.6ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 448)
LoRA Block weight (lora): still_in_love_V1.2: (Te:0.8,Unet:0.8) x [1.0, 0, 1.0, 1.0, 0, 1.0, 1.0, 0, 0.0, 0.0, 0, 0, 0, 0.0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0]
[['diffusion_model_out_2'], ['diffusion_model_time_embed_0'], ['diffusion_model_time_embed_2']]
*** Error creating infotext for key "Hires prompt"
    Traceback (most recent call last):
      File "W:\stable-diffusion-webui\modules\processing.py", line 809, in create_infotext
        generation_params[key] = value(**locals())
      File "W:\stable-diffusion-webui\modules\processing.py", line 1259, in get_hr_prompt
        hr_prompt = p.all_hr_prompts[index]
    AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'all_hr_prompts'

---
*** Error creating infotext for key "Hires negative prompt"
    Traceback (most recent call last):
      File "W:\stable-diffusion-webui\modules\processing.py", line 809, in create_infotext
        generation_params[key] = value(**locals())
      File "W:\stable-diffusion-webui\modules\processing.py", line 1263, in get_hr_negative_prompt
        hr_negative_prompt = p.all_hr_negative_prompts[index]
    AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'all_hr_negative_prompts'

---
*** Error creating infotext for key "Hires prompt"
    Traceback (most recent call last):
      File "W:\stable-diffusion-webui\modules\processing.py", line 809, in create_infotext
        generation_params[key] = value(**locals())
      File "W:\stable-diffusion-webui\modules\processing.py", line 1259, in get_hr_prompt
        hr_prompt = p.all_hr_prompts[index]
    AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'all_hr_prompts'

---
*** Error creating infotext for key "Hires negative prompt"
    Traceback (most recent call last):
      File "W:\stable-diffusion-webui\modules\processing.py", line 809, in create_infotext
        generation_params[key] = value(**locals())
      File "W:\stable-diffusion-webui\modules\processing.py", line 1263, in get_hr_negative_prompt
        hr_negative_prompt = p.all_hr_negative_prompts[index]
    AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'all_hr_negative_prompts'

---
```

**Comment by weiligudesankeyou** [comment]
same issue.

**Comment by dauuuuuu** [comment]
T.T I’m the same

**Comment by Bing-su** [comment]
谢谢
