### ISSUE TITLE
[Bug]: A1111 1.9.0's new "--no-prompt-history" causes issues

### ISSUE THREAD

**Issue by bobba84** [Bing-su/adetailer#585]
### Describe the bug

If you add --no-prompt-history as a command line arg to a new A1111 1.9.0 installation (this is a NEW feature in 1.9.0) then it never makes a params.txt file - therefore ADetailer will crash saying this file cannot be found.

I got around the crash by manually creating a blank params.txt file BUT - I'm not sure if it ALSO creates issues for ADetailer as it cannot use this file to obtain the parameters / prompts used for the image generation?

### Steps to reproduce

1. Install fresh A1111 1.9.0
2. Add --no-prompt-history to CMDLINE_ARGS before ever making an image.
3. Install ADetailer Extension and restart
4. Try using ADetailer, it will crash

### Console logs, from start to end.

```Shell
*** Error running postprocess_image: D:\Apps\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "D:\Apps\stable-diffusion-webui\modules\scripts.py", line 897, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\Apps\stable-diffusion-webui\extensions\adetailer\adetailer\traceback.py", line 159, in wrapper
        raise error from None
    FileNotFoundError:
    ╭──────────────────────────────────────────────────────────────────────────╮
    │                               System info                                │
    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃             ┃ Value                                                  ┃ │
    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │    Platform │ Windows-10-10.0.22631-SP0                              │ │
    │ │      Python │ 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49)   │ │
    │ │             │ [MSC v.1932 64 bit (AMD64)]                            │ │
    │ │     Version │ v1.9.0                                                 │ │
    │ │      Commit │ adadb4e3c7382bf3e4f7519126cd6c70f4f8557b               │ │
    │ │ Commandline │ ['launch.py', '--no-half-vae', '--medvram-sdxl',       │ │
    │ │             │ '--xformers', '--listen', '--no-prompt-history',       │ │
    │ │             │ '--enable-insecure-extension-access']                  │ │
    │ │   Libraries │ {'torch': '2.1.2+cu121', 'torchvision':                │ │
    │ │             │ '0.16.2+cu121', 'ultralytics': '8.1.47', 'mediapipe':  │ │
    │ │             │ '0.10.11'}                                             │ │
    │ └─────────────┴────────────────────────────────────────────────────────┘ │
    │                            Inputs                                        │
    │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓            │
    │ ┃                 ┃ Value                                   ┃            │
    │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩            │
    │ │          prompt │ a man standing on a stage               │            │
    │ │ negative_prompt │  easynegative  BadDream                 │            │
    │ │          n_iter │ 1                                       │            │
    │ │      batch_size │ 1                                       │            │
    │ │           width │ 512                                     │            │
    │ │          height │ 512                                     │            │
    │ │    sampler_name │ DPM++ 2M                                │            │
    │ │       enable_hr │ True                                    │            │
    │ │     hr_upscaler │ 4xUltrasharp_4xUltrasharpV10            │            │
    │ │      checkpoint │ zavychromaxl_v60.safetensors            │            │
    │ │             vae │ Automatic                               │            │
    │ │            unet │ Automatic                               │            │
    │ └─────────────────┴─────────────────────────────────────────┘            │
    │                 ADetailer                                                │
    │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓                                │
    │ ┃                     ┃ Value           ┃                                │
    │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩                                │
    │ │             version │ 24.4.1          │                                │
    │ │            ad_model │ face_yolov8n.pt │                                │
    │ │           ad_prompt │                 │                                │
    │ │  ad_negative_prompt │                 │                                │
    │ │ ad_controlnet_model │ None            │                                │
    │ │              is_api │ False           │                                │
    │ └─────────────────────┴─────────────────┘                                │
    │ ╭───────────────── Traceback (most recent call last) ──────────────────╮ │
    │ │ D:\Apps\stable-diffusion-webui\extensions\adetailer\adetailer\traceb │ │
    │ │ ack.py:139 in wrapper                                                │ │
    │ │                                                                      │ │
    │ │   138 │   │   try:                                                   │ │
    │ │ ❱ 139 │   │   │   return func(*args, **kwargs)                       │ │
    │ │   140 │   │   except Exception as e:                                 │ │
    │ │                                                                      │ │
    │ │ D:\Apps\stable-diffusion-webui\extensions\adetailer\scripts\!adetail │ │
    │ │ er.py:786 in postprocess_image                                       │ │
    │ │                                                                      │ │
    │ │    785 │   │   arg_list = self.get_args(p, *args_)                   │ │
    │ │ ❱  786 │   │   params_txt_content = Path(paths.data_path, "params.tx │ │
    │ │    787                                                               │ │
    │ │                                                                      │ │
    │ │ C:\Users\Bobby                                                       │ │
    │ │ Evans\AppData\Local\Programs\Python\Python310\lib\pathlib.py:1134 in │ │
    │ │ read_text                                                            │ │
    │ │                                                                      │ │
    │ │   1133 │   │   encoding = io.text_encoding(encoding)                 │ │
    │ │ ❱ 1134 │   │   with self.open(mode='r', encoding=encoding, errors=er │ │
    │ │   1135 │   │   │   return f.read()                                   │ │
    │ │                                                                      │ │
    │ │ C:\Users\Bobby                                                       │ │
    │ │ Evans\AppData\Local\Programs\Python\Python310\lib\pathlib.py:1119 in │ │
    │ │ open                                                                 │ │
    │ │                                                                      │ │
    │ │   1118 │   │   │   encoding = io.text_encoding(encoding)             │ │
    │ │ ❱ 1119 │   │   return self._accessor.open(self, mode, buffering, enc │ │
    │ │   1120 │   │   │   │   │   │   │   │      newline)                   │ │
    │ ╰──────────────────────────────────────────────────────────────────────╯ │
    │ FileNotFoundError: [Errno 2] No such file or directory:                  │
    │ 'D:\\Apps\\stable-diffusion-webui\\params.txt'                           │
    ╰──────────────────────────────────────────────────────────────────────────╯
```

### List of installed extensions

ADetailer

**Comment by bobba84** [comment]
Good bot, but we still don't know why adetailer needs the params.txt file - maybe something won't work properly if it does not have the relevant prompts etc in it?

**Comment by Bing-su** [comment]
Because adetailer overwrites the history with undesired contents, it reads and writes to that file only to maintain the history.

**Comment by bobba84** [comment]
Strange that you closed it as not planned, even though you fixed the issue I was talking about in https://github.com/Bing-su/adetailer/commit/93d223f130d39b04f0a5f4ca2a193e9acc85f1ab
