### ISSUE TITLE
Fresh Install !adetailer.py issue

### ISSUE THREAD

**Issue by smasonlawrence** [Bing-su/adetailer#586]
### Question

I lost my SDD and ended up having to start from scratch, installed a new instance of Automatic1111 and adetailer, but am getting the following error.

*** Error loading script: !adetailer.py
    Traceback (most recent call last):
      File "X:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "X:\Stable Diffusion\stable-diffusion-webui\modules\script_loading.py", line 14, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "X:\Stable Diffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 33, in <module>
        from adetailer import (
      File "X:\Stable Diffusion\stable-diffusion-webui\extensions\adetailer\adetailer\__init__.py", line 2, in <module>
        from .args import ALL_ARGS, ADetailerArgs
      File "X:\Stable Diffusion\stable-diffusion-webui\extensions\adetailer\adetailer\args.py", line 55, in <module>
        class ADetailerArgs(BaseModel, extra=Extra.forbid):
      File "pydantic\main.py", line 178, in pydantic.main.ModelMetaclass.__new__
      File "pydantic\typing.py", line 396, in pydantic.typing.resolve_annotations
    TypeError: ForwardRef.__init__() got an unexpected keyword argument 'is_class'

Pydantic is installed, version 1.10.11, do I have the wrong version or is this not related to pydantic at all?

**Comment by smasonlawrence** [comment]
Any other advice from anybody? Pydantic 1.10.8 didnt work and downgrading to 23.5.8 works, but is not ideal as it's grossly outdated.

**Comment by Bing-su** [comment]
It's probably a Python version problem. Try upgrading your Python version to the latest version out of version 3.10.

**Comment by smasonlawrence** [comment]
Figured this all out in the event someone else has the same issue, removed python and its caches, removed sd installation, reinstalled everything from scratch, now its working.. I assume there was a left over file someplace that was used during the install that broke everything else. Fresh install did the trick.
