### ISSUE TITLE
adetailer stopped showing in My A1111

### ISSUE THREAD

**Issue by Zak088** [Bing-su/adetailer#6]
Hello, Yesterday everything was working great but today when I started My webui adetailer was gone I updated it but still not showin and I get this error in my terminal window , btw I am on mac system 

`Error loading script: !adetailer.py`

it was really great extension and I don't know what Happened !!??

**Comment by Bing-su** [comment]
Are you using Python 3.8?

**Comment by Bing-su** [comment]
Can you post the full error log?

**Comment by Zak088** [comment]
yeah sure, btw now it is working but only face_yolov8s is working and the others I get this error 

```
Error running postprocess_batch: /Users/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py
Traceback (most recent call last):
  File "/Users/stable-diffusion-webui/modules/scripts.py", line 462, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "/Users/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 461, in postprocess_image
    pred = predictor(ad_model, pp.image, args.ad_conf, **kwargs)
  File "/Users/stable-diffusion-webui/extensions/adetailer/adetailer/mediapipe.py", line 13, in mediapipe_predict
    import mediapipe as mp
  File "/Users/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/__init__.py", line 16, in <module>
    import mediapipe.python.solutions as solutions
  File "/Users/table-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/python/solutions/__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "/Users/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/python/solutions/drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "/Users/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/python/solutions/drawing_utils.py", line 24, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "/Users/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/framework/formats/detection_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/Users/stable-diffusion-webui/venv/lib/python3.10/site-packages/google/protobuf/internal/__init__.py)
```

**Comment by Bing-su** [comment]
Well, you might want to try reinstalling protobuf.

https://stackoverflow.com/questions/71759248/importerror-cannot-import-name-builder-from-google-protobuf-internal
