### ISSUE TITLE
[Issue] Cant reinstall - always same error: Error loading script: !adetailer.py

### ISSUE THREAD

**Issue by Rogal80** [Bing-su/adetailer#67]
hi, after removing an instal again i have this issue :(

Error loading script: !adetailer.py
Traceback (most recent call last):
  File "I:\Github\Web_UI\webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "I:\Github\Web_UI\webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "I:\Github\Web_UI\webui\extensions\adetailer\scripts\!adetailer.py", line 29, in <module>
    from sd_webui.paths import data_path, models_path
  File "I:\Github\Web_UI\webui\extensions\adetailer\sd_webui\paths.py", line 14, in <module>
    from modules.paths import (
ImportError: cannot import name 'extensions_builtin_dir' from 'modules.paths' (I:\Github\Web_UI\webui\modules\paths.py)

**Comment by anonCantCode** [comment]
Same issue.

**Comment by ToniMagi** [comment]
Sorry, I'm not a programmer. How and where is this edit made? Thank you!

**Comment by Bing-su** [comment]
Fixed, sorry.
