### ISSUE TITLE
[Question] If the resolution is odd, face Detailer does not work.

### ISSUE THREAD

**Issue by Tktw** [Bing-su/adetailer#70]
txt2img 512x683
`Error running postprocess_batch: C:\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 463, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "C:\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 494, in postprocess_image
    is_processed |= self._postprocess_image(p, pp, args, n=n)
  File "C:\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 465, in _postprocess_image
    processed = process_images(p2)
  File "C:\stable-diffusion-webui\modules\processing.py", line 526, in process_images
    res = process_images_inner(p)
  File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "C:\stable-diffusion-webui\modules\processing.py", line 615, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "C:\stable-diffusion-webui\modules\processing.py", line 1035, in init
    image_mask = images.resize_image(2, mask, self.width, self.height)
  File "C:\stable-diffusion-webui\modules\images.py", line 308, in resize_image
    res.paste(resized.resize((fill_width, height), box=(0, 0, 0, height)), box=(0, 0))
  File "C:\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 2192, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: height and width must be > 0`

I know I shouldn't use odd numbers, but can you fix it?

**Comment by Bing-su** [comment]
I'm sorry. This is not something I can fix.

**Comment by Tktw** [comment]
Okay, Thank you for your answer. 👍

**Comment by mongalong247** [comment]
If you select the option "use separate width/height" it will work.

**Comment by Tktw** [comment]
@mongalong247 
I don't know what this option does, so I didn't use it, but I tried it and it seems to work.
Thank you!
