### ISSUE TITLE
[Bug]: Unable to install adetailer in SD.Next

### ISSUE THREAD

**Issue by hw25io** [Bing-su/adetailer#705]
### Describe the bug

When trying to install adetailer in the most recent version of SD.next, the installation fails with the error message ""subprocess.CalledProcessError: Command '['D:\\SD-Next\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'ultralytics>=8.2.0', 'mediapipe>=0.10.13']' returned non-zero exit status 1.".

The error near the end ("ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'D:\\SD-Next\\venv\\Lib\\site-packages\\cv2\\cv2.pyd'  Check the permissions.") i had several times earlier and didn't prevent the installation.

Complete log of the installation:

```
12:31:09-020568 INFO     Extension install: https://github.com/Bing-su/adetailer
12:31:09-020568 INFO     Installing extension: https://github.com/Bing-su/adetailer into extensions\adetailer
12:31:10-925391 DEBUG    Running extension installer: D:\SD-Next\extensions\adetailer\install.py
12:31:16-801091 ERROR    Error running extension installer: D:\SD-Next\extensions\adetailer\install.py
12:31:16-802092 DEBUG    Collecting ultralytics>=8.2.0
                           Using cached ultralytics-8.2.87-py3-none-any.whl (872 kB)
                         Collecting mediapipe>=0.10.13
                           Using cached mediapipe-0.10.14-cp310-cp310-win_amd64.whl (50.8 MB)
                         Collecting py-cpuinfo
                           Using cached py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)
                         Requirement already satisfied: pandas>=1.1.4 in d:\sd-next\venv\lib\site-packages (from ultralytics>=8.2.0) (2.2.2)
                         Requirement already satisfied: opencv-python>=4.6.0 in d:\sd-next\venv\lib\site-packages (from ultralytics>=8.2.0) (4.10.0.84)
                         Requirement already satisfied: pyyaml>=5.3.1 in d:\sd-next\venv\lib\site-packages (from ultralytics>=8.2.0) (6.0.2)
                         Requirement already satisfied: matplotlib>=3.3.0 in d:\sd-next\venv\lib\site-packages (from ultralytics>=8.2.0) (3.9.2)
                         Requirement already satisfied: tqdm>=4.64.0 in d:\sd-next\venv\lib\site-packages (from ultralytics>=8.2.0) (4.66.4)
                         Requirement already satisfied: psutil in d:\sd-next\venv\lib\site-packages (from ultralytics>=8.2.0) (6.0.0)
                         Collecting torch<2.4.0,>=1.8.0
                           Using cached torch-2.3.1-cp310-cp310-win_amd64.whl (159.8 MB)
                         Requirement already satisfied: numpy<2.0.0,>=1.23.0 in d:\sd-next\venv\lib\site-packages (from ultralytics>=8.2.0) (1.26.4)
                         Requirement already satisfied: requests>=2.23.0 in d:\sd-next\venv\lib\site-packages (from ultralytics>=8.2.0) (2.31.0)
                         Requirement already satisfied: torchvision>=0.9.0 in d:\sd-next\venv\lib\site-packages (from ultralytics>=8.2.0) (0.19.1+cu124)
                         Collecting seaborn>=0.11.0
                           Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
                         Requirement already satisfied: scipy>=1.4.1 in d:\sd-next\venv\lib\site-packages (from ultralytics>=8.2.0) (1.14.1)
                         Collecting ultralytics-thop>=2.0.0
                           Using cached ultralytics_thop-2.0.6-py3-none-any.whl (26 kB)
                         Requirement already satisfied: pillow>=7.1.2 in d:\sd-next\venv\lib\site-packages (from ultralytics>=8.2.0) (10.4.0)
                         Requirement already satisfied: absl-py in d:\sd-next\venv\lib\site-packages (from mediapipe>=0.10.13) (2.1.0)
                         Collecting jaxlib
                           Using cached jaxlib-0.4.31-cp310-cp310-win_amd64.whl (56.3 MB)
                         Collecting opencv-contrib-python
                           Using cached opencv_contrib_python-4.10.0.84-cp37-abi3-win_amd64.whl (45.5 MB)
                         Requirement already satisfied: protobuf<5,>=4.25.3 in d:\sd-next\venv\lib\site-packages (from mediapipe>=0.10.13) (4.25.3)
                         Requirement already satisfied: attrs>=19.1.0 in d:\sd-next\venv\lib\site-packages (from mediapipe>=0.10.13) (24.2.0)
                         Collecting sounddevice>=0.4.4
                           Using cached sounddevice-0.5.0-py3-none-win_amd64.whl (189 kB)
                         Collecting jax
                           Using cached jax-0.4.31-py3-none-any.whl (2.0 MB)
                         Requirement already satisfied: flatbuffers>=2.0 in d:\sd-next\venv\lib\site-packages (from mediapipe>=0.10.13) (24.3.25)
                         Requirement already satisfied: kiwisolver>=1.3.1 in d:\sd-next\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.2.0)       
                         (1.4.6)
                         Requirement already satisfied: contourpy>=1.0.1 in d:\sd-next\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.2.0) (1.3.0)                         Requirement already satisfied: packaging>=20.0 in d:\sd-next\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.2.0) (24.1)  
                         Requirement already satisfied: python-dateutil>=2.7 in d:\sd-next\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.2.0)    
                         (2.9.0.post0)
                         Requirement already satisfied: fonttools>=4.22.0 in d:\sd-next\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.2.0)       
                         (4.53.1)
                         Requirement already satisfied: pyparsing>=2.3.1 in d:\sd-next\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.2.0) (3.1.4)                         Requirement already satisfied: cycler>=0.10 in d:\sd-next\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.2.0) (0.12.1)   
                         Requirement already satisfied: pytz>=2020.1 in d:\sd-next\venv\lib\site-packages (from pandas>=1.1.4->ultralytics>=8.2.0) (2024.1)       
                         Requirement already satisfied: tzdata>=2022.7 in d:\sd-next\venv\lib\site-packages (from pandas>=1.1.4->ultralytics>=8.2.0) (2024.1)     
                         Requirement already satisfied: certifi>=2017.4.17 in d:\sd-next\venv\lib\site-packages (from requests>=2.23.0->ultralytics>=8.2.0)       
                         (2024.8.30)
                         Requirement already satisfied: idna<4,>=2.5 in d:\sd-next\venv\lib\site-packages (from requests>=2.23.0->ultralytics>=8.2.0) (3.8)       
                         Requirement already satisfied: charset-normalizer<4,>=2 in d:\sd-next\venv\lib\site-packages (from requests>=2.23.0->ultralytics>=8.2.0) 
                         (3.3.2)
                         Requirement already satisfied: urllib3<3,>=1.21.1 in d:\sd-next\venv\lib\site-packages (from requests>=2.23.0->ultralytics>=8.2.0)       
                         (1.26.19)
                         Collecting CFFI>=1.0
                           Using cached cffi-1.17.0-cp310-cp310-win_amd64.whl (180 kB)
                         Collecting mkl<=2021.4.0,>=2021.1.1
                           Using cached mkl-2021.4.0-py2.py3-none-win_amd64.whl (228.5 MB)
                         Requirement already satisfied: filelock in d:\sd-next\venv\lib\site-packages (from torch<2.4.0,>=1.8.0->ultralytics>=8.2.0) (3.13.1)     
                         Requirement already satisfied: jinja2 in d:\sd-next\venv\lib\site-packages (from torch<2.4.0,>=1.8.0->ultralytics>=8.2.0) (3.1.3)        
                         Requirement already satisfied: fsspec in d:\sd-next\venv\lib\site-packages (from torch<2.4.0,>=1.8.0->ultralytics>=8.2.0) (2024.2.0)     
                         Requirement already satisfied: networkx in d:\sd-next\venv\lib\site-packages (from torch<2.4.0,>=1.8.0->ultralytics>=8.2.0) (3.2.1)      
                         Requirement already satisfied: typing-extensions>=4.8.0 in d:\sd-next\venv\lib\site-packages (from
                         torch<2.4.0,>=1.8.0->ultralytics>=8.2.0) (4.11.0)
                         Requirement already satisfied: sympy in d:\sd-next\venv\lib\site-packages (from torch<2.4.0,>=1.8.0->ultralytics>=8.2.0) (1.13.2)        
                         Collecting torchvision>=0.9.0
                           Using cached torchvision-0.19.0-1-cp310-cp310-win_amd64.whl (1.3 MB)
                           Using cached torchvision-0.18.1-cp310-cp310-win_amd64.whl (1.2 MB)
                         Requirement already satisfied: colorama in d:\sd-next\venv\lib\site-packages (from tqdm>=4.64.0->ultralytics>=8.2.0) (0.4.6)
                         Collecting opt-einsum
                           Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
                         Collecting ml-dtypes>=0.2.0
                           Using cached ml_dtypes-0.4.0-cp310-cp310-win_amd64.whl (126 kB)
                         Collecting pycparser
                           Using cached pycparser-2.22-py3-none-any.whl (117 kB)
                         Collecting intel-openmp==2021.*
                           Using cached intel_openmp-2021.4.0-py2.py3-none-win_amd64.whl (3.5 MB)
                         Collecting tbb==2021.*
                           Using cached tbb-2021.13.1-py3-none-win_amd64.whl (286 kB)
                         Requirement already satisfied: six>=1.5 in d:\sd-next\venv\lib\site-packages (from
                         python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics>=8.2.0) (1.16.0)
                         Requirement already satisfied: MarkupSafe>=2.0 in d:\sd-next\venv\lib\site-packages (from
                         jinja2->torch<2.4.0,>=1.8.0->ultralytics>=8.2.0) (2.1.5)
                         Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\sd-next\venv\lib\site-packages (from
                         sympy->torch<2.4.0,>=1.8.0->ultralytics>=8.2.0) (1.3.0)
                         Installing collected packages: tbb, py-cpuinfo, intel-openmp, pycparser, opt-einsum, opencv-contrib-python, ml-dtypes, mkl, torch,       
                         jaxlib, CFFI, ultralytics-thop, torchvision, sounddevice, seaborn, jax, ultralytics, mediapipe

                         ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'D:\\SD-Next\\venv\\Lib\\site-packages\\cv2\\cv2.pyd'                         Check the permissions.


                         [notice] A new release of pip is available: 23.0.1 -> 24.2
                         [notice] To update, run: D:\SD-Next\venv\Scripts\python.exe -m pip install --upgrade pip
                         Traceback (most recent call last):
                           File "D:\SD-Next\extensions\adetailer\install.py", line 77, in <module>
                             install()
                           File "D:\SD-Next\extensions\adetailer\install.py", line 66, in install
                             run_pip(*pkgs)
                           File "D:\SD-Next\extensions\adetailer\install.py", line 41, in run_pip
                             subprocess.run([sys.executable, "-m", "pip", "install", *args], check=True)
                           File "C:\Users\TalNy\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 526, in run
                             raise CalledProcessError(retcode, process.args,
                         subprocess.CalledProcessError: Command '['D:\\SD-Next\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'ultralytics>=8.2.0',
                         'mediapipe>=0.10.13']' returned non-zero exit status 1.

12:31:16-831234 INFO     Disabled extensions: ['sdnext-modernui']
12:31:16-888298 DEBUG    Extension list: processed=391 installed=1 enabled=1 disabled=0 visible=2 hidden=389
```

### Console logs, from start to end.

```Shell
Details from SD.Next:

12:28:47-486318 INFO     Starting SD.Next
12:28:47-488316 INFO     Logger: file="D:\SD-Next\sdnext.log" level=DEBUG size=65 mode=create
12:28:47-489567 INFO     Python version=3.10.11 platform=Windows bin="D:\SD-Next\venv\Scripts\python.exe" venv="D:\SD-Next\venv"
12:28:47-597584 INFO     Version: app=sd.next updated=2024-08-31 hash=bab17a0b branch=master url=https://github.com/vladmandic/automatic/tree/master ui=main      
12:28:47-872790 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 183 Stepping 1, GenuineIntel system=Windows release=Windows-10-10.0.19045-SP0
                         python=3.10.11
12:28:47-873790 DEBUG    Setting environment tuning
12:28:47-874791 INFO     HF cache folder: C:\Users\TalNy\.cache\huggingface\hub
12:28:47-875791 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
12:28:47-885768 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
12:28:47-886768 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
12:28:47-890768 INFO     nVidia CUDA toolkit detected: nvidia-smi present
12:28:48-464066 INFO     Verifying requirements
12:28:48-470075 INFO     Verifying packages
12:28:48-496174 DEBUG    Repository update time: Sat Aug 31 22:57:34 2024
12:28:48-497171 INFO     Startup: standard
12:28:48-498171 INFO     Verifying submodules
12:28:50-136046 DEBUG    Submodule: extensions-builtin/sd-extension-chainner / main
12:28:50-222642 DEBUG    Submodule: extensions-builtin/sd-extension-system-info / main
12:28:50-283001 DEBUG    Submodule: extensions-builtin/sd-webui-agent-scheduler / main
12:28:50-395002 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=main
12:28:50-396002 DEBUG    Submodule: extensions-builtin/sdnext-modernui / main
12:28:50-457002 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-rembg / master
12:28:50-514911 DEBUG    Submodule: modules/k-diffusion / master
12:28:50-589925 DEBUG    Git detached head detected: folder="wiki" reattach=master
12:28:50-590924 DEBUG    Submodule: wiki / master
12:28:50-618926 DEBUG    Register paths
12:28:50-647924 DEBUG    Installed packages: 175
12:28:50-648925 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sdnext-modernui',
                         'stable-diffusion-webui-rembg']
12:28:50-721967 DEBUG    Running extension installer: D:\SD-Next\extensions-builtin\sd-webui-agent-scheduler\install.py
12:28:50-924149 DEBUG    Running extension installer: D:\SD-Next\extensions-builtin\stable-diffusion-webui-rembg\install.py
12:28:51-103022 DEBUG    Extensions all: []
12:28:51-104033 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sdnext-modernui',
                         'stable-diffusion-webui-rembg']
12:28:51-106028 INFO     Verifying requirements
12:28:51-107028 DEBUG    Setup complete without errors: 1725445731
12:28:51-113030 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
12:28:51-114029 DEBUG    Starting module: <module 'webui' from 'D:\\SD-Next\\webui.py'>
12:28:51-115028 INFO     Command line args: ['--listen', '--insecure', '--debug'] insecure=True listen=True debug=True
12:28:51-116028 DEBUG    Env flags: []
12:28:58-046993 INFO     Load packages: {'torch': '2.4.1+cu124', 'diffusers': '0.30.2', 'gradio': '3.43.2'}
12:28:59-155107 INFO     VRAM: Detected=23.99 GB Optimization=none
12:28:59-158107 DEBUG    Read: file="config.json" json=36 bytes=1662 time=0.000
12:28:59-159621 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product" mode=no_grad
12:28:59-196133 INFO     Device: device=NVIDIA GeForce RTX 4090 n=1 arch=sm_90 cap=(8, 9) cuda=12.4 cudnn=90100 driver=560.94
12:28:59-202133 DEBUG    Read: file="html\reference.json" json=52 bytes=29118 time=0.004
12:28:59-638131 DEBUG    ONNX: version=1.19.0 provider=CUDAExecutionProvider, available=['AzureExecutionProvider', 'CPUExecutionProvider']
12:28:59-798173 DEBUG    Importing LDM
12:28:59-815465 DEBUG    Entering start sequence
12:28:59-816467 DEBUG    Initializing
12:28:59-838466 INFO     Available VAEs: path="D:\SD-Storage\models\VAE" items=1
12:28:59-839465 DEBUG    Available UNets: path="D:\SD-Storage\models\UNET" items=0
12:28:59-840466 INFO     Disabled extensions: ['sdnext-modernui']
12:28:59-844465 DEBUG    Read: file="cache.json" json=2 bytes=374 time=0.003
12:28:59-852472 DEBUG    Read: file="metadata.json" json=142 bytes=509543 time=0.007
12:28:59-854473 DEBUG    Scanning diffusers cache: folder=D:\SD-Storage\models\Diffusers items=1 time=0.00
12:28:59-855473 INFO     Available models: path="D:\SD-Storage\models\Stable-diffusion" items=23 time=0.01
12:29:00-254791 DEBUG    Load extensions
12:29:00-303986 INFO     Extension: script='extensions-builtin\Lora\scripts\lora_script.py' [2;36m12:29:00-300986[0m[2;36m [0m[34mINFO    [0m LoRA networks:      
                         [33mavailable[0m=[1;36m120[0m [33mfolders[0m=[1;36m2[0m
12:29:00-735581 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using sqlite file:
                         extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
12:29:00-745581 DEBUG    Extensions init time: 0.49 sd-webui-agent-scheduler=0.39
12:29:00-760679 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2672 time=0.005
12:29:00-765680 DEBUG    Read: file="extensions-builtin\sd-extension-chainner\models.json" json=24 bytes=2719 time=0.004
12:29:00-767679 DEBUG    chaiNNer models: path="D:\SD-Storage\models\chaiNNer" defined=24 discovered=0 downloaded=1
12:29:00-768679 DEBUG    Upscaler type=ESRGAN folder="D:\SD-Storage\models\ESRGAN" model="4x-UltraSharp" path="D:\SD-Storage\models\ESRGAN\4x-UltraSharp.pth"     
12:29:00-770679 DEBUG    Load upscalers: total=54 downloaded=12 user=1 time=0.02 ['None', 'Lanczos', 'Nearest', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'LDSR',
                         'RealESRGAN', 'SCUNet', 'SD', 'SwinIR']
12:29:01-223444 DEBUG    Load styles: folder="D:\SD-Storage\models\styles" items=342 time=0.45
12:29:01-227445 DEBUG    Creating UI
12:29:01-228623 DEBUG    UI themes available: type=Standard themes=12
12:29:01-229445 INFO     UI theme: type=Standard name="black-teal"
12:29:01-232445 DEBUG    UI theme: css="D:\SD-Next\javascript\black-teal.css" base="sdnext.css" user="None"
12:29:01-234445 DEBUG    UI initialize: txt2img
12:29:01-301147 DEBUG    Networks: page='model' items=74 subfolders=2 tab=txt2img folders=['D:\\SD-Storage\\models\\Stable-diffusion',
                         'D:\\SD-Storage\\models\\Diffusers', 'models\\Reference'] list=0.05 thumb=0.02 desc=0.00 info=0.02 workers=4 sort=Default
12:29:01-307148 DEBUG    Networks: page='lora' items=120 subfolders=0 tab=txt2img folders=['D:\\SD-Storage\\models\\Lora', 'D:\\SD-Storage\\models\\LyCORIS']     
                         list=0.05 thumb=0.01 desc=0.02 info=0.09 workers=4 sort=Default
12:29:01-321156 DEBUG    Networks: page='style' items=342 subfolders=1 tab=txt2img folders=['D:\\SD-Storage\\models\\styles', 'html'] list=0.05 thumb=0.01        
                         desc=0.00 info=0.00 workers=4 sort=Default
12:29:01-324155 DEBUG    Networks: page='embedding' items=16 subfolders=0 tab=txt2img folders=['D:\\SD-Storage\\models\\embeddings'] list=0.03 thumb=0.01
                         desc=0.00 info=0.01 workers=4 sort=Default
12:29:01-326154 DEBUG    Networks: page='vae' items=1 subfolders=0 tab=txt2img folders=['D:\\SD-Storage\\models\\VAE'] list=0.01 thumb=0.01 desc=0.00 info=0.00   
                         workers=4 sort=Default
12:29:01-379193 DEBUG    UI initialize: img2img
12:29:01-455410 DEBUG    UI initialize: control models=D:\SD-Storage\models\control
12:29:01-767163 DEBUG    Read: file="ui-config.json" json=29 bytes=1436 time=0.004
12:29:01-847223 DEBUG    UI themes available: type=Standard themes=12
12:29:01-950753 DEBUG    Reading failed: D:\SD-Next\html\extensions.json [Errno 2] No such file or directory: 'D:\\SD-Next\\html\\extensions.json'
12:29:01-951754 INFO     Extension list is empty: refresh required
12:29:02-350539 DEBUG    Extension list: processed=6 installed=6 enabled=5 disabled=1 visible=6 hidden=0
12:29:02-541467 DEBUG    Root paths: ['D:\\SD-Next']
12:29:04-632312 INFO     Local URL: http://localhost:7860/
12:29:04-633312 DEBUG    Gradio functions: registered=1721
12:29:04-635312 DEBUG    FastAPI middleware: ['Middleware', 'Middleware']
12:29:04-638312 DEBUG    Creating API
12:29:04-740056 INFO     [AgentScheduler] Task queue is empty
12:29:04-741083 INFO     [AgentScheduler] Registering APIs
12:29:04-806317 DEBUG    Scripts setup: ['IP Adapters:0.018', 'AnimateDiff:0.006', 'X/Y/Z Grid:0.01', 'Face:0.013']
12:29:04-807327 DEBUG    Model metadata: file="metadata.json" no changes
12:29:04-808501 DEBUG    Torch mode: deterministic=False
12:29:04-835840 DEBUG    Desired Torch parameters: dtype=FP16 no-half=False no-half-vae=False upscast=False
12:29:04-836834 INFO     Setting Torch parameters: device=cuda dtype=torch.float16 vae=torch.float16 unet=torch.float16 context=no_grad fp16=True bf16=None       
                         optimization=Scaled-Dot-Product
12:29:04-838840 DEBUG    Model requested: fn=<lambda>
12:29:04-840437 INFO     Select: model="zavychromaxl_v90 [08e878758a]"
12:29:04-841442 DEBUG    Load model: existing=False target=D:\SD-Storage\models\Stable-diffusion\zavychromaxl_v90.safetensors info=None
12:29:04-842442 DEBUG    Diffusers loading: path="D:\SD-Storage\models\Stable-diffusion\zavychromaxl_v90.safetensors"
12:29:04-842442 INFO     Autodetect: model="Stable Diffusion XL" class=StableDiffusionXLPipeline
                         file="D:\SD-Storage\models\Stable-diffusion\zavychromaxl_v90.safetensors" size=6617MB
Loading pipeline components... 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7  [ 0:00:00 < 0:00:00 , 10 C/s ]12:29:05-493458 DEBUG    Setting model: pipeline=StableDiffusionXLPipeline config={'low_cpu_mem_usage': True, 'torch_dtype': torch.float16,
                         'load_connected_pipeline': True, 'extract_ema': False, 'config': 'configs/sdxl', 'use_safetensors': True, 'cache_dir':
                         'C:\\Users\\TalNy\\.cache\\huggingface\\hub'}
12:29:07-771269 INFO     Load embeddings: loaded=5 skipped=11 time=2.28
12:29:07-773269 DEBUG    Setting model: enable VAE slicing
12:29:07-787268 DEBUG    Read: file="D:\SD-Next\configs\sdxl\vae\config.json" json=15 bytes=674 time=0.000
12:29:10-426248 DEBUG    GC: utilization={'gpu': 35, 'ram': 2, 'threshold': 80} gc={'collected': 362, 'saved': 0.0} before={'gpu': 8.45, 'ram': 1.47}
                         after={'gpu': 8.45, 'ram': 1.47, 'retries': 0, 'oom': 0} device=cuda fn=load_diffuser time=0.13
12:29:10-432249 INFO     Load model: time=5.45 load=0.65 embeddings=2.28 move=2.51 native=1024 {'ram': {'used': 1.47, 'total': 63.75}, 'gpu': {'used': 8.45,      
                         'total': 23.99}, 'retries': 0, 'oom': 0}
12:29:10-435248 DEBUG    Script callback init time: task_scheduler.py:app_started=0.08
12:29:10-436248 DEBUG    Save: file="config.json" json=36 bytes=1611 time=0.001
12:29:10-436248 INFO     Startup time: 19.32 torch=4.58 gradio=1.44 diffusers=0.91 libraries=1.75 extensions=0.49 face-restore=0.40 networks=0.46 ui-en=0.16      
                         ui-img2img=0.05 ui-control=0.08 ui-models=0.15 ui-settings=0.18 ui-extensions=0.42 ui-defaults=0.16 launch=2.12 api=0.06 app-started=0.11                         checkpoint=5.63
```

**Comment by hw25io** [comment]
The bot mentioned this:

pip install ultralytics>=8.2.0
pip install mediapipe>=0.10.13

but, installation of ultralytics failed with:

```
pip install ultralytics>=8.2.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
optimum 1.21.4 requires transformers[sentencepiece]<4.44.0,>=4.29.0, but you have transformers 4.44.2 which is incompatible.
```
After downgrading transformers and installing ultralytics and mediapipe, SD.Next is upgrading transformers again:

```
12:48:50-650938 INFO     Install: package="transformers==4.44.2" mode=pip
12:48:50-651951 DEBUG    Running: pip="install --upgrade transformers==4.44.2"
```

That's where the cat bites its own tail ... :)

**Comment by hw25io** [comment]
Update: after downgrading transformers in the requirements.txt of SD.Next from 4.44.2 to 4.43.4 it's working again, inkluding adetailer.

Everything seems to be working for the moment, but of course I don't know if there are any undesirable side effects ...

**Comment by Bing-su** [comment]
This report seems to be a mix of a permissions issue and a version issue...

As a side note, pip will not fail the install even if it throws dependency conflict error.
