### ISSUE TITLE
[Bug]: "Feature: Filter k most confident masks" (Commit 9ceb586) seems to break mediapipe_face_mesh functions

### ISSUE THREAD

**Issue by BagronkeN** [Bing-su/adetailer#737]
### Describe the bug

Hi,

[Commit 9ceb586](https://github.com/Bing-su/adetailer/commit/9ceb58685a7639b1a6a6c6ca2ab7a7b9d750cf6f), which added "Feature: Filter k most confident masks" seems to break the two **mediapipe_face_mesh** models (**mediapipe_face_mesh** + **mediapipe_face_mesh_eyes_only**).

This commit was recently brought into main, and I can no longer run mediapipe_face_mesh or mediapipe_face_mesh_eyes_only, resulting in an **IndexError: list index out of range** error.

This is _possibly_ because the mesh models do not use the same confidence-detection (**mediapipe_face_detection**) as the other **mediapipe_face** models (**mediapipe_face_short** + **mediapipe_face_full**, which still work).

I can't be sure about the exact reason, since I don't have an environment to run debug on this, but my guess is the change in args when the function changed from slider to radio-buttons has something to do with it.

I have tried a fresh install of the extension on A1111, and different versions of mediapipe (0.10.14, 0.10.15, 0.10.18), but this errors seems to be in the python code. Going back to Commit 7538620 solves the issue for me.

I have also tried with a fresh install of WebUI Forge, which results in the same error.

Please let me know if you can't reproduce this on your end, and I can check further on my end.

### Steps to reproduce

Use detection model mediapipe_face_mesh or mediapipe_face_mesh_eyes_only.

### Console logs, from start to end.

```Shell
*** Error running postprocess_image: C:\StableDiffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 912, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\StableDiffusion\stable-diffusion-webui\extensions\adetailer\aaaaaa\traceback.py", line 173, in wrapper
        raise error from None
    IndexError:
    ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
    │                                                        System info                                                                                                                   │
    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                                                           │
    │ ┃             ┃ Value                                                                                                    ┃                                                           │
    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩                                                           │
    │ │    Platform │ Windows-10-10.0.19045-SP0                                                                                │                                                           │
    │ │      Python │ 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]                         │                                                           │
    │ │     Version │ v1.10.1                                                                                                  │                                                           │
    │ │      Commit │ 82a973c04367123ae98bd9abdf80d9eda9b910e2                                                                 │                                                           │
    │ │ Commandline │ ['launch.py', '--xformers']                                                                              │                                                           │
    │ │   Libraries │ {'torch': '2.1.2+cu121', 'torchvision': '0.16.2+cu121', 'ultralytics': '8.2.38', 'mediapipe': '0.10.14'} │                                                           │
    │ └─────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────┘                                                           │
    │                              Inputs                                                                                                                                                  │
    │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                                                                                                                     │
    │ ┃                 ┃ Value                                      ┃                                                                                                                     │
    │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩                                                                                                                     │
    │ │          prompt │ 1man, sad face because of bugs in the code │                                                                                                                     │
    │ │ negative_prompt │ happy face                                 │                                                                                                                     │
    │ │          n_iter │ 1                                          │                                                                                                                     │
    │ │      batch_size │ 1                                          │                                                                                                                     │
    │ │           width │ 960                                        │                                                                                                                     │
    │ │          height │ 1536                                       │                                                                                                                     │
    │ │    sampler_name │ Euler a                                    │                                                                                                                     │
    │ │       enable_hr │ False                                      │                                                                                                                     │
    │ │     hr_upscaler │ Latent                                     │                                                                                                                     │
    │ │      checkpoint │ cyberrealisticPony_v64.safetensors         │                                                                                                                     │
    │ │             vae │ Automatic                                  │                                                                                                                     │
    │ │            unet │ Automatic                                  │                                                                                                                     │
    │ └─────────────────┴────────────────────────────────────────────┘                                                                                                                     │
    │                   ADetailer                                                                                                                                                          │
    │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┓                                                                                                                                        │
    │ ┃                     ┃ Value               ┃                                                                                                                                        │
    │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━┩                                                                                                                                        │
    │ │             version │ 24.11.0             │                                                                                                                                        │
    │ │            ad_model │ mediapipe_face_mesh │                                                                                                                                        │
    │ │           ad_prompt │                     │                                                                                                                                        │
    │ │  ad_negative_prompt │                     │                                                                                                                                        │
    │ │ ad_controlnet_model │ None                │                                                                                                                                        │
    │ │              is_api │ False               │                                                                                                                                        │
    │ └─────────────────────┴─────────────────────┘                                                                                                                                        │
    │ ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮                                                                                 │
    │ │ C:\StableDiffusion\stable-diffusion-webui\extensions\adetailer\aaaaaa\traceback.py:153 in        │                                                                                 │
    │ │ wrapper                                                                                          │                                                                                 │
    │ │                                                                                                  │                                                                                 │
    │ │   152 │   │   try:                                                                               │                                                                                 │
    │ │ ❱ 153 │   │   │   return func(*args, **kwargs)                                                   │                                                                                 │
    │ │   154 │   │   except Exception as e:                                                             │                                                                                 │
    │ │                                                                                                  │                                                                                 │
    │ │ C:\StableDiffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py:916 in      │                                                                                 │
    │ │ postprocess_image                                                                                │                                                                                 │
    │ │    915 │   │   │   │   │   continue                                                              │                                                                                 │
    │ │ ❱  916 │   │   │   │   is_processed |= self._postprocess_image_inner(p, pp, args, n=n)           │                                                                                 │
    │ │    917                                                                                           │                                                                                 │
    │ │                                                                                                  │                                                                                 │
    │ │ C:\StableDiffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py:844 in      │                                                                                 │
    │ │ _postprocess_image_inner                                                                         │                                                                                 │
    │ │                                                                                                  │                                                                                 │
    │ │    843 │   │                                                                                     │                                                                                 │
    │ │ ❱  844 │   │   masks = self.pred_preprocessing(p, pred, args)                                    │                                                                                 │
    │ │    845 │   │   shared.state.assign_current_image(pred.preview)                                   │                                                                                 │
    │ │                                                                                                  │                                                                                 │
    │ │ C:\StableDiffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py:608 in      │                                                                                 │
    │ │ pred_preprocessing                                                                               │                                                                                 │
    │ │                                                                                                  │                                                                                 │
    │ │    607 │   def pred_preprocessing(self, p, pred: PredictOutput, args: ADetailerArgs):            │                                                                                 │
    │ │ ❱  608 │   │   pred = filter_by_ratio(                                                           │                                                                                 │
    │ │    609 │   │   │   pred, low=args.ad_mask_min_ratio, high=args.ad_mask_max_ratio                 │                                                                                 │
    │ │                                                                                                  │                                                                                 │
    │ │ C:\StableDiffusion\stable-diffusion-webui\extensions\adetailer\adetailer\mask.py:228 in          │                                                                                 │
    │ │ filter_by_ratio                                                                                  │                                                                                 │
    │ │                                                                                                  │                                                                                 │
    │ │   227 │   pred.masks = [pred.masks[i] for i in idx]                                              │                                                                                 │
    │ │ ❱ 228 │   pred.confidences = [pred.confidences[i] for i in idx]                                  │                                                                                 │
    │ │   229 │   return pred                                                                            │                                                                                 │
    │ │                                                                                                  │                                                                                 │
    │ │ C:\StableDiffusion\stable-diffusion-webui\extensions\adetailer\adetailer\mask.py:228 in          │                                                                                 │
    │ │ <listcomp>                                                                                       │                                                                                 │
    │ │                                                                                                  │                                                                                 │
    │ │   227 │   pred.masks = [pred.masks[i] for i in idx]                                              │                                                                                 │
    │ │ ❱ 228 │   pred.confidences = [pred.confidences[i] for i in idx]                                  │                                                                                 │
    │ │   229 │   return pred                                                                            │                                                                                 │
    │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯                                                                                 │
    │ IndexError: list index out of range                                                                                                                                                  │
    ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

### List of installed extensions

None, I tried to disable them all, but same result.

**Comment by Bing-su** [comment]
My apologies for the bug. I've put a fix in place.

**Comment by BagronkeN** [comment]
I've tested the new code on my install, and the mesh models both work now.

Thank you so much for the quick fix and your awesome efforts!
