### ISSUE TITLE
[Bug]: adetailer crashes if euler smea dy cfg++ sampler is used (reforge)

### ISSUE THREAD

**Issue by Hugs288** [Bing-su/adetailer#759]
### Describe the bug

adetailer crashes if euler smea dy cfg++ sampler is used (reforge)

simply using a seperate sampler gives no error

### Steps to reproduce

enable adetailer on image with euler smea dy cfg++ sampler

### Screenshots

![image](https://github.com/user-attachments/assets/913df10e-27da-49e3-a36c-096d4a646e4a)
![image](https://github.com/user-attachments/assets/ffccdd26-4c56-4730-8f1d-0f1ae2102122)

### Console logs, from start to end.

```Shell
venv "J:\aistuff\stable-diffusion-webui-reForge\venv\Scripts\Python.exe"
Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Version: f1.5.0dev2-v1.10.1RC-latest-1802-gb704df5e
Commit hash: b704df5eb7ca63a483fd3514abb894c5f4a1cfe9
Launching Web UI with arguments: --skip-python-version-check --ckpt-dir 'J:\aistuff\stable-diffusion-webui-forge\models\Stable-diffusion' --hypernetwork-dir 'J:\aistuff\stable-diffusion-webui-forge\models\hypernetworks' --embeddings-dir 'J:\aistuff\stable-diffusion-webui-forge\embeddings' --lora-dir 'J:\aistuff\stable-diffusion-webui-forge\models\Lora' --vae-dir 'J:\aistuff\stable-diffusion-webui-forge\models\vae'
Total VRAM 24564 MB, total RAM 32417 MB
pytorch version: 2.5.1+cu124
Set vram state to: {vram_state.name}
Device: cuda:0 NVIDIA GeForce RTX 4090 : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: [torch.bfloat16, torch.bfloat16, torch.float16, torch.float32]
CUDA Stream Activated:  False
J:\aistuff\stable-diffusion-webui-reForge\venv\Lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
J:\aistuff\stable-diffusion-webui-reForge\venv\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
ControlNet preprocessor location: J:\aistuff\stable-diffusion-webui-reForge\models\ControlNetPreprocessor
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
person_yolov8n-seg.pt: 100%|██████████████████████████████████████████████████████| 6.78M/6.78M [00:00<00:00, 8.45MB/s]
hand_yolov8n.pt: 100%|████████████████████████████████████████████████████████████| 6.24M/6.24M [00:00<00:00, 6.67MB/s]
face_yolov8s.pt: 100%|████████████████████████████████████████████████████████████| 22.5M/22.5M [00:01<00:00, 14.5MB/s]
face_yolov8n.pt: 100%|████████████████████████████████████████████████████████████| 6.23M/6.23M [00:01<00:00, 3.97MB/s]
person_yolov8s-seg.pt: 100%|██████████████████████████████████████████████████████| 23.9M/23.9M [00:01<00:00, 13.2MB/s]
yolov8x-worldv2.pt: 100%|███████████████████████████████████████████████████████████| 146M/146M [00:05<00:00, 27.5MB/s]
[-] ADetailer initialized. version: 24.11.1, num models: 10████████████████▍      | 21.0M/23.9M [00:01<00:00, 12.9MB/s]
<module 'scripts' (<_frozen_importlib_external.NamespaceLoader object at 0x000002330A8D6090>)> None ['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'iib', 'logging', 'model_keyword_support', 'shared_paths', 'tag_frequency_db']
Loading model noobaiXLNAIXL_vPred10Version.safetensors [ea349eeae8] (1 of 1)████████| 146M/146M [00:05<00:00, 43.1MB/s]
Loading weights [ea349eeae8] from J:\aistuff\stable-diffusion-webui-forge\models\Stable-diffusion\noobaiXLNAIXL_vPred10Version.safetensors
2024-12-27 18:14:14,239 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860
[TIPO-KGen]-|21:08:49|-INFO: Processing propmt: 1girl, duramente \(umamusume\), umamusum...
[TIPO-KGen]-|21:08:49|-INFO: Processing with seed: 1782821780
[TIPO-KGen]-|21:08:51|-INFO: Prompt processing done.
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:04<00:00,  6.20it/s]
Total progress: 32it [00:05,  6.17it/s]
Error parsing "TIPO nl prompt: "89it/s]
Error parsing "TIPO nl prompt: "
[TIPO-KGen]-|21:11:04|-INFO: Processing propmt: 1girl, duramente \(umamusume\), umamusum...
[TIPO-KGen]-|21:11:04|-INFO: Processing with seed: 359039126
[TIPO-KGen]-|21:11:06|-INFO: Prompt processing done.
                                                                                                                       Cleanup minimal inference memory.                                                                | 0/30 [00:00<?, ?it/s]
tiled upscale: 100%|███████████████████████████████████████████████████████████████████| 24/24 [00:01<00:00, 20.33it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [00:05<00:00,  2.79it/s]
J:\aistuff\stable-diffusion-webui-reForge\modules_forge\patch_basic.py:13: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  result = original_loader(*args, **kwargs)

0: 640x448 1 face, 7.0ms
Speed: 1.0ms preprocess, 7.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 448)
  0%|                                                                                           | 0/10 [00:00<?, ?it/s]
*** Error running postprocess_image: J:\aistuff\stable-diffusion-webui-reForge\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "J:\aistuff\stable-diffusion-webui-reForge\modules\scripts.py", line 948, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "J:\aistuff\stable-diffusion-webui-reForge\extensions\adetailer\aaaaaa\traceback.py", line 173, in wrapper
        raise error from None
    RuntimeError:
    ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
    │                                                   System info                                                    │
    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃             ┃ Value                                                                                          ┃ │
    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │    Platform │ Windows-10-10.0.26100-SP0                                                                      │ │
    │ │      Python │ 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]               │ │
    │ │     Version │ f1.5.0dev2-v1.10.1RC-latest-1802-gb704df5e                                                     │ │
    │ │      Commit │ b704df5eb7ca63a483fd3514abb894c5f4a1cfe9                                                       │ │
    │ │ Commandline │ ['launch.py', '--skip-python-version-check', '--ckpt-dir',                                     │ │
    │ │             │ 'J:\\aistuff\\stable-diffusion-webui-forge\\models\\Stable-diffusion', '--hypernetwork-dir',   │ │
    │ │             │ 'J:\\aistuff\\stable-diffusion-webui-forge\\models\\hypernetworks', '--embeddings-dir',        │ │
    │ │             │ 'J:\\aistuff\\stable-diffusion-webui-forge\\embeddings', '--lora-dir',                         │ │
    │ │             │ 'J:\\aistuff\\stable-diffusion-webui-forge\\models\\Lora', '--vae-dir',                        │ │
    │ │             │ 'J:\\aistuff\\stable-diffusion-webui-forge\\models\\vae']                                      │ │
    │ │   Libraries │ {'torch': '2.5.1+cu124', 'torchvision': '0.20.1+cu124', 'ultralytics': '8.3.55', 'mediapipe':  │ │
    │ │             │ '0.10.14'}                                                                                     │ │
    │ └─────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘ │
    │                                                      Inputs                                                      │
    │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃                 ┃ Value                                                                                      ┃ │
    │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │          prompt │ __booru1girlWildcardFor_v10/CharacterBooru__, <lora:kohakuvpred:1> kohaku \(csacu\),       │ │
    │ │                 │ masterpiece, best quality, newest, absurdres, highres                                      │ │
    │ │ negative_prompt │                                                                                            │ │
    │ │          n_iter │ 1                                                                                          │ │
    │ │      batch_size │ 1                                                                                          │ │
    │ │           width │ 832                                                                                        │ │
    │ │          height │ 1216                                                                                       │ │
    │ │    sampler_name │ Euler SMEA DY CFG++                                                                        │ │
    │ │       enable_hr │ True                                                                                       │ │
    │ │     hr_upscaler │ R-ESRGAN 4x+ Anime6B                                                                       │ │
    │ │      checkpoint │ noobaiXLNAIXL_vPred10Version.safetensors                                                   │ │
    │ │             vae │ Automatic                                                                                  │ │
    │ │            unet │ Automatic                                                                                  │ │
    │ └─────────────────┴────────────────────────────────────────────────────────────────────────────────────────────┘ │
    │                 ADetailer                                                                                        │
    │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓                                                                        │
    │ ┃                     ┃ Value           ┃                                                                        │
    │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩                                                                        │
    │ │             version │ 24.11.1         │                                                                        │
    │ │            ad_model │ face_yolov8n.pt │                                                                        │
    │ │           ad_prompt │                 │                                                                        │
    │ │  ad_negative_prompt │                 │                                                                        │
    │ │ ad_controlnet_model │ None            │                                                                        │
    │ │              is_api │ False           │                                                                        │
    │ └─────────────────────┴─────────────────┘                                                                        │
    │ ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮             │
    │ │ J:\aistuff\stable-diffusion-webui-reForge\extensions\adetailer\aaaaaa\traceback.py:153 in        │             │
    │ │ wrapper                                                                                          │             │
    │ │                                                                                                  │             │
    │ │   152 │   │   try:                                                                               │             │
    │ │ ❱ 153 │   │   │   return func(*args, **kwargs)                                                   │             │
    │ │   154 │   │   except Exception as e:                                                             │             │
    │ │                                                                                                  │             │
    │ │ J:\aistuff\stable-diffusion-webui-reForge\extensions\adetailer\scripts\!adetailer.py:916 in      │             │
    │ │ postprocess_image                                                                                │             │
    │ │                                                                                                  │             │
    │ │    915 │   │   │   │   │   continue                                                              │             │
    │ │ ❱  916 │   │   │   │   is_processed |= self._postprocess_image_inner(p, pp, args, n=n)           │             │
    │ │    917                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ J:\aistuff\stable-diffusion-webui-reForge\extensions\adetailer\scripts\!adetailer.py:873 in      │             │
    │ │ _postprocess_image_inner                                                                         │             │
    │ │                                                                                                  │             │
    │ │    872 │   │   │   try:                                                                          │             │
    │ │ ❱  873 │   │   │   │   processed = process_images(p2)                                            │             │
    │ │    874 │   │   │   except NansException as e:                                                    │             │
    │ │                                                                                                  │             │
    │ │ J:\aistuff\stable-diffusion-webui-reForge\modules\processing.py:823 in process_images            │             │
    │ │                                                                                                  │             │
    │ │    822 │   │   │   with profiling.Profiler():                                                    │             │
    │ │ ❱  823 │   │   │   │   res = process_images_inner(p)                                             │             │
    │ │    824                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ J:\aistuff\stable-diffusion-webui-reForge\modules\processing.py:981 in process_images_inner      │             │
    │ │                                                                                                  │             │
    │ │    980 │   │   │   │                                                                             │             │
    │ │ ❱  981 │   │   │   │   samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.u  │             │
    │ │    982                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ J:\aistuff\stable-diffusion-webui-reForge\modules\processing.py:1803 in sample                   │             │
    │ │                                                                                                  │             │
    │ │   1802 │   │   │                                                                                 │             │
    │ │ ❱ 1803 │   │   │   samples = self.sampler.sample_img2img(self, self.init_latent, x, conditionin  │             │
    │ │   1804                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ J:\aistuff\stable-diffusion-webui-reForge\modules_forge\forge_alter_samplers.py:136 in           │             │
    │ │ sample_img2img                                                                                   │             │
    │ │                                                                                                  │             │
    │ │   135 │   │   self.scheduler_name = p.scheduler                                                  │             │
    │ │ ❱ 136 │   │   return super().sample_img2img(p, x, noise, conditioning, unconditional_condition   │             │
    │ │   137                                                                                            │             │
    │ │                                                                                                  │             │
    │ │ J:\aistuff\stable-diffusion-webui-reForge\modules\sd_samplers_kdiffusion.py:238 in               │             │
    │ │ sample_img2img                                                                                   │             │
    │ │                                                                                                  │             │
    │ │   237 │   │                                                                                      │             │
    │ │ ❱ 238 │   │   samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg,   │             │
    │ │   239                                                                                            │             │
    │ │                                                                                                  │             │
    │ │ J:\aistuff\stable-diffusion-webui-reForge\modules\sd_samplers_common.py:280 in launch_sampling   │             │
    │ │                                                                                                  │             │
    │ │   279 │   │   try:                                                                               │             │
    │ │ ❱ 280 │   │   │   return func()                                                                  │             │
    │ │   281 │   │   except RecursionError:                                                             │             │
    │ │                                                                                                  │             │
    │ │ J:\aistuff\stable-diffusion-webui-reForge\modules\sd_samplers_kdiffusion.py:238 in <lambda>      │             │
    │ │                                                                                                  │             │
    │ │   237 │   │                                                                                      │             │
    │ │ ❱ 238 │   │   samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg,   │             │
    │ │   239                                                                                            │             │
    │ │                                                                                                  │             │
    │ │ J:\aistuff\stable-diffusion-webui-reForge\venv\Lib\site-packages\torch\utils\_contextlib.py:116  │             │
    │ │ in decorate_context                                                                              │             │
    │ │                                                                                                  │             │
    │ │   115 │   │   with ctx_factory():                                                                │             │
    │ │ ❱ 116 │   │   │   return func(*args, **kwargs)                                                   │             │
    │ │   117                                                                                            │             │
    │ │                                                                                                  │             │
    │ │ J:\aistuff\stable-diffusion-webui-reForge\ldm_patched\k_diffusion\sampling.py:2268 in            │             │
    │ │ sample_euler_smea_dy_cfg_pp                                                                      │             │
    │ │                                                                                                  │             │
    │ │   2267 │   │   │   if i + 1 // 2 == 0:                                                           │             │
    │ │ ❱ 2268 │   │   │   │   x = smea_sampling_step_cfg_pp(x, model, sigmas[i + 1], i, sigmas[i], sig  │             │
    │ │   2269 │   return x                                                                              │             │
    │ │                                                                                                  │             │
    │ │ J:\aistuff\stable-diffusion-webui-reForge\venv\Lib\site-packages\torch\utils\_contextlib.py:116  │             │
    │ │ in decorate_context                                                                              │             │
    │ │                                                                                                  │             │
    │ │   115 │   │   with ctx_factory():                                                                │             │
    │ │ ❱ 116 │   │   │   return func(*args, **kwargs)                                                   │             │
    │ │   117                                                                                            │             │
    │ │                                                                                                  │             │
    │ │ J:\aistuff\stable-diffusion-webui-reForge\ldm_patched\k_diffusion\sampling.py:2204 in            │             │
    │ │ smea_sampling_step_cfg_pp                                                                        │             │
    │ │                                                                                                  │             │
    │ │   2203 │   with Rescaler(model, x, "nearest-exact", **extra_args) as rescaler:                   │             │
    │ │ ❱ 2204 │   │   denoised = model(x, sigma_hat * x.new_ones([x.shape[0]]), **rescaler.extra_args)  │             │
    │ │   2205 │   if callback is not None:                                                              │             │
    │ │                                                                                                  │             │
    │ │ J:\aistuff\stable-diffusion-webui-reForge\venv\Lib\site-packages\torch\nn\modules\module.py:1736 │             │
    │ │ in _wrapped_call_impl                                                                            │             │
    │ │                                                                                                  │             │
    │ │   1735 │   │   else:                                                                             │             │
    │ │ ❱ 1736 │   │   │   return self._call_impl(*args, **kwargs)                                       │             │
    │ │   1737                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ J:\aistuff\stable-diffusion-webui-reForge\venv\Lib\site-packages\torch\nn\modules\module.py:1747 │             │
    │ │ in _call_impl                                                                                    │             │
    │ │                                                                                                  │             │
    │ │   1746 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │             │
    │ │ ❱ 1747 │   │   │   return forward_call(*args, **kwargs)                                          │             │
    │ │   1748                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ J:\aistuff\stable-diffusion-webui-reForge\modules\sd_samplers_cfg_denoiser.py:245 in forward     │             │
    │ │                                                                                                  │             │
    │ │   244 │   │   │   if not self.mask_before_denoising and self.mask is not None:                   │             │
    │ │ ❱ 245 │   │   │   │   denoised = apply_blend(denoised)                                           │             │
    │ │   246 │   │   │   preview = self.sampler.last_latent = denoised                                  │             │
    │ │                                                                                                  │             │
    │ │ J:\aistuff\stable-diffusion-webui-reForge\modules\sd_samplers_cfg_denoiser.py:145 in apply_blend │             │
    │ │                                                                                                  │             │
    │ │   144 │   │   │   │   │   noisy_initial_latent = self.init_latent                                │             │
    │ │ ❱ 145 │   │   │   │   blended_latent = current_latent * self.nmask + noisy_initial_latent * se   │             │
    │ │   146                                                                                            │             │
    │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯             │
    │ RuntimeError: The size of tensor a (160) must match the size of tensor b (128) at non-singleton dimension 3      │
    ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

### List of installed extensions

![image](https://github.com/user-attachments/assets/0e2ad412-074e-4efa-a5ee-09fb9254daf6)

**Comment by Hugs288** [comment]
closing this issue and reporting it to reforge instead since i am pretty sure now this is a reforge problem and not an adetailer problem
