### ISSUE TITLE
Controlnet issues - Batch processing

### ISSUE THREAD

**Issue by alenknight** [Bing-su/adetailer#78]
first off, thanks for the recent patch that got controlnet with Adetailer working again!  greatly appreciate it.

next issue - which I'm hoping is along the same lines - when doing batch processing... it fails.  just get a black screen when batch running more than 1 image.... screenshot attached showing.
there's no error - just shows that no image was detected - (which makes sense considering it's a black box)
[-] ADetailer: nothing detected on image 2 with 1st settings.

- also, this occurs with any preprocessor of controlnet.

![Screenshot 2023-05-22 at 7 31 53 PM](https://github.com/Bing-su/adetailer/assets/22153900/0bac15b9-24a5-4e91-be22-26c4f990003e)

**Comment by xxaier** [comment]
same error , I use apple mac m2

```
Traceback (most recent call last):
  File "/Users/z/git/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/Users/z/git/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/Users/z/git/stable-diffusion-webui/modules/txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "/Users/z/git/stable-diffusion-webui/modules/processing.py", line 526, in process_images
    res = process_images_inner(p)
  File "/Users/z/git/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "/Users/z/git/stable-diffusion-webui/modules/processing.py", line 680, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "/Users/z/git/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 252, in process_sample
    return process.sample_before_CN_hack(*args, **kwargs)
  File "/Users/z/git/stable-diffusion-webui/modules/processing.py", line 907, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "/Users/z/git/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 377, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/Users/z/git/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 251, in launch_sampling
    return func()
  File "/Users/z/git/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 377, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/Users/z/git/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/z/git/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 553, in sample_dpmpp_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/Users/z/git/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/z/git/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 167, in forward
    devices.test_for_nans(x_out, "unet")
  File "/Users/z/git/stable-diffusion-webui/modules/devices.py", line 156, in test_for_nans
    raise NansException(message)
modules.devices.NansException: A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because
 your video card does not support half type. Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half comman
dline argument to fix this. Use --disable-nan-check commandline argument to disable this check.
```

**Comment by alenknight** [comment]
@Bing-su  - did you change something to address this or the worklow order?  with the latest build -55594a9ea64191f9e7afba9826fd69e0c9302387 of adetailer - and controlnet 54f7c64b4dc4a4206e76a152651d5f0b0fac248f .... it's now working in batch processing.  

latest version of controlnet fails.... but i marked that version for myself because i was able to get 1 image out of controlnet with it and it's last build that worked kinda... batch wasn't.  but now ADetailer works with it.

**Comment by Bing-su** [comment]
Yes, I fixed a few things, I verified that adetailer 23.5.18 and controlnet 1.1.191 work with batch count 2 and above, controlnet batch and img2img batch all work.

**Comment by Mistborn-First-Era** [comment]
working with control net 1.1.189 as well. Thank you for the fix

**Comment by alenknight** [comment]
works now.  thanks!
