### ISSUE TITLE
Error Loading script: !adetailer.py

### ISSUE THREAD

**Issue by gabyguo** [Bing-su/adetailer#79]
System prompt：Load a script to extend detail-main! adetailer.py failed. You may want to consider temporarily deactivating this extension or adjusting its version.

When I used Stable Diffusion, the first time I loaded the adetailer plug-in, the load failed. Following the prompt, I have switched to an older version and the glitch is still not resolved. Ask a professional to help solve this problem. Thank you!

**Comment by Bing-su** [comment]
Please post the full console log.

**Comment by WesleyNery** [comment]
I have the same problem:
Error loading script: !adetailer.py
```
Error loading script: !adetailer.py
Traceback (most recent call last):
  File "D:\torrents\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\torrents\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\torrents\StableDiffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 17, in <module>
    from adetailer import (
  File "D:\torrents\StableDiffusion\stable-diffusion-webui\extensions\adetailer\adetailer\__init__.py", line 2, in <module>
    from .args import AD_ENABLE, ALL_ARGS, ADetailerArgs, EnableChecker
  File "D:\torrents\StableDiffusion\stable-diffusion-webui\extensions\adetailer\adetailer\args.py", line 34, in <module>
    class ADetailerArgs(BaseModel, extra=Extra.forbid):
  File "D:\torrents\StableDiffusion\stable-diffusion-webui\extensions\adetailer\adetailer\args.py", line 61, in ADetailerArgs
    def check_ad_conf(cls, v: Any):  # noqa: N805
  File "pydantic\class_validators.py", line 93, in pydantic.class_validators.validator.dec
  File "pydantic\class_validators.py", line 152, in pydantic.class_validators._prepare_validator
pydantic.errors.ConfigError: duplicate validator function "adetailer.args.ADetailerArgs.check_ad_conf"; if this is intended, set `allow_reuse=True`
```

**Comment by gabyguo** [comment]
> 请发布完整的控制台日志。

Error loading script: !adetailer.py
Traceback (most recent call last):
  File "D:\new ai\miaoshouai-sd-webui-v230222full\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\new ai\miaoshouai-sd-webui-v230222full\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\new ai\miaoshouai-sd-webui-v230222full\extensions\adetailer\scripts\!adetailer.py", line 54, in <module>
    model_mapping = get_models(adetailer_dir, huggingface=not no_huggingface)
  File "D:\new ai\miaoshouai-sd-webui-v230222full\extensions\adetailer\adetailer\common.py", line 42, in get_models
    "person_yolov8n-seg.pt": hf_hub_download(
  File "D:\new ai\miaoshouai-sd-webui-v230222full\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\new ai\miaoshouai-sd-webui-v230222full\python\lib\site-packages\huggingface_hub\file_download.py", line 1259, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

**Comment by gabyguo** [comment]
> 请发布完整的控制台日志。

I can use it when I switch back to v23.5.8.  If you switch to a later version, an error message is displayed and the WebUI cannot be loaded.  Could you take a look, please?  Thank you!

**Comment by Bing-su** [comment]
This issue has been fixed today.

**Comment by gabyguo** [comment]
> 此问题已于今天修复。

Thank you very much. Problem solved.

**Comment by kohxtpbb250** [comment]
> > 请发布完整的控制台日志。
> 
> I can use it when I switch back to v23.5.8. If you switch to a later version, an error message is displayed and the WebUI cannot be loaded. Could you take a look, please? Thank you!



> > 请发布完整的控制台日志。
> 
> I can use it when I switch back to v23.5.8. If you switch to a later version, an error message is displayed and the WebUI cannot be loaded. Could you take a look, please? Thank you!

Hi, I would like to download adetailer v23.5.8 as you replied! I am also having errors with adetailer. I want to install v23.5.8 of adetailer as you replied can you tell me how?
