### ISSUE TITLE
error logs during post process

### ISSUE THREAD

**Issue by santamarias** [Bing-su/adetailer#98]
Error logs during post process below

Error running postprocess_batch: C:\webui\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui\modules\scripts.py", line 463, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "C:\webui\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 522, in postprocess_image
    self.cn_script.process(p)
  File "C:\webui\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 293, in process
    enabled, module, model, weight, image, scribble_mode, \
ValueError: not enough values to unpack (expected 12, got 0)

results seems little vague.. I think some part of extension still applied to results... but error logs... is this ok to leave it alone?

**Comment by santamarias** [comment]
To answer my own question,
version update and several reloads later, it was fixed.
